/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as types from "../../types/primitives.js";
import { SankaError } from "./sanka-error.js";

export type ContactsErrorResponseData = {
  message: string;
  ctxId?: string | null | undefined;
  errors?: { [k: string]: any } | null | undefined;
};

export class ContactsErrorResponse extends SankaError {
  ctxId?: string | null | undefined;
  errors?: { [k: string]: any } | null | undefined;

  /** The original data that was passed to this error instance. */
  data$: ContactsErrorResponseData;

  constructor(
    err: ContactsErrorResponseData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.ctxId != null) this.ctxId = err.ctxId;
    if (err.errors != null) this.errors = err.errors;

    this.name = "ContactsErrorResponse";
  }
}

/** @internal */
export const ContactsErrorResponse$inboundSchema: z.ZodMiniType<
  ContactsErrorResponse,
  unknown
> = z.pipe(
  z.object({
    message: types.string(),
    ctx_id: z.optional(z.nullable(types.string())),
    errors: z.optional(z.nullable(z.record(z.string(), z.any()))),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    const remapped = remap$(v, {
      "ctx_id": "ctxId",
    });

    return new ContactsErrorResponse(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
