/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { absencesCreatePublicAbsenceApiV2PublicAbsencesPost } from "../funcs/absences-create-public-absence-api-v2-public-absences-post.js";
import { absencesDeletePublicAbsenceApiV2PublicAbsencesAbsenceIdDelete } from "../funcs/absences-delete-public-absence-api-v2-public-absences-absence-id-delete.js";
import { absencesGetPublicAbsenceApiV2PublicAbsencesAbsenceIdGet } from "../funcs/absences-get-public-absence-api-v2-public-absences-absence-id-get.js";
import { absencesListPublicAbsencesApiV2PublicAbsencesGet } from "../funcs/absences-list-public-absences-api-v2-public-absences-get.js";
import { absencesUpdatePublicAbsenceApiV2PublicAbsencesAbsenceIdPut } from "../funcs/absences-update-public-absence-api-v2-public-absences-absence-id-put.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Absences extends ClientSDK {
  /**
   * List Public Absences
   */
  async listPublicAbsencesApiV2PublicAbsencesGet(
    request?:
      | operations.ListPublicAbsencesApiV2PublicAbsencesGetRequest
      | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListPublicAbsencesApiV2PublicAbsencesGetResponse> {
    return unwrapAsync(absencesListPublicAbsencesApiV2PublicAbsencesGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Public Absence
   */
  async createPublicAbsenceApiV2PublicAbsencesPost(
    request: operations.CreatePublicAbsenceApiV2PublicAbsencesPostRequest,
    options?: RequestOptions,
  ): Promise<operations.CreatePublicAbsenceApiV2PublicAbsencesPostResponse> {
    return unwrapAsync(absencesCreatePublicAbsenceApiV2PublicAbsencesPost(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Public Absence
   */
  async getPublicAbsenceApiV2PublicAbsencesAbsenceIdGet(
    request: operations.GetPublicAbsenceApiV2PublicAbsencesAbsenceIdGetRequest,
    options?: RequestOptions,
  ): Promise<
    operations.GetPublicAbsenceApiV2PublicAbsencesAbsenceIdGetResponse
  > {
    return unwrapAsync(absencesGetPublicAbsenceApiV2PublicAbsencesAbsenceIdGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update Public Absence
   */
  async updatePublicAbsenceApiV2PublicAbsencesAbsenceIdPut(
    request:
      operations.UpdatePublicAbsenceApiV2PublicAbsencesAbsenceIdPutRequest,
    options?: RequestOptions,
  ): Promise<
    operations.UpdatePublicAbsenceApiV2PublicAbsencesAbsenceIdPutResponse
  > {
    return unwrapAsync(
      absencesUpdatePublicAbsenceApiV2PublicAbsencesAbsenceIdPut(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Delete Public Absence
   */
  async deletePublicAbsenceApiV2PublicAbsencesAbsenceIdDelete(
    request:
      operations.DeletePublicAbsenceApiV2PublicAbsencesAbsenceIdDeleteRequest,
    options?: RequestOptions,
  ): Promise<
    operations.DeletePublicAbsenceApiV2PublicAbsencesAbsenceIdDeleteResponse
  > {
    return unwrapAsync(
      absencesDeletePublicAbsenceApiV2PublicAbsencesAbsenceIdDelete(
        this,
        request,
        options,
      ),
    );
  }
}
