/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { applicantsActivatePublicApplicant } from "../funcs/applicants-activate-public-applicant.js";
import { applicantsArchivePublicApplicant } from "../funcs/applicants-archive-public-applicant.js";
import { applicantsCreatePublicApplicant } from "../funcs/applicants-create-public-applicant.js";
import { applicantsGetPublicApplicant } from "../funcs/applicants-get-public-applicant.js";
import { applicantsListPublicApplicants } from "../funcs/applicants-list-public-applicants.js";
import { applicantsUpdatePublicApplicant } from "../funcs/applicants-update-public-applicant.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Applicants extends ClientSDK {
  /**
   * List Records
   */
  async listPublicApplicants(
    request?: operations.ListPublicApplicantsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListPublicApplicantsResponse> {
    return unwrapAsync(applicantsListPublicApplicants(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Record
   */
  async createPublicApplicant(
    request: operations.CreatePublicApplicantRequest,
    options?: RequestOptions,
  ): Promise<operations.CreatePublicApplicantResponse> {
    return unwrapAsync(applicantsCreatePublicApplicant(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Record
   */
  async getPublicApplicant(
    request: operations.GetPublicApplicantRequest,
    options?: RequestOptions,
  ): Promise<operations.GetPublicApplicantResponse> {
    return unwrapAsync(applicantsGetPublicApplicant(
      this,
      request,
      options,
    ));
  }

  /**
   * Update Record
   */
  async updatePublicApplicant(
    request: operations.UpdatePublicApplicantRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdatePublicApplicantResponse> {
    return unwrapAsync(applicantsUpdatePublicApplicant(
      this,
      request,
      options,
    ));
  }

  /**
   * Archive Record
   */
  async archivePublicApplicant(
    request: operations.ArchivePublicApplicantRequest,
    options?: RequestOptions,
  ): Promise<operations.ArchivePublicApplicantResponse> {
    return unwrapAsync(applicantsArchivePublicApplicant(
      this,
      request,
      options,
    ));
  }

  /**
   * Activate Record
   */
  async activatePublicApplicant(
    request: operations.ActivatePublicApplicantRequest,
    options?: RequestOptions,
  ): Promise<operations.ActivatePublicApplicantResponse> {
    return unwrapAsync(applicantsActivatePublicApplicant(
      this,
      request,
      options,
    ));
  }
}
