/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { associationsCreatePublicAssociationApiV2PublicAssociationsPost } from "../funcs/associations-create-public-association-api-v2-public-associations-post.js";
import { associationsDeletePublicAssociationApiV2PublicAssociationsDelete } from "../funcs/associations-delete-public-association-api-v2-public-associations-delete.js";
import { associationsListPublicAssociationsApiV2PublicAssociationsGet } from "../funcs/associations-list-public-associations-api-v2-public-associations-get.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Associations extends ClientSDK {
  /**
   * List Public Associations
   */
  async listPublicAssociationsApiV2PublicAssociationsGet(
    request: operations.ListPublicAssociationsApiV2PublicAssociationsGetRequest,
    options?: RequestOptions,
  ): Promise<
    operations.ListPublicAssociationsApiV2PublicAssociationsGetResponse
  > {
    return unwrapAsync(
      associationsListPublicAssociationsApiV2PublicAssociationsGet(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Create Public Association
   */
  async createPublicAssociationApiV2PublicAssociationsPost(
    request:
      operations.CreatePublicAssociationApiV2PublicAssociationsPostRequest,
    options?: RequestOptions,
  ): Promise<
    operations.CreatePublicAssociationApiV2PublicAssociationsPostResponse
  > {
    return unwrapAsync(
      associationsCreatePublicAssociationApiV2PublicAssociationsPost(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Delete Public Association
   */
  async deletePublicAssociationApiV2PublicAssociationsDelete(
    request:
      operations.DeletePublicAssociationApiV2PublicAssociationsDeleteRequest,
    options?: RequestOptions,
  ): Promise<
    operations.DeletePublicAssociationApiV2PublicAssociationsDeleteResponse
  > {
    return unwrapAsync(
      associationsDeletePublicAssociationApiV2PublicAssociationsDelete(
        this,
        request,
        options,
      ),
    );
  }
}
