/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { attendanceRecordsCreatePublicAttendanceRecordApiV2PublicAttendanceRecordsPost } from "../funcs/attendance-records-create-public-attendance-record-api-v2-public-attendance-records-post.js";
import {
  attendanceRecordsDeletePublicAttendanceRecordApiV2PublicAttendanceRecordsAttendanceRecordIdDelete,
} from "../funcs/attendance-records-delete-public-attendance-record-api-v2-public-attendance-records-attendance-record-id-delete.js";
import {
  attendanceRecordsGetPublicAttendanceRecordApiV2PublicAttendanceRecordsAttendanceRecordIdGet,
} from "../funcs/attendance-records-get-public-attendance-record-api-v2-public-attendance-records-attendance-record-id-get.js";
import { attendanceRecordsListPublicAttendanceRecordsApiV2PublicAttendanceRecordsGet } from "../funcs/attendance-records-list-public-attendance-records-api-v2-public-attendance-records-get.js";
import {
  attendanceRecordsUpdatePublicAttendanceRecordApiV2PublicAttendanceRecordsAttendanceRecordIdPut,
} from "../funcs/attendance-records-update-public-attendance-record-api-v2-public-attendance-records-attendance-record-id-put.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class AttendanceRecords extends ClientSDK {
  /**
   * List Public Attendance Records
   */
  async listPublicAttendanceRecordsApiV2PublicAttendanceRecordsGet(
    request?:
      | operations.ListPublicAttendanceRecordsApiV2PublicAttendanceRecordsGetRequest
      | undefined,
    options?: RequestOptions,
  ): Promise<
    operations.ListPublicAttendanceRecordsApiV2PublicAttendanceRecordsGetResponse
  > {
    return unwrapAsync(
      attendanceRecordsListPublicAttendanceRecordsApiV2PublicAttendanceRecordsGet(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Create Public Attendance Record
   */
  async createPublicAttendanceRecordApiV2PublicAttendanceRecordsPost(
    request:
      operations.CreatePublicAttendanceRecordApiV2PublicAttendanceRecordsPostRequest,
    options?: RequestOptions,
  ): Promise<
    operations.CreatePublicAttendanceRecordApiV2PublicAttendanceRecordsPostResponse
  > {
    return unwrapAsync(
      attendanceRecordsCreatePublicAttendanceRecordApiV2PublicAttendanceRecordsPost(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Get Public Attendance Record
   */
  async getPublicAttendanceRecordApiV2PublicAttendanceRecordsAttendanceRecordIdGet(
    request:
      operations.GetPublicAttendanceRecordApiV2PublicAttendanceRecordsAttendanceRecordIdGetRequest,
    options?: RequestOptions,
  ): Promise<
    operations.GetPublicAttendanceRecordApiV2PublicAttendanceRecordsAttendanceRecordIdGetResponse
  > {
    return unwrapAsync(
      attendanceRecordsGetPublicAttendanceRecordApiV2PublicAttendanceRecordsAttendanceRecordIdGet(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Update Public Attendance Record
   */
  async updatePublicAttendanceRecordApiV2PublicAttendanceRecordsAttendanceRecordIdPut(
    request:
      operations.UpdatePublicAttendanceRecordApiV2PublicAttendanceRecordsAttendanceRecordIdPutRequest,
    options?: RequestOptions,
  ): Promise<
    operations.UpdatePublicAttendanceRecordApiV2PublicAttendanceRecordsAttendanceRecordIdPutResponse
  > {
    return unwrapAsync(
      attendanceRecordsUpdatePublicAttendanceRecordApiV2PublicAttendanceRecordsAttendanceRecordIdPut(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Delete Public Attendance Record
   */
  async deletePublicAttendanceRecordApiV2PublicAttendanceRecordsAttendanceRecordIdDelete(
    request:
      operations.DeletePublicAttendanceRecordApiV2PublicAttendanceRecordsAttendanceRecordIdDeleteRequest,
    options?: RequestOptions,
  ): Promise<
    operations.DeletePublicAttendanceRecordApiV2PublicAttendanceRecordsAttendanceRecordIdDeleteResponse
  > {
    return unwrapAsync(
      attendanceRecordsDeletePublicAttendanceRecordApiV2PublicAttendanceRecordsAttendanceRecordIdDelete(
        this,
        request,
        options,
      ),
    );
  }
}
