/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { billsCreate } from "../funcs/bills-create.js";
import { billsDelete } from "../funcs/bills-delete.js";
import { billsGet } from "../funcs/bills-get.js";
import { billsList } from "../funcs/bills-list.js";
import { billsUpdate } from "../funcs/bills-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Bills extends ClientSDK {
  /**
   * List Bills
   */
  async list(
    request?:
      | operations.ApiRoutersV1BillsPublicApiListWorkspaceBillsRequest
      | undefined,
    options?: RequestOptions,
  ): Promise<Array<models.BillSchema>> {
    return unwrapAsync(billsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Bill
   */
  async create(
    request: models.PublicBillRequest,
    options?: RequestOptions,
  ): Promise<models.PublicBillResponse> {
    return unwrapAsync(billsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Bill
   */
  async get(
    request: operations.ApiRoutersV1BillsPublicApiGetPublicBillRequest,
    options?: RequestOptions,
  ): Promise<models.BillSchema> {
    return unwrapAsync(billsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update Bill
   */
  async update(
    request: operations.ApiRoutersV1BillsPublicApiUpdatePublicBillRequest,
    options?: RequestOptions,
  ): Promise<models.PublicBillResponse> {
    return unwrapAsync(billsUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete Bill
   */
  async delete(
    request: operations.ApiRoutersV1BillsPublicApiDeletePublicBillRequest,
    options?: RequestOptions,
  ): Promise<models.PublicBillResponse> {
    return unwrapAsync(billsDelete(
      this,
      request,
      options,
    ));
  }
}
