/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { contactsCreate } from "../funcs/contacts-create.js";
import { contactsDelete } from "../funcs/contacts-delete.js";
import { contactsGet } from "../funcs/contacts-get.js";
import { contactsList } from "../funcs/contacts-list.js";
import { contactsUpdate } from "../funcs/contacts-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Contacts extends ClientSDK {
  /**
   * List Contacts
   */
  async list(
    request?:
      | operations.ApiRoutersV1ContactsPublicApiPublicListContactsRequest
      | undefined,
    options?: RequestOptions,
  ): Promise<models.ContactsListResponse> {
    return unwrapAsync(contactsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Contact
   */
  async create(
    request: models.PublicContactRequest,
    options?: RequestOptions,
  ): Promise<models.PublicContactResponse> {
    return unwrapAsync(contactsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Contact
   */
  async get(
    request: operations.ApiRoutersV1ContactsPublicApiGetPublicContactRequest,
    options?: RequestOptions,
  ): Promise<models.ContactSchema> {
    return unwrapAsync(contactsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update Contact
   */
  async update(
    request: operations.ApiRoutersV1ContactsPublicApiUpdatePublicContactRequest,
    options?: RequestOptions,
  ): Promise<models.PublicContactResponse> {
    return unwrapAsync(contactsUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete Contact
   */
  async delete(
    request: operations.ApiRoutersV1ContactsPublicApiDeletePublicContactRequest,
    options?: RequestOptions,
  ): Promise<models.PublicContactResponse> {
    return unwrapAsync(contactsDelete(
      this,
      request,
      options,
    ));
  }
}
