/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customObjectsActivateRecord } from "../funcs/custom-objects-activate-record.js";
import {
  customObjectsArchivePublicCustomObjectRecordCompatibilityApiV2PublicRecordsCustomObjectsRecordsRecordIdArchivePost,
} from "../funcs/custom-objects-archive-public-custom-object-record-compatibility-api-v2-public-records-custom-objects-records-record-id-archive-post.js";
import { customObjectsArchiveRecord } from "../funcs/custom-objects-archive-record.js";
import {
  customObjectsCreatePublicCustomObjectRecordCompatibilityApiV2PublicRecordsCustomObjectsRecordsPost,
} from "../funcs/custom-objects-create-public-custom-object-record-compatibility-api-v2-public-records-custom-objects-records-post.js";
import { customObjectsCreateRecord } from "../funcs/custom-objects-create-record.js";
import { customObjectsDeleteRecord } from "../funcs/custom-objects-delete-record.js";
import { customObjectsGetRecord } from "../funcs/custom-objects-get-record.js";
import { customObjectsListRecords } from "../funcs/custom-objects-list-records.js";
import {
  customObjectsUpdatePublicCustomObjectRecordCompatibilityApiV2PublicRecordsCustomObjectsRecordsRecordIdPost,
} from "../funcs/custom-objects-update-public-custom-object-record-compatibility-api-v2-public-records-custom-objects-records-record-id-post.js";
import { customObjectsUpdateRecord } from "../funcs/custom-objects-update-record.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class CustomObjects extends ClientSDK {
  /**
   * List Custom Object Records
   */
  async listRecords(
    request:
      operations.ListPublicCustomObjectRecordsApiV2PublicCustomObjectsCustomObjectIdRecordsGetRequest,
    options?: RequestOptions,
  ): Promise<
    operations.ListPublicCustomObjectRecordsApiV2PublicCustomObjectsCustomObjectIdRecordsGetResponse
  > {
    return unwrapAsync(customObjectsListRecords(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Custom Object Record
   */
  async createRecord(
    request:
      operations.CreatePublicCustomObjectRecordApiV2PublicCustomObjectsCustomObjectIdRecordsPostRequest,
    options?: RequestOptions,
  ): Promise<
    operations.CreatePublicCustomObjectRecordApiV2PublicCustomObjectsCustomObjectIdRecordsPostResponse
  > {
    return unwrapAsync(customObjectsCreateRecord(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Custom Object Record
   */
  async getRecord(
    request:
      operations.GetPublicCustomObjectRecordApiV2PublicCustomObjectsCustomObjectIdRecordsRecordIdGetRequest,
    options?: RequestOptions,
  ): Promise<
    operations.GetPublicCustomObjectRecordApiV2PublicCustomObjectsCustomObjectIdRecordsRecordIdGetResponse
  > {
    return unwrapAsync(customObjectsGetRecord(
      this,
      request,
      options,
    ));
  }

  /**
   * Update Custom Object Record
   */
  async updateRecord(
    request:
      operations.UpdatePublicCustomObjectRecordApiV2PublicCustomObjectsCustomObjectIdRecordsRecordIdPutRequest,
    options?: RequestOptions,
  ): Promise<
    operations.UpdatePublicCustomObjectRecordApiV2PublicCustomObjectsCustomObjectIdRecordsRecordIdPutResponse
  > {
    return unwrapAsync(customObjectsUpdateRecord(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete Custom Object Record
   */
  async deleteRecord(
    request:
      operations.DeletePublicCustomObjectRecordApiV2PublicCustomObjectsCustomObjectIdRecordsRecordIdDeleteRequest,
    options?: RequestOptions,
  ): Promise<
    operations.DeletePublicCustomObjectRecordApiV2PublicCustomObjectsCustomObjectIdRecordsRecordIdDeleteResponse
  > {
    return unwrapAsync(customObjectsDeleteRecord(
      this,
      request,
      options,
    ));
  }

  /**
   * Archive Custom Object Record
   */
  async archiveRecord(
    request:
      operations.ArchivePublicCustomObjectRecordApiV2PublicCustomObjectsCustomObjectIdRecordsRecordIdArchivePostRequest,
    options?: RequestOptions,
  ): Promise<
    operations.ArchivePublicCustomObjectRecordApiV2PublicCustomObjectsCustomObjectIdRecordsRecordIdArchivePostResponse
  > {
    return unwrapAsync(customObjectsArchiveRecord(
      this,
      request,
      options,
    ));
  }

  /**
   * Activate Custom Object Record
   */
  async activateRecord(
    request:
      operations.ActivatePublicCustomObjectRecordApiV2PublicCustomObjectsCustomObjectIdRecordsRecordIdActivatePostRequest,
    options?: RequestOptions,
  ): Promise<
    operations.ActivatePublicCustomObjectRecordApiV2PublicCustomObjectsCustomObjectIdRecordsRecordIdActivatePostResponse
  > {
    return unwrapAsync(customObjectsActivateRecord(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Public Custom Object Record Compatibility
   */
  async createPublicCustomObjectRecordCompatibilityApiV2PublicRecordsCustomObjectsRecordsPost(
    request:
      operations.CreatePublicCustomObjectRecordCompatibilityApiV2PublicRecordsCustomObjectsRecordsPostRequest,
    options?: RequestOptions,
  ): Promise<
    operations.CreatePublicCustomObjectRecordCompatibilityApiV2PublicRecordsCustomObjectsRecordsPostResponse
  > {
    return unwrapAsync(
      customObjectsCreatePublicCustomObjectRecordCompatibilityApiV2PublicRecordsCustomObjectsRecordsPost(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Update Public Custom Object Record Compatibility
   */
  async updatePublicCustomObjectRecordCompatibilityApiV2PublicRecordsCustomObjectsRecordsRecordIdPost(
    request:
      operations.UpdatePublicCustomObjectRecordCompatibilityApiV2PublicRecordsCustomObjectsRecordsRecordIdPostRequest,
    options?: RequestOptions,
  ): Promise<
    operations.UpdatePublicCustomObjectRecordCompatibilityApiV2PublicRecordsCustomObjectsRecordsRecordIdPostResponse
  > {
    return unwrapAsync(
      customObjectsUpdatePublicCustomObjectRecordCompatibilityApiV2PublicRecordsCustomObjectsRecordsRecordIdPost(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Archive Public Custom Object Record Compatibility
   */
  async archivePublicCustomObjectRecordCompatibilityApiV2PublicRecordsCustomObjectsRecordsRecordIdArchivePost(
    request:
      operations.ArchivePublicCustomObjectRecordCompatibilityApiV2PublicRecordsCustomObjectsRecordsRecordIdArchivePostRequest,
    options?: RequestOptions,
  ): Promise<
    operations.ArchivePublicCustomObjectRecordCompatibilityApiV2PublicRecordsCustomObjectsRecordsRecordIdArchivePostResponse
  > {
    return unwrapAsync(
      customObjectsArchivePublicCustomObjectRecordCompatibilityApiV2PublicRecordsCustomObjectsRecordsRecordIdArchivePost(
        this,
        request,
        options,
      ),
    );
  }
}
