/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { dealsCreatePipeline } from "../funcs/deals-create-pipeline.js";
import { dealsCreate } from "../funcs/deals-create.js";
import { dealsDelete } from "../funcs/deals-delete.js";
import { dealsGet } from "../funcs/deals-get.js";
import { dealsListPipelines } from "../funcs/deals-list-pipelines.js";
import { dealsList } from "../funcs/deals-list.js";
import { dealsUpdatePipeline } from "../funcs/deals-update-pipeline.js";
import { dealsUpdate } from "../funcs/deals-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Deals extends ClientSDK {
  /**
   * List Public Deals
   */
  async list(
    request?: operations.ListPublicDealsApiV2PublicDealsGetRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListPublicDealsApiV2PublicDealsGetResponse> {
    return unwrapAsync(dealsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Public Deal
   */
  async create(
    request: operations.CreatePublicDealApiV2PublicDealsPostRequest,
    options?: RequestOptions,
  ): Promise<operations.CreatePublicDealApiV2PublicDealsPostResponse> {
    return unwrapAsync(dealsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * List Public Deal Pipelines
   */
  async listPipelines(
    request?:
      | operations.ListPublicDealPipelinesApiV2PublicDealsPipelinesGetRequest
      | undefined,
    options?: RequestOptions,
  ): Promise<
    operations.ListPublicDealPipelinesApiV2PublicDealsPipelinesGetResponse
  > {
    return unwrapAsync(dealsListPipelines(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Public Deal Pipeline
   */
  async createPipeline(
    request:
      operations.CreatePublicDealPipelineApiV2PublicDealsPipelinesPostRequest,
    options?: RequestOptions,
  ): Promise<
    operations.CreatePublicDealPipelineApiV2PublicDealsPipelinesPostResponse
  > {
    return unwrapAsync(dealsCreatePipeline(
      this,
      request,
      options,
    ));
  }

  /**
   * Update Public Deal Pipeline
   */
  async updatePipeline(
    request:
      operations.UpdatePublicDealPipelineApiV2PublicDealsPipelinesPipelineIdPatchRequest,
    options?: RequestOptions,
  ): Promise<
    operations.UpdatePublicDealPipelineApiV2PublicDealsPipelinesPipelineIdPatchResponse
  > {
    return unwrapAsync(dealsUpdatePipeline(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Public Deal
   */
  async get(
    request: operations.GetPublicDealApiV2PublicDealsDealIdGetRequest,
    options?: RequestOptions,
  ): Promise<operations.GetPublicDealApiV2PublicDealsDealIdGetResponse> {
    return unwrapAsync(dealsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update Public Deal
   */
  async update(
    request: operations.UpdatePublicDealApiV2PublicDealsDealIdPutRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdatePublicDealApiV2PublicDealsDealIdPutResponse> {
    return unwrapAsync(dealsUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete Public Deal
   */
  async delete(
    request: operations.DeletePublicDealApiV2PublicDealsDealIdDeleteRequest,
    options?: RequestOptions,
  ): Promise<operations.DeletePublicDealApiV2PublicDealsDealIdDeleteResponse> {
    return unwrapAsync(dealsDelete(
      this,
      request,
      options,
    ));
  }
}
