/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { exportsCancelPublicExportJobCompatApiV2PublicExportsJobIdCancelPost } from "../funcs/exports-cancel-public-export-job-compat-api-v2-public-exports-job-id-cancel-post.js";
import { exportsCreatePublicExportJobCompatApiV2PublicExportsPost } from "../funcs/exports-create-public-export-job-compat-api-v2-public-exports-post.js";
import { exportsGetPublicExportJobCompatApiV2PublicExportsJobIdGet } from "../funcs/exports-get-public-export-job-compat-api-v2-public-exports-job-id-get.js";
import { exportsListPublicExportJobsCompatApiV2PublicExportsGet } from "../funcs/exports-list-public-export-jobs-compat-api-v2-public-exports-get.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Exports extends ClientSDK {
  /**
   * List Public Export Jobs Compat
   */
  async listPublicExportJobsCompatApiV2PublicExportsGet(
    request?:
      | operations.ListPublicExportJobsCompatApiV2PublicExportsGetRequest
      | undefined,
    options?: RequestOptions,
  ): Promise<
    operations.ListPublicExportJobsCompatApiV2PublicExportsGetResponse
  > {
    return unwrapAsync(exportsListPublicExportJobsCompatApiV2PublicExportsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Public Export Job Compat
   *
   * @remarks
   * Create an export job.
   *
   * Integration-destination exports are validated against the runnable
   * delivery matrix. HubSpot Company, Contact, Custom Object, Deal, Invoice,
   * Item, Order, Subscription, and Ticket exports use the dedicated Hatchet
   * bulk workflow, bounded CSV chunks, and HubSpot's Imports API. Invoice
   * requires an explicitly selected HubSpot custom-object type id. NextEngine
   * Item and Order exports keep their dedicated Hatchet pipelines. Provider and
   * object pairs without a working delivery pipeline are rejected with HTTP
   * 400 and error code ``INTEGRATION_EXPORT_NOT_SUPPORTED`` before any job
   * history row is created. Empty or unknown provider slugs are rejected with
   * ``INTEGRATION_EXPORT_UNKNOWN_PROVIDER``. Accepted jobs stay queued or
   * running until provider completion and required post-processing finish.
   */
  async createPublicExportJobCompatApiV2PublicExportsPost(
    request:
      operations.CreatePublicExportJobCompatApiV2PublicExportsPostRequest,
    options?: RequestOptions,
  ): Promise<
    operations.CreatePublicExportJobCompatApiV2PublicExportsPostResponse
  > {
    return unwrapAsync(exportsCreatePublicExportJobCompatApiV2PublicExportsPost(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Public Export Job Compat
   */
  async getPublicExportJobCompatApiV2PublicExportsJobIdGet(
    request:
      operations.GetPublicExportJobCompatApiV2PublicExportsJobIdGetRequest,
    options?: RequestOptions,
  ): Promise<
    operations.GetPublicExportJobCompatApiV2PublicExportsJobIdGetResponse
  > {
    return unwrapAsync(
      exportsGetPublicExportJobCompatApiV2PublicExportsJobIdGet(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Cancel Public Export Job Compat
   */
  async cancelPublicExportJobCompatApiV2PublicExportsJobIdCancelPost(
    request:
      operations.CancelPublicExportJobCompatApiV2PublicExportsJobIdCancelPostRequest,
    options?: RequestOptions,
  ): Promise<
    operations.CancelPublicExportJobCompatApiV2PublicExportsJobIdCancelPostResponse
  > {
    return unwrapAsync(
      exportsCancelPublicExportJobCompatApiV2PublicExportsJobIdCancelPost(
        this,
        request,
        options,
      ),
    );
  }
}
