/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { journalsActivate } from "../funcs/journals-activate.js";
import { journalsArchive } from "../funcs/journals-archive.js";
import { journalsCreatePublicFinancialStatementViewApiV2PublicJournalsViewsPost } from "../funcs/journals-create-public-financial-statement-view-api-v2-public-journals-views-post.js";
import { journalsCreatePublicJournalApiV2PublicJournalsPost } from "../funcs/journals-create-public-journal-api-v2-public-journals-post.js";
import { journalsDelete } from "../funcs/journals-delete.js";
import { journalsGet } from "../funcs/journals-get.js";
import { journalsListPublicJournalsApiV2PublicJournalsGet } from "../funcs/journals-list-public-journals-api-v2-public-journals-get.js";
import { journalsUpdate } from "../funcs/journals-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Journals extends ClientSDK {
  /**
   * List Journal Entries
   */
  async listPublicJournalsApiV2PublicJournalsGet(
    request?:
      | operations.ListPublicJournalsApiV2PublicJournalsGetRequest
      | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListPublicJournalsApiV2PublicJournalsGetResponse> {
    return unwrapAsync(journalsListPublicJournalsApiV2PublicJournalsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Journal Entry
   */
  async createPublicJournalApiV2PublicJournalsPost(
    request: operations.CreatePublicJournalApiV2PublicJournalsPostRequest,
    options?: RequestOptions,
  ): Promise<operations.CreatePublicJournalApiV2PublicJournalsPostResponse> {
    return unwrapAsync(journalsCreatePublicJournalApiV2PublicJournalsPost(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Financial Statement View
   */
  async createPublicFinancialStatementViewApiV2PublicJournalsViewsPost(
    request:
      operations.CreatePublicFinancialStatementViewApiV2PublicJournalsViewsPostRequest,
    options?: RequestOptions,
  ): Promise<
    operations.CreatePublicFinancialStatementViewApiV2PublicJournalsViewsPostResponse
  > {
    return unwrapAsync(
      journalsCreatePublicFinancialStatementViewApiV2PublicJournalsViewsPost(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Get Journal Entry
   */
  async get(
    request: operations.GetPublicJournalApiV2PublicJournalsJournalIdGetRequest,
    options?: RequestOptions,
  ): Promise<
    operations.GetPublicJournalApiV2PublicJournalsJournalIdGetResponse
  > {
    return unwrapAsync(journalsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update Journal Entry
   */
  async update(
    request:
      operations.UpdatePublicJournalApiV2PublicJournalsJournalIdPutRequest,
    options?: RequestOptions,
  ): Promise<
    operations.UpdatePublicJournalApiV2PublicJournalsJournalIdPutResponse
  > {
    return unwrapAsync(journalsUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete Journal Entry
   */
  async delete(
    request:
      operations.DeletePublicJournalApiV2PublicJournalsJournalIdDeleteRequest,
    options?: RequestOptions,
  ): Promise<
    operations.DeletePublicJournalApiV2PublicJournalsJournalIdDeleteResponse
  > {
    return unwrapAsync(journalsDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Archive Journal Entry
   */
  async archive(
    request:
      operations.ArchivePublicJournalApiV2PublicJournalsJournalIdArchivePostRequest,
    options?: RequestOptions,
  ): Promise<
    operations.ArchivePublicJournalApiV2PublicJournalsJournalIdArchivePostResponse
  > {
    return unwrapAsync(journalsArchive(
      this,
      request,
      options,
    ));
  }

  /**
   * Activate Journal Entry
   */
  async activate(
    request:
      operations.ActivatePublicJournalApiV2PublicJournalsJournalIdActivatePostRequest,
    options?: RequestOptions,
  ): Promise<
    operations.ActivatePublicJournalApiV2PublicJournalsJournalIdActivatePostResponse
  > {
    return unwrapAsync(journalsActivate(
      this,
      request,
      options,
    ));
  }
}
