/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { locationsCreate } from "../funcs/locations-create.js";
import { locationsDelete } from "../funcs/locations-delete.js";
import { locationsGet } from "../funcs/locations-get.js";
import { locationsList } from "../funcs/locations-list.js";
import { locationsUpdate } from "../funcs/locations-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Locations extends ClientSDK {
  /**
   * List Public Locations
   */
  async list(
    request?:
      | operations.ListPublicLocationsApiV2PublicLocationsGetRequest
      | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListPublicLocationsApiV2PublicLocationsGetResponse> {
    return unwrapAsync(locationsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Public Location
   */
  async create(
    request: operations.CreatePublicLocationApiV2PublicLocationsPostRequest,
    options?: RequestOptions,
  ): Promise<operations.CreatePublicLocationApiV2PublicLocationsPostResponse> {
    return unwrapAsync(locationsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Public Location
   */
  async get(
    request:
      operations.GetPublicLocationApiV2PublicLocationsLocationIdGetRequest,
    options?: RequestOptions,
  ): Promise<
    operations.GetPublicLocationApiV2PublicLocationsLocationIdGetResponse
  > {
    return unwrapAsync(locationsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update Public Location
   */
  async update(
    request:
      operations.UpdatePublicLocationApiV2PublicLocationsLocationIdPutRequest,
    options?: RequestOptions,
  ): Promise<
    operations.UpdatePublicLocationApiV2PublicLocationsLocationIdPutResponse
  > {
    return unwrapAsync(locationsUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete Public Location
   */
  async delete(
    request:
      operations.DeletePublicLocationApiV2PublicLocationsLocationIdDeleteRequest,
    options?: RequestOptions,
  ): Promise<
    operations.DeletePublicLocationApiV2PublicLocationsLocationIdDeleteResponse
  > {
    return unwrapAsync(locationsDelete(
      this,
      request,
      options,
    ));
  }
}
