/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ordersBulkCreate } from "../funcs/orders-bulk-create.js";
import { ordersCreate } from "../funcs/orders-create.js";
import { ordersDelete } from "../funcs/orders-delete.js";
import { ordersGet } from "../funcs/orders-get.js";
import { ordersList } from "../funcs/orders-list.js";
import { ordersUpdate } from "../funcs/orders-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Orders extends ClientSDK {
  /**
   * List Orders
   */
  async list(
    request?:
      | operations.ApiRoutersV1OrdersPublicApiPublicListOrdersRequest
      | undefined,
    options?: RequestOptions,
  ): Promise<models.OrdersListResponse> {
    return unwrapAsync(ordersList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Orders
   */
  async create(
    request: models.PublicOrderRequest,
    options?: RequestOptions,
  ): Promise<models.BulkOrdersResponse> {
    return unwrapAsync(ordersCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Bulk Create Orders
   */
  async bulkCreate(
    request: models.BulkOrdersRequest,
    options?: RequestOptions,
  ): Promise<models.BulkOrdersResponse> {
    return unwrapAsync(ordersBulkCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Order
   */
  async get(
    request: operations.ApiRoutersV1OrdersPublicApiPublicGetOrderRequest,
    options?: RequestOptions,
  ): Promise<models.PublicOrderDetailSchema> {
    return unwrapAsync(ordersGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update Order
   */
  async update(
    request: operations.ApiRoutersV1OrdersPublicApiPublicUpdateOrderRequest,
    options?: RequestOptions,
  ): Promise<models.BulkOrdersResponse> {
    return unwrapAsync(ordersUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete Order
   */
  async delete(
    request: operations.ApiRoutersV1OrdersPublicApiPublicDeleteOrderRequest,
    options?: RequestOptions,
  ): Promise<models.PublicOrderDeleteResponse> {
    return unwrapAsync(ordersDelete(
      this,
      request,
      options,
    ));
  }
}
