/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { projectsCreatePublicProjectApiV2PublicProjectsPost } from "../funcs/projects-create-public-project-api-v2-public-projects-post.js";
import { projectsDeletePublicProjectApiV2PublicProjectsProjectIdDelete } from "../funcs/projects-delete-public-project-api-v2-public-projects-project-id-delete.js";
import { projectsGetPublicProjectApiV2PublicProjectsProjectIdGet } from "../funcs/projects-get-public-project-api-v2-public-projects-project-id-get.js";
import { projectsListPublicProjectsApiV2PublicProjectsGet } from "../funcs/projects-list-public-projects-api-v2-public-projects-get.js";
import { projectsUpdatePublicProjectApiV2PublicProjectsProjectIdPut } from "../funcs/projects-update-public-project-api-v2-public-projects-project-id-put.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Projects extends ClientSDK {
  /**
   * List Public Projects
   */
  async listPublicProjectsApiV2PublicProjectsGet(
    request?:
      | operations.ListPublicProjectsApiV2PublicProjectsGetRequest
      | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListPublicProjectsApiV2PublicProjectsGetResponse> {
    return unwrapAsync(projectsListPublicProjectsApiV2PublicProjectsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Public Project
   */
  async createPublicProjectApiV2PublicProjectsPost(
    request: operations.CreatePublicProjectApiV2PublicProjectsPostRequest,
    options?: RequestOptions,
  ): Promise<operations.CreatePublicProjectApiV2PublicProjectsPostResponse> {
    return unwrapAsync(projectsCreatePublicProjectApiV2PublicProjectsPost(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Public Project
   */
  async getPublicProjectApiV2PublicProjectsProjectIdGet(
    request: operations.GetPublicProjectApiV2PublicProjectsProjectIdGetRequest,
    options?: RequestOptions,
  ): Promise<
    operations.GetPublicProjectApiV2PublicProjectsProjectIdGetResponse
  > {
    return unwrapAsync(projectsGetPublicProjectApiV2PublicProjectsProjectIdGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update Public Project
   */
  async updatePublicProjectApiV2PublicProjectsProjectIdPut(
    request:
      operations.UpdatePublicProjectApiV2PublicProjectsProjectIdPutRequest,
    options?: RequestOptions,
  ): Promise<
    operations.UpdatePublicProjectApiV2PublicProjectsProjectIdPutResponse
  > {
    return unwrapAsync(
      projectsUpdatePublicProjectApiV2PublicProjectsProjectIdPut(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Delete Public Project
   */
  async deletePublicProjectApiV2PublicProjectsProjectIdDelete(
    request:
      operations.DeletePublicProjectApiV2PublicProjectsProjectIdDeleteRequest,
    options?: RequestOptions,
  ): Promise<
    operations.DeletePublicProjectApiV2PublicProjectsProjectIdDeleteResponse
  > {
    return unwrapAsync(
      projectsDeletePublicProjectApiV2PublicProjectsProjectIdDelete(
        this,
        request,
        options,
      ),
    );
  }
}
