/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { projectsCreate } from "../funcs/projects-create.js";
import { projectsDelete } from "../funcs/projects-delete.js";
import { projectsGet } from "../funcs/projects-get.js";
import { projectsList } from "../funcs/projects-list.js";
import { projectsUpdate } from "../funcs/projects-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Projects extends ClientSDK {
  /**
   * List Public Projects
   */
  async list(
    request?:
      | operations.ListPublicProjectsApiV2PublicProjectsGetRequest
      | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListPublicProjectsApiV2PublicProjectsGetResponse> {
    return unwrapAsync(projectsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Public Project
   */
  async create(
    request: operations.CreatePublicProjectApiV2PublicProjectsPostRequest,
    options?: RequestOptions,
  ): Promise<operations.CreatePublicProjectApiV2PublicProjectsPostResponse> {
    return unwrapAsync(projectsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Public Project
   */
  async get(
    request: operations.GetPublicProjectApiV2PublicProjectsProjectIdGetRequest,
    options?: RequestOptions,
  ): Promise<
    operations.GetPublicProjectApiV2PublicProjectsProjectIdGetResponse
  > {
    return unwrapAsync(projectsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update Public Project
   */
  async update(
    request:
      operations.UpdatePublicProjectApiV2PublicProjectsProjectIdPutRequest,
    options?: RequestOptions,
  ): Promise<
    operations.UpdatePublicProjectApiV2PublicProjectsProjectIdPutResponse
  > {
    return unwrapAsync(projectsUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete Public Project
   */
  async delete(
    request:
      operations.DeletePublicProjectApiV2PublicProjectsProjectIdDeleteRequest,
    options?: RequestOptions,
  ): Promise<
    operations.DeletePublicProjectApiV2PublicProjectsProjectIdDeleteResponse
  > {
    return unwrapAsync(projectsDelete(
      this,
      request,
      options,
    ));
  }
}
