/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { reportsCreate } from "../funcs/reports-create.js";
import { reportsDelete } from "../funcs/reports-delete.js";
import { reportsGet } from "../funcs/reports-get.js";
import { reportsList } from "../funcs/reports-list.js";
import { reportsUpdate } from "../funcs/reports-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Reports extends ClientSDK {
  /**
   * List Public Reports
   */
  async list(
    request?:
      | operations.ListPublicReportsApiV2PublicReportsGetRequest
      | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListPublicReportsApiV2PublicReportsGetResponse> {
    return unwrapAsync(reportsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Public Report
   */
  async create(
    request: operations.CreatePublicReportApiV2PublicReportsPostRequest,
    options?: RequestOptions,
  ): Promise<operations.CreatePublicReportApiV2PublicReportsPostResponse> {
    return unwrapAsync(reportsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Public Report
   */
  async get(
    request: operations.GetPublicReportApiV2PublicReportsReportIdGetRequest,
    options?: RequestOptions,
  ): Promise<operations.GetPublicReportApiV2PublicReportsReportIdGetResponse> {
    return unwrapAsync(reportsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update Public Report
   */
  async update(
    request: operations.UpdatePublicReportApiV2PublicReportsReportIdPutRequest,
    options?: RequestOptions,
  ): Promise<
    operations.UpdatePublicReportApiV2PublicReportsReportIdPutResponse
  > {
    return unwrapAsync(reportsUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete Public Report
   */
  async delete(
    request:
      operations.DeletePublicReportApiV2PublicReportsReportIdDeleteRequest,
    options?: RequestOptions,
  ): Promise<
    operations.DeletePublicReportApiV2PublicReportsReportIdDeleteResponse
  > {
    return unwrapAsync(reportsDelete(
      this,
      request,
      options,
    ));
  }
}
