/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sankaBuyListPublicBuyOffersApiV2PublicBuyOffersGet } from "../funcs/sanka-buy-list-public-buy-offers-api-v2-public-buy-offers-get.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class SankaBuy extends ClientSDK {
  /**
   * List Public Buy Offers
   */
  async listPublicBuyOffersApiV2PublicBuyOffersGet(
    request?:
      | operations.ListPublicBuyOffersApiV2PublicBuyOffersGetRequest
      | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListPublicBuyOffersApiV2PublicBuyOffersGetResponse> {
    return unwrapAsync(sankaBuyListPublicBuyOffersApiV2PublicBuyOffersGet(
      this,
      request,
      options,
    ));
  }
}
