/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Ai } from "./ai.js";
import { Bills } from "./bills.js";
import { Calendar } from "./calendar.js";
import { Companies } from "./companies.js";
import { Contacts } from "./contacts.js";
import { Deals } from "./deals.js";
import { Disbursements } from "./disbursements.js";
import { Estimates } from "./estimates.js";
import { Expenses } from "./expenses.js";
import { Inventories } from "./inventories.js";
import { InventoryTransactions } from "./inventory-transactions.js";
import { Invoices } from "./invoices.js";
import { Items } from "./items.js";
import { Locations } from "./locations.js";
import { Meters } from "./meters.js";
import { Orders } from "./orders.js";
import { Payments } from "./payments.js";
import { Properties } from "./properties.js";
import { PublicAuth } from "./public-auth.js";
import { PurchaseOrders } from "./purchase-orders.js";
import { Reports } from "./reports.js";
import { Slips } from "./slips.js";
import { Subscriptions } from "./subscriptions.js";
import { Tickets } from "./tickets.js";
import { Workflows } from "./workflows.js";

export class Sanka extends ClientSDK {
  private _ai?: Ai;
  get ai(): Ai {
    return (this._ai ??= new Ai(this._options));
  }

  private _orders?: Orders;
  get orders(): Orders {
    return (this._orders ??= new Orders(this._options));
  }

  private _items?: Items;
  get items(): Items {
    return (this._items ??= new Items(this._options));
  }

  private _contacts?: Contacts;
  get contacts(): Contacts {
    return (this._contacts ??= new Contacts(this._options));
  }

  private _companies?: Companies;
  get companies(): Companies {
    return (this._companies ??= new Companies(this._options));
  }

  private _deals?: Deals;
  get deals(): Deals {
    return (this._deals ??= new Deals(this._options));
  }

  private _tickets?: Tickets;
  get tickets(): Tickets {
    return (this._tickets ??= new Tickets(this._options));
  }

  private _subscriptions?: Subscriptions;
  get subscriptions(): Subscriptions {
    return (this._subscriptions ??= new Subscriptions(this._options));
  }

  private _estimates?: Estimates;
  get estimates(): Estimates {
    return (this._estimates ??= new Estimates(this._options));
  }

  private _invoices?: Invoices;
  get invoices(): Invoices {
    return (this._invoices ??= new Invoices(this._options));
  }

  private _payments?: Payments;
  get payments(): Payments {
    return (this._payments ??= new Payments(this._options));
  }

  private _expenses?: Expenses;
  get expenses(): Expenses {
    return (this._expenses ??= new Expenses(this._options));
  }

  private _inventories?: Inventories;
  get inventories(): Inventories {
    return (this._inventories ??= new Inventories(this._options));
  }

  private _locations?: Locations;
  get locations(): Locations {
    return (this._locations ??= new Locations(this._options));
  }

  private _inventoryTransactions?: InventoryTransactions;
  get inventoryTransactions(): InventoryTransactions {
    return (this._inventoryTransactions ??= new InventoryTransactions(
      this._options,
    ));
  }

  private _meters?: Meters;
  get meters(): Meters {
    return (this._meters ??= new Meters(this._options));
  }

  private _properties?: Properties;
  get properties(): Properties {
    return (this._properties ??= new Properties(this._options));
  }

  private _purchaseOrders?: PurchaseOrders;
  get purchaseOrders(): PurchaseOrders {
    return (this._purchaseOrders ??= new PurchaseOrders(this._options));
  }

  private _slips?: Slips;
  get slips(): Slips {
    return (this._slips ??= new Slips(this._options));
  }

  private _bills?: Bills;
  get bills(): Bills {
    return (this._bills ??= new Bills(this._options));
  }

  private _disbursements?: Disbursements;
  get disbursements(): Disbursements {
    return (this._disbursements ??= new Disbursements(this._options));
  }

  private _reports?: Reports;
  get reports(): Reports {
    return (this._reports ??= new Reports(this._options));
  }

  private _workflows?: Workflows;
  get workflows(): Workflows {
    return (this._workflows ??= new Workflows(this._options));
  }

  private _calendar?: Calendar;
  get calendar(): Calendar {
    return (this._calendar ??= new Calendar(this._options));
  }

  private _publicAuth?: PublicAuth;
  get publicAuth(): PublicAuth {
    return (this._publicAuth ??= new PublicAuth(this._options));
  }
}
