/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { viewsCreatePublicViewApiV2PublicViewsPost } from "../funcs/views-create-public-view-api-v2-public-views-post.js";
import { viewsDeletePublicViewApiV2PublicViewsViewIdDelete } from "../funcs/views-delete-public-view-api-v2-public-views-view-id-delete.js";
import { viewsGetPublicViewApiV2PublicViewsViewIdGet } from "../funcs/views-get-public-view-api-v2-public-views-view-id-get.js";
import { viewsGetPublicViewColumnsApiV2PublicViewsViewIdColumnsGet } from "../funcs/views-get-public-view-columns-api-v2-public-views-view-id-columns-get.js";
import { viewsListPublicViewsApiV2PublicViewsGet } from "../funcs/views-list-public-views-api-v2-public-views-get.js";
import { viewsUpdatePublicViewApiV2PublicViewsViewIdPatch } from "../funcs/views-update-public-view-api-v2-public-views-view-id-patch.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Views extends ClientSDK {
  /**
   * List Public Views
   */
  async listPublicViewsApiV2PublicViewsGet(
    request?: operations.ListPublicViewsApiV2PublicViewsGetRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListPublicViewsApiV2PublicViewsGetResponse> {
    return unwrapAsync(viewsListPublicViewsApiV2PublicViewsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Public View
   */
  async createPublicViewApiV2PublicViewsPost(
    request: operations.CreatePublicViewApiV2PublicViewsPostRequest,
    options?: RequestOptions,
  ): Promise<operations.CreatePublicViewApiV2PublicViewsPostResponse> {
    return unwrapAsync(viewsCreatePublicViewApiV2PublicViewsPost(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Public View
   */
  async getPublicViewApiV2PublicViewsViewIdGet(
    request: operations.GetPublicViewApiV2PublicViewsViewIdGetRequest,
    options?: RequestOptions,
  ): Promise<operations.GetPublicViewApiV2PublicViewsViewIdGetResponse> {
    return unwrapAsync(viewsGetPublicViewApiV2PublicViewsViewIdGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update Public View
   */
  async updatePublicViewApiV2PublicViewsViewIdPatch(
    request: operations.UpdatePublicViewApiV2PublicViewsViewIdPatchRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdatePublicViewApiV2PublicViewsViewIdPatchResponse> {
    return unwrapAsync(viewsUpdatePublicViewApiV2PublicViewsViewIdPatch(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete Public View
   */
  async deletePublicViewApiV2PublicViewsViewIdDelete(
    request: operations.DeletePublicViewApiV2PublicViewsViewIdDeleteRequest,
    options?: RequestOptions,
  ): Promise<operations.DeletePublicViewApiV2PublicViewsViewIdDeleteResponse> {
    return unwrapAsync(viewsDeletePublicViewApiV2PublicViewsViewIdDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Public View Columns
   *
   * @remarks
   * Return saved view columns as canonical V2 field ids. Legacy raw UUID columns and stale `standard:<uuid>` columns are normalized to `custom_property:<uuid>`, standard aliases are resolved for compatible objects, and labels honor the requested language when localized metadata or compatibility fallbacks are available.
   */
  async getPublicViewColumnsApiV2PublicViewsViewIdColumnsGet(
    request:
      operations.GetPublicViewColumnsApiV2PublicViewsViewIdColumnsGetRequest,
    options?: RequestOptions,
  ): Promise<
    operations.GetPublicViewColumnsApiV2PublicViewsViewIdColumnsGetResponse
  > {
    return unwrapAsync(
      viewsGetPublicViewColumnsApiV2PublicViewsViewIdColumnsGet(
        this,
        request,
        options,
      ),
    );
  }
}
