/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { workforcePlanningCreatePublicWorkforcePosition } from "../funcs/workforce-planning-create-public-workforce-position.js";
import { workforcePlanningGetPublicWorkforceOrganization } from "../funcs/workforce-planning-get-public-workforce-organization.js";
import { workforcePlanningSetPublicWorkforcePositionJob } from "../funcs/workforce-planning-set-public-workforce-position-job.js";
import { workforcePlanningSetPublicWorkforcePositionOccupant } from "../funcs/workforce-planning-set-public-workforce-position-occupant.js";
import { workforcePlanningUpdatePublicWorkforcePosition } from "../funcs/workforce-planning-update-public-workforce-position.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class WorkforcePlanning extends ClientSDK {
  /**
   * Get Public Workforce Organization
   */
  async getPublicWorkforceOrganization(
    request?: operations.GetPublicWorkforceOrganizationRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetPublicWorkforceOrganizationResponse> {
    return unwrapAsync(workforcePlanningGetPublicWorkforceOrganization(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Public Workforce Position
   */
  async createPublicWorkforcePosition(
    request: operations.CreatePublicWorkforcePositionRequest,
    options?: RequestOptions,
  ): Promise<operations.CreatePublicWorkforcePositionResponse> {
    return unwrapAsync(workforcePlanningCreatePublicWorkforcePosition(
      this,
      request,
      options,
    ));
  }

  /**
   * Update Public Workforce Position
   */
  async updatePublicWorkforcePosition(
    request: operations.UpdatePublicWorkforcePositionRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdatePublicWorkforcePositionResponse> {
    return unwrapAsync(workforcePlanningUpdatePublicWorkforcePosition(
      this,
      request,
      options,
    ));
  }

  /**
   * Set Public Workforce Position Job
   */
  async setPublicWorkforcePositionJob(
    request: operations.SetPublicWorkforcePositionJobRequest,
    options?: RequestOptions,
  ): Promise<operations.SetPublicWorkforcePositionJobResponse> {
    return unwrapAsync(workforcePlanningSetPublicWorkforcePositionJob(
      this,
      request,
      options,
    ));
  }

  /**
   * Set Public Workforce Position Occupant
   */
  async setPublicWorkforcePositionOccupant(
    request: operations.SetPublicWorkforcePositionOccupantRequest,
    options?: RequestOptions,
  ): Promise<operations.SetPublicWorkforcePositionOccupantResponse> {
    return unwrapAsync(workforcePlanningSetPublicWorkforcePositionOccupant(
      this,
      request,
      options,
    ));
  }
}
