/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type ApiRoutersV1DisbursementsPublicApiUpdatePublicDisbursementRequest =
  {
    disbursementId: string;
    body: models.PublicDisbursementRequest;
  };

/** @internal */
export type ApiRoutersV1DisbursementsPublicApiUpdatePublicDisbursementRequest$Outbound =
  {
    disbursement_id: string;
    body: models.PublicDisbursementRequest$Outbound;
  };

/** @internal */
export const ApiRoutersV1DisbursementsPublicApiUpdatePublicDisbursementRequest$outboundSchema:
  z.ZodMiniType<
    ApiRoutersV1DisbursementsPublicApiUpdatePublicDisbursementRequest$Outbound,
    ApiRoutersV1DisbursementsPublicApiUpdatePublicDisbursementRequest
  > = z.pipe(
    z.object({
      disbursementId: z.string(),
      body: models.PublicDisbursementRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        disbursementId: "disbursement_id",
      });
    }),
  );

export function apiRoutersV1DisbursementsPublicApiUpdatePublicDisbursementRequestToJSON(
  apiRoutersV1DisbursementsPublicApiUpdatePublicDisbursementRequest:
    ApiRoutersV1DisbursementsPublicApiUpdatePublicDisbursementRequest,
): string {
  return JSON.stringify(
    ApiRoutersV1DisbursementsPublicApiUpdatePublicDisbursementRequest$outboundSchema
      .parse(apiRoutersV1DisbursementsPublicApiUpdatePublicDisbursementRequest),
  );
}
