/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type ApiRoutersV1PurchaseOrdersPublicApiGetPublicPurchaseOrderRequest = {
  purchaseOrderId: string;
  externalId?: string | null | undefined;
  lang?: string | null | undefined;
  language?: string | null | undefined;
  acceptLanguage?: string | undefined;
};

/** @internal */
export type ApiRoutersV1PurchaseOrdersPublicApiGetPublicPurchaseOrderRequest$Outbound =
  {
    purchase_order_id: string;
    external_id?: string | null | undefined;
    lang?: string | null | undefined;
    language?: string | null | undefined;
    "Accept-Language"?: string | undefined;
  };

/** @internal */
export const ApiRoutersV1PurchaseOrdersPublicApiGetPublicPurchaseOrderRequest$outboundSchema:
  z.ZodMiniType<
    ApiRoutersV1PurchaseOrdersPublicApiGetPublicPurchaseOrderRequest$Outbound,
    ApiRoutersV1PurchaseOrdersPublicApiGetPublicPurchaseOrderRequest
  > = z.pipe(
    z.object({
      purchaseOrderId: z.string(),
      externalId: z.optional(z.nullable(z.string())),
      lang: z.optional(z.nullable(z.string())),
      language: z.optional(z.nullable(z.string())),
      acceptLanguage: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        purchaseOrderId: "purchase_order_id",
        externalId: "external_id",
        acceptLanguage: "Accept-Language",
      });
    }),
  );

export function apiRoutersV1PurchaseOrdersPublicApiGetPublicPurchaseOrderRequestToJSON(
  apiRoutersV1PurchaseOrdersPublicApiGetPublicPurchaseOrderRequest:
    ApiRoutersV1PurchaseOrdersPublicApiGetPublicPurchaseOrderRequest,
): string {
  return JSON.stringify(
    ApiRoutersV1PurchaseOrdersPublicApiGetPublicPurchaseOrderRequest$outboundSchema
      .parse(apiRoutersV1PurchaseOrdersPublicApiGetPublicPurchaseOrderRequest),
  );
}
