/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type ApiRoutersV1PropertiesPublicApiCreatePublicPropertyRequest = {
  objectName: string;
  body: models.PublicPropertyUpsertRequest;
};

/** @internal */
export type ApiRoutersV1PropertiesPublicApiCreatePublicPropertyRequest$Outbound =
  {
    object_name: string;
    body: models.PublicPropertyUpsertRequest$Outbound;
  };

/** @internal */
export const ApiRoutersV1PropertiesPublicApiCreatePublicPropertyRequest$outboundSchema:
  z.ZodMiniType<
    ApiRoutersV1PropertiesPublicApiCreatePublicPropertyRequest$Outbound,
    ApiRoutersV1PropertiesPublicApiCreatePublicPropertyRequest
  > = z.pipe(
    z.object({
      objectName: z.string(),
      body: models.PublicPropertyUpsertRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        objectName: "object_name",
      });
    }),
  );

export function apiRoutersV1PropertiesPublicApiCreatePublicPropertyRequestToJSON(
  apiRoutersV1PropertiesPublicApiCreatePublicPropertyRequest:
    ApiRoutersV1PropertiesPublicApiCreatePublicPropertyRequest,
): string {
  return JSON.stringify(
    ApiRoutersV1PropertiesPublicApiCreatePublicPropertyRequest$outboundSchema
      .parse(apiRoutersV1PropertiesPublicApiCreatePublicPropertyRequest),
  );
}
