/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type ApiRoutersV1ReportsPublicApiUpdatePublicReportRequest = {
  reportId: string;
  workspaceId?: string | null | undefined;
  body: models.PublicUpdateReportRequest;
};

/** @internal */
export type ApiRoutersV1ReportsPublicApiUpdatePublicReportRequest$Outbound = {
  report_id: string;
  workspace_id?: string | null | undefined;
  body: models.PublicUpdateReportRequest$Outbound;
};

/** @internal */
export const ApiRoutersV1ReportsPublicApiUpdatePublicReportRequest$outboundSchema:
  z.ZodMiniType<
    ApiRoutersV1ReportsPublicApiUpdatePublicReportRequest$Outbound,
    ApiRoutersV1ReportsPublicApiUpdatePublicReportRequest
  > = z.pipe(
    z.object({
      reportId: z.string(),
      workspaceId: z.optional(z.nullable(z.string())),
      body: models.PublicUpdateReportRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        reportId: "report_id",
        workspaceId: "workspace_id",
      });
    }),
  );

export function apiRoutersV1ReportsPublicApiUpdatePublicReportRequestToJSON(
  apiRoutersV1ReportsPublicApiUpdatePublicReportRequest:
    ApiRoutersV1ReportsPublicApiUpdatePublicReportRequest,
): string {
  return JSON.stringify(
    ApiRoutersV1ReportsPublicApiUpdatePublicReportRequest$outboundSchema.parse(
      apiRoutersV1ReportsPublicApiUpdatePublicReportRequest,
    ),
  );
}
