/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type ApiRoutersV1PaymentsPublicApiListWorkspacePaymentsRequest = {
  workspaceId?: string | null | undefined;
  lang?: string | null | undefined;
  language?: string | null | undefined;
  acceptLanguage?: string | undefined;
};

/** @internal */
export type ApiRoutersV1PaymentsPublicApiListWorkspacePaymentsRequest$Outbound =
  {
    workspace_id?: string | null | undefined;
    lang?: string | null | undefined;
    language?: string | null | undefined;
    "Accept-Language"?: string | undefined;
  };

/** @internal */
export const ApiRoutersV1PaymentsPublicApiListWorkspacePaymentsRequest$outboundSchema:
  z.ZodMiniType<
    ApiRoutersV1PaymentsPublicApiListWorkspacePaymentsRequest$Outbound,
    ApiRoutersV1PaymentsPublicApiListWorkspacePaymentsRequest
  > = z.pipe(
    z.object({
      workspaceId: z.optional(z.nullable(z.string())),
      lang: z.optional(z.nullable(z.string())),
      language: z.optional(z.nullable(z.string())),
      acceptLanguage: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        workspaceId: "workspace_id",
        acceptLanguage: "Accept-Language",
      });
    }),
  );

export function apiRoutersV1PaymentsPublicApiListWorkspacePaymentsRequestToJSON(
  apiRoutersV1PaymentsPublicApiListWorkspacePaymentsRequest:
    ApiRoutersV1PaymentsPublicApiListWorkspacePaymentsRequest,
): string {
  return JSON.stringify(
    ApiRoutersV1PaymentsPublicApiListWorkspacePaymentsRequest$outboundSchema
      .parse(apiRoutersV1PaymentsPublicApiListWorkspacePaymentsRequest),
  );
}
