/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type ApiRoutersV1ReportsPublicApiDeletePublicReportRequest = {
  reportId: string;
  workspaceId?: string | null | undefined;
};

/** @internal */
export type ApiRoutersV1ReportsPublicApiDeletePublicReportRequest$Outbound = {
  report_id: string;
  workspace_id?: string | null | undefined;
};

/** @internal */
export const ApiRoutersV1ReportsPublicApiDeletePublicReportRequest$outboundSchema:
  z.ZodMiniType<
    ApiRoutersV1ReportsPublicApiDeletePublicReportRequest$Outbound,
    ApiRoutersV1ReportsPublicApiDeletePublicReportRequest
  > = z.pipe(
    z.object({
      reportId: z.string(),
      workspaceId: z.optional(z.nullable(z.string())),
    }),
    z.transform((v) => {
      return remap$(v, {
        reportId: "report_id",
        workspaceId: "workspace_id",
      });
    }),
  );

export function apiRoutersV1ReportsPublicApiDeletePublicReportRequestToJSON(
  apiRoutersV1ReportsPublicApiDeletePublicReportRequest:
    ApiRoutersV1ReportsPublicApiDeletePublicReportRequest,
): string {
  return JSON.stringify(
    ApiRoutersV1ReportsPublicApiDeletePublicReportRequest$outboundSchema.parse(
      apiRoutersV1ReportsPublicApiDeletePublicReportRequest,
    ),
  );
}
