/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type ApiRoutersV1ReportsPublicApiGetPublicReportRequest = {
  reportId: string;
  workspaceId?: string | null | undefined;
};

/** @internal */
export type ApiRoutersV1ReportsPublicApiGetPublicReportRequest$Outbound = {
  report_id: string;
  workspace_id?: string | null | undefined;
};

/** @internal */
export const ApiRoutersV1ReportsPublicApiGetPublicReportRequest$outboundSchema:
  z.ZodMiniType<
    ApiRoutersV1ReportsPublicApiGetPublicReportRequest$Outbound,
    ApiRoutersV1ReportsPublicApiGetPublicReportRequest
  > = z.pipe(
    z.object({
      reportId: z.string(),
      workspaceId: z.optional(z.nullable(z.string())),
    }),
    z.transform((v) => {
      return remap$(v, {
        reportId: "report_id",
        workspaceId: "workspace_id",
      });
    }),
  );

export function apiRoutersV1ReportsPublicApiGetPublicReportRequestToJSON(
  apiRoutersV1ReportsPublicApiGetPublicReportRequest:
    ApiRoutersV1ReportsPublicApiGetPublicReportRequest,
): string {
  return JSON.stringify(
    ApiRoutersV1ReportsPublicApiGetPublicReportRequest$outboundSchema.parse(
      apiRoutersV1ReportsPublicApiGetPublicReportRequest,
    ),
  );
}
