/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type ApiRoutersV1TicketsPublicApiGetPublicTicketRequest = {
  ticketId: string;
  workspaceId?: string | null | undefined;
  externalId?: string | null | undefined;
};

/** @internal */
export type ApiRoutersV1TicketsPublicApiGetPublicTicketRequest$Outbound = {
  ticket_id: string;
  workspace_id?: string | null | undefined;
  external_id?: string | null | undefined;
};

/** @internal */
export const ApiRoutersV1TicketsPublicApiGetPublicTicketRequest$outboundSchema:
  z.ZodMiniType<
    ApiRoutersV1TicketsPublicApiGetPublicTicketRequest$Outbound,
    ApiRoutersV1TicketsPublicApiGetPublicTicketRequest
  > = z.pipe(
    z.object({
      ticketId: z.string(),
      workspaceId: z.optional(z.nullable(z.string())),
      externalId: z.optional(z.nullable(z.string())),
    }),
    z.transform((v) => {
      return remap$(v, {
        ticketId: "ticket_id",
        workspaceId: "workspace_id",
        externalId: "external_id",
      });
    }),
  );

export function apiRoutersV1TicketsPublicApiGetPublicTicketRequestToJSON(
  apiRoutersV1TicketsPublicApiGetPublicTicketRequest:
    ApiRoutersV1TicketsPublicApiGetPublicTicketRequest,
): string {
  return JSON.stringify(
    ApiRoutersV1TicketsPublicApiGetPublicTicketRequest$outboundSchema.parse(
      apiRoutersV1TicketsPublicApiGetPublicTicketRequest,
    ),
  );
}
