/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type ApiRoutersV1SubscriptionsPublicApiGetPublicSubscriptionRequest = {
  subscriptionId: string;
  externalId?: string | null | undefined;
};

/** @internal */
export type ApiRoutersV1SubscriptionsPublicApiGetPublicSubscriptionRequest$Outbound =
  {
    subscription_id: string;
    external_id?: string | null | undefined;
  };

/** @internal */
export const ApiRoutersV1SubscriptionsPublicApiGetPublicSubscriptionRequest$outboundSchema:
  z.ZodMiniType<
    ApiRoutersV1SubscriptionsPublicApiGetPublicSubscriptionRequest$Outbound,
    ApiRoutersV1SubscriptionsPublicApiGetPublicSubscriptionRequest
  > = z.pipe(
    z.object({
      subscriptionId: z.string(),
      externalId: z.optional(z.nullable(z.string())),
    }),
    z.transform((v) => {
      return remap$(v, {
        subscriptionId: "subscription_id",
        externalId: "external_id",
      });
    }),
  );

export function apiRoutersV1SubscriptionsPublicApiGetPublicSubscriptionRequestToJSON(
  apiRoutersV1SubscriptionsPublicApiGetPublicSubscriptionRequest:
    ApiRoutersV1SubscriptionsPublicApiGetPublicSubscriptionRequest,
): string {
  return JSON.stringify(
    ApiRoutersV1SubscriptionsPublicApiGetPublicSubscriptionRequest$outboundSchema
      .parse(apiRoutersV1SubscriptionsPublicApiGetPublicSubscriptionRequest),
  );
}
