/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type ApiRoutersV1InventoryTransactionsPublicApiDeletePublicInventoryTransactionRequest =
  {
    transactionId: string;
  };

/** @internal */
export type ApiRoutersV1InventoryTransactionsPublicApiDeletePublicInventoryTransactionRequest$Outbound =
  {
    transaction_id: string;
  };

/** @internal */
export const ApiRoutersV1InventoryTransactionsPublicApiDeletePublicInventoryTransactionRequest$outboundSchema:
  z.ZodMiniType<
    ApiRoutersV1InventoryTransactionsPublicApiDeletePublicInventoryTransactionRequest$Outbound,
    ApiRoutersV1InventoryTransactionsPublicApiDeletePublicInventoryTransactionRequest
  > = z.pipe(
    z.object({
      transactionId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        transactionId: "transaction_id",
      });
    }),
  );

export function apiRoutersV1InventoryTransactionsPublicApiDeletePublicInventoryTransactionRequestToJSON(
  apiRoutersV1InventoryTransactionsPublicApiDeletePublicInventoryTransactionRequest:
    ApiRoutersV1InventoryTransactionsPublicApiDeletePublicInventoryTransactionRequest,
): string {
  return JSON.stringify(
    ApiRoutersV1InventoryTransactionsPublicApiDeletePublicInventoryTransactionRequest$outboundSchema
      .parse(
        apiRoutersV1InventoryTransactionsPublicApiDeletePublicInventoryTransactionRequest,
      ),
  );
}
