/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ApprovePublicIncentiveApiV2PublicIncentivesIncentiveIdApprovePostRequest =
  {
    incentiveId: string;
    workspaceId?: string | null | undefined;
    xWorkspaceCode?: string | undefined;
  };

export type ApprovePublicIncentiveApiV2PublicIncentivesIncentiveIdApprovePostResponse =
  {
    headers: { [k: string]: Array<string> };
    result:
      models.ApprovePublicIncentiveApiV2PublicIncentivesIncentiveIdApprovePost200Envelope;
  };

/** @internal */
export type ApprovePublicIncentiveApiV2PublicIncentivesIncentiveIdApprovePostRequest$Outbound =
  {
    incentive_id: string;
    workspace_id?: string | null | undefined;
    "X-Workspace-Code"?: string | undefined;
  };

/** @internal */
export const ApprovePublicIncentiveApiV2PublicIncentivesIncentiveIdApprovePostRequest$outboundSchema:
  z.ZodMiniType<
    ApprovePublicIncentiveApiV2PublicIncentivesIncentiveIdApprovePostRequest$Outbound,
    ApprovePublicIncentiveApiV2PublicIncentivesIncentiveIdApprovePostRequest
  > = z.pipe(
    z.object({
      incentiveId: z.string(),
      workspaceId: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        incentiveId: "incentive_id",
        workspaceId: "workspace_id",
        xWorkspaceCode: "X-Workspace-Code",
      });
    }),
  );

export function approvePublicIncentiveApiV2PublicIncentivesIncentiveIdApprovePostRequestToJSON(
  approvePublicIncentiveApiV2PublicIncentivesIncentiveIdApprovePostRequest:
    ApprovePublicIncentiveApiV2PublicIncentivesIncentiveIdApprovePostRequest,
): string {
  return JSON.stringify(
    ApprovePublicIncentiveApiV2PublicIncentivesIncentiveIdApprovePostRequest$outboundSchema
      .parse(
        approvePublicIncentiveApiV2PublicIncentivesIncentiveIdApprovePostRequest,
      ),
  );
}

/** @internal */
export const ApprovePublicIncentiveApiV2PublicIncentivesIncentiveIdApprovePostResponse$inboundSchema:
  z.ZodMiniType<
    ApprovePublicIncentiveApiV2PublicIncentivesIncentiveIdApprovePostResponse,
    unknown
  > = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result:
        models
          .ApprovePublicIncentiveApiV2PublicIncentivesIncentiveIdApprovePost200Envelope$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function approvePublicIncentiveApiV2PublicIncentivesIncentiveIdApprovePostResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ApprovePublicIncentiveApiV2PublicIncentivesIncentiveIdApprovePostResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApprovePublicIncentiveApiV2PublicIncentivesIncentiveIdApprovePostResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ApprovePublicIncentiveApiV2PublicIncentivesIncentiveIdApprovePostResponse' from JSON`,
  );
}
