/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ApprovePublicPayrollRunApiV2PublicPayrollRunsRunIdApprovePostRequest =
  {
    runId: string;
    workspaceId?: string | null | undefined;
    xWorkspaceCode?: string | undefined;
  };

export type ApprovePublicPayrollRunApiV2PublicPayrollRunsRunIdApprovePostResponse =
  {
    headers: { [k: string]: Array<string> };
    result:
      models.ApprovePublicPayrollRunApiV2PublicPayrollRunsRunIdApprovePost200Envelope;
  };

/** @internal */
export type ApprovePublicPayrollRunApiV2PublicPayrollRunsRunIdApprovePostRequest$Outbound =
  {
    run_id: string;
    workspace_id?: string | null | undefined;
    "X-Workspace-Code"?: string | undefined;
  };

/** @internal */
export const ApprovePublicPayrollRunApiV2PublicPayrollRunsRunIdApprovePostRequest$outboundSchema:
  z.ZodMiniType<
    ApprovePublicPayrollRunApiV2PublicPayrollRunsRunIdApprovePostRequest$Outbound,
    ApprovePublicPayrollRunApiV2PublicPayrollRunsRunIdApprovePostRequest
  > = z.pipe(
    z.object({
      runId: z.string(),
      workspaceId: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        runId: "run_id",
        workspaceId: "workspace_id",
        xWorkspaceCode: "X-Workspace-Code",
      });
    }),
  );

export function approvePublicPayrollRunApiV2PublicPayrollRunsRunIdApprovePostRequestToJSON(
  approvePublicPayrollRunApiV2PublicPayrollRunsRunIdApprovePostRequest:
    ApprovePublicPayrollRunApiV2PublicPayrollRunsRunIdApprovePostRequest,
): string {
  return JSON.stringify(
    ApprovePublicPayrollRunApiV2PublicPayrollRunsRunIdApprovePostRequest$outboundSchema
      .parse(
        approvePublicPayrollRunApiV2PublicPayrollRunsRunIdApprovePostRequest,
      ),
  );
}

/** @internal */
export const ApprovePublicPayrollRunApiV2PublicPayrollRunsRunIdApprovePostResponse$inboundSchema:
  z.ZodMiniType<
    ApprovePublicPayrollRunApiV2PublicPayrollRunsRunIdApprovePostResponse,
    unknown
  > = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result:
        models
          .ApprovePublicPayrollRunApiV2PublicPayrollRunsRunIdApprovePost200Envelope$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function approvePublicPayrollRunApiV2PublicPayrollRunsRunIdApprovePostResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ApprovePublicPayrollRunApiV2PublicPayrollRunsRunIdApprovePostResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApprovePublicPayrollRunApiV2PublicPayrollRunsRunIdApprovePostResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ApprovePublicPayrollRunApiV2PublicPayrollRunsRunIdApprovePostResponse' from JSON`,
  );
}
