/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ArchivePublicJobPostingRequest = {
  recordRef: string;
  workspaceId?: string | null | undefined;
  xWorkspaceCode?: string | undefined;
};

export type ArchivePublicJobPostingResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ArchivePublicJobPosting200Envelope;
};

/** @internal */
export type ArchivePublicJobPostingRequest$Outbound = {
  record_ref: string;
  workspace_id?: string | null | undefined;
  "X-Workspace-Code"?: string | undefined;
};

/** @internal */
export const ArchivePublicJobPostingRequest$outboundSchema: z.ZodMiniType<
  ArchivePublicJobPostingRequest$Outbound,
  ArchivePublicJobPostingRequest
> = z.pipe(
  z.object({
    recordRef: z.string(),
    workspaceId: z.optional(z.nullable(z.string())),
    xWorkspaceCode: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      recordRef: "record_ref",
      workspaceId: "workspace_id",
      xWorkspaceCode: "X-Workspace-Code",
    });
  }),
);

export function archivePublicJobPostingRequestToJSON(
  archivePublicJobPostingRequest: ArchivePublicJobPostingRequest,
): string {
  return JSON.stringify(
    ArchivePublicJobPostingRequest$outboundSchema.parse(
      archivePublicJobPostingRequest,
    ),
  );
}

/** @internal */
export const ArchivePublicJobPostingResponse$inboundSchema: z.ZodMiniType<
  ArchivePublicJobPostingResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.ArchivePublicJobPosting200Envelope$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function archivePublicJobPostingResponseFromJSON(
  jsonString: string,
): SafeParseResult<ArchivePublicJobPostingResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ArchivePublicJobPostingResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ArchivePublicJobPostingResponse' from JSON`,
  );
}
