/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type BulkUpdatePublicSubscriptionsApiV2PublicSubscriptionsBulkUpdatePostRequest =
  {
    workspaceId?: string | null | undefined;
    acceptLanguage?: string | null | undefined;
    xWorkspaceCode?: string | undefined;
    body: models.ObjectRecordBulkActionRequest;
  };

export type BulkUpdatePublicSubscriptionsApiV2PublicSubscriptionsBulkUpdatePostResponseResult =
  | models.BulkUpdatePublicSubscriptionsApiV2PublicSubscriptionsBulkUpdatePost200Envelope
  | models.BulkUpdatePublicSubscriptionsApiV2PublicSubscriptionsBulkUpdatePost202Envelope;

export type BulkUpdatePublicSubscriptionsApiV2PublicSubscriptionsBulkUpdatePostResponse =
  {
    headers: { [k: string]: Array<string> };
    result:
      | models.BulkUpdatePublicSubscriptionsApiV2PublicSubscriptionsBulkUpdatePost200Envelope
      | models.BulkUpdatePublicSubscriptionsApiV2PublicSubscriptionsBulkUpdatePost202Envelope;
  };

/** @internal */
export type BulkUpdatePublicSubscriptionsApiV2PublicSubscriptionsBulkUpdatePostRequest$Outbound =
  {
    workspace_id?: string | null | undefined;
    "Accept-Language"?: string | null | undefined;
    "X-Workspace-Code"?: string | undefined;
    body: models.ObjectRecordBulkActionRequest$Outbound;
  };

/** @internal */
export const BulkUpdatePublicSubscriptionsApiV2PublicSubscriptionsBulkUpdatePostRequest$outboundSchema:
  z.ZodMiniType<
    BulkUpdatePublicSubscriptionsApiV2PublicSubscriptionsBulkUpdatePostRequest$Outbound,
    BulkUpdatePublicSubscriptionsApiV2PublicSubscriptionsBulkUpdatePostRequest
  > = z.pipe(
    z.object({
      workspaceId: z.optional(z.nullable(z.string())),
      acceptLanguage: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
      body: models.ObjectRecordBulkActionRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        workspaceId: "workspace_id",
        acceptLanguage: "Accept-Language",
        xWorkspaceCode: "X-Workspace-Code",
      });
    }),
  );

export function bulkUpdatePublicSubscriptionsApiV2PublicSubscriptionsBulkUpdatePostRequestToJSON(
  bulkUpdatePublicSubscriptionsApiV2PublicSubscriptionsBulkUpdatePostRequest:
    BulkUpdatePublicSubscriptionsApiV2PublicSubscriptionsBulkUpdatePostRequest,
): string {
  return JSON.stringify(
    BulkUpdatePublicSubscriptionsApiV2PublicSubscriptionsBulkUpdatePostRequest$outboundSchema
      .parse(
        bulkUpdatePublicSubscriptionsApiV2PublicSubscriptionsBulkUpdatePostRequest,
      ),
  );
}

/** @internal */
export const BulkUpdatePublicSubscriptionsApiV2PublicSubscriptionsBulkUpdatePostResponseResult$inboundSchema:
  z.ZodMiniType<
    BulkUpdatePublicSubscriptionsApiV2PublicSubscriptionsBulkUpdatePostResponseResult,
    unknown
  > = smartUnion([
    models
      .BulkUpdatePublicSubscriptionsApiV2PublicSubscriptionsBulkUpdatePost200Envelope$inboundSchema,
    models
      .BulkUpdatePublicSubscriptionsApiV2PublicSubscriptionsBulkUpdatePost202Envelope$inboundSchema,
  ]);

export function bulkUpdatePublicSubscriptionsApiV2PublicSubscriptionsBulkUpdatePostResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<
  BulkUpdatePublicSubscriptionsApiV2PublicSubscriptionsBulkUpdatePostResponseResult,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      BulkUpdatePublicSubscriptionsApiV2PublicSubscriptionsBulkUpdatePostResponseResult$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'BulkUpdatePublicSubscriptionsApiV2PublicSubscriptionsBulkUpdatePostResponseResult' from JSON`,
  );
}

/** @internal */
export const BulkUpdatePublicSubscriptionsApiV2PublicSubscriptionsBulkUpdatePostResponse$inboundSchema:
  z.ZodMiniType<
    BulkUpdatePublicSubscriptionsApiV2PublicSubscriptionsBulkUpdatePostResponse,
    unknown
  > = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result: smartUnion([
        models
          .BulkUpdatePublicSubscriptionsApiV2PublicSubscriptionsBulkUpdatePost200Envelope$inboundSchema,
        models
          .BulkUpdatePublicSubscriptionsApiV2PublicSubscriptionsBulkUpdatePost202Envelope$inboundSchema,
      ]),
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function bulkUpdatePublicSubscriptionsApiV2PublicSubscriptionsBulkUpdatePostResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  BulkUpdatePublicSubscriptionsApiV2PublicSubscriptionsBulkUpdatePostResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      BulkUpdatePublicSubscriptionsApiV2PublicSubscriptionsBulkUpdatePostResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'BulkUpdatePublicSubscriptionsApiV2PublicSubscriptionsBulkUpdatePostResponse' from JSON`,
  );
}
