/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CalculatePublicIncentivesApiV2PublicIncentivesCalculatePostRequest =
  {
    workspaceId?: string | null | undefined;
    xWorkspaceCode?: string | undefined;
    body: models.IncentiveCalculateRequest;
  };

export type CalculatePublicIncentivesApiV2PublicIncentivesCalculatePostResponse =
  {
    headers: { [k: string]: Array<string> };
    result:
      models.CalculatePublicIncentivesApiV2PublicIncentivesCalculatePost200Envelope;
  };

/** @internal */
export type CalculatePublicIncentivesApiV2PublicIncentivesCalculatePostRequest$Outbound =
  {
    workspace_id?: string | null | undefined;
    "X-Workspace-Code"?: string | undefined;
    body: models.IncentiveCalculateRequest$Outbound;
  };

/** @internal */
export const CalculatePublicIncentivesApiV2PublicIncentivesCalculatePostRequest$outboundSchema:
  z.ZodMiniType<
    CalculatePublicIncentivesApiV2PublicIncentivesCalculatePostRequest$Outbound,
    CalculatePublicIncentivesApiV2PublicIncentivesCalculatePostRequest
  > = z.pipe(
    z.object({
      workspaceId: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
      body: models.IncentiveCalculateRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        workspaceId: "workspace_id",
        xWorkspaceCode: "X-Workspace-Code",
      });
    }),
  );

export function calculatePublicIncentivesApiV2PublicIncentivesCalculatePostRequestToJSON(
  calculatePublicIncentivesApiV2PublicIncentivesCalculatePostRequest:
    CalculatePublicIncentivesApiV2PublicIncentivesCalculatePostRequest,
): string {
  return JSON.stringify(
    CalculatePublicIncentivesApiV2PublicIncentivesCalculatePostRequest$outboundSchema
      .parse(
        calculatePublicIncentivesApiV2PublicIncentivesCalculatePostRequest,
      ),
  );
}

/** @internal */
export const CalculatePublicIncentivesApiV2PublicIncentivesCalculatePostResponse$inboundSchema:
  z.ZodMiniType<
    CalculatePublicIncentivesApiV2PublicIncentivesCalculatePostResponse,
    unknown
  > = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result:
        models
          .CalculatePublicIncentivesApiV2PublicIncentivesCalculatePost200Envelope$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function calculatePublicIncentivesApiV2PublicIncentivesCalculatePostResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  CalculatePublicIncentivesApiV2PublicIncentivesCalculatePostResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CalculatePublicIncentivesApiV2PublicIncentivesCalculatePostResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'CalculatePublicIncentivesApiV2PublicIncentivesCalculatePostResponse' from JSON`,
  );
}
