/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CancelPublicProgramPresentationExportRequest = {
  programId: string;
  presentationId: string;
  exportId: string;
  workspaceId?: string | null | undefined;
  xWorkspaceCode?: string | undefined;
};

export type CancelPublicProgramPresentationExportResponse = {
  headers: { [k: string]: Array<string> };
  result: models.CancelPublicProgramPresentationExport200Envelope;
};

/** @internal */
export type CancelPublicProgramPresentationExportRequest$Outbound = {
  program_id: string;
  presentation_id: string;
  export_id: string;
  workspace_id?: string | null | undefined;
  "X-Workspace-Code"?: string | undefined;
};

/** @internal */
export const CancelPublicProgramPresentationExportRequest$outboundSchema:
  z.ZodMiniType<
    CancelPublicProgramPresentationExportRequest$Outbound,
    CancelPublicProgramPresentationExportRequest
  > = z.pipe(
    z.object({
      programId: z.string(),
      presentationId: z.string(),
      exportId: z.string(),
      workspaceId: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        programId: "program_id",
        presentationId: "presentation_id",
        exportId: "export_id",
        workspaceId: "workspace_id",
        xWorkspaceCode: "X-Workspace-Code",
      });
    }),
  );

export function cancelPublicProgramPresentationExportRequestToJSON(
  cancelPublicProgramPresentationExportRequest:
    CancelPublicProgramPresentationExportRequest,
): string {
  return JSON.stringify(
    CancelPublicProgramPresentationExportRequest$outboundSchema.parse(
      cancelPublicProgramPresentationExportRequest,
    ),
  );
}

/** @internal */
export const CancelPublicProgramPresentationExportResponse$inboundSchema:
  z.ZodMiniType<CancelPublicProgramPresentationExportResponse, unknown> = z
    .pipe(
      z.object({
        Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
        Result:
          models.CancelPublicProgramPresentationExport200Envelope$inboundSchema,
      }),
      z.transform((v) => {
        return remap$(v, {
          "Headers": "headers",
          "Result": "result",
        });
      }),
    );

export function cancelPublicProgramPresentationExportResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  CancelPublicProgramPresentationExportResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CancelPublicProgramPresentationExportResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'CancelPublicProgramPresentationExportResponse' from JSON`,
  );
}
