/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CreatePublicTicketApiV2PublicTicketsPostRequest = {
  workspaceId?: string | null | undefined;
  xWorkspaceCode?: string | undefined;
  body: models.ObjectRecordCreateRequest;
};

export type CreatePublicTicketApiV2PublicTicketsPostResponse = {
  headers: { [k: string]: Array<string> };
  result: models.CreatePublicTicketApiV2PublicTicketsPost200Envelope;
};

/** @internal */
export type CreatePublicTicketApiV2PublicTicketsPostRequest$Outbound = {
  workspace_id?: string | null | undefined;
  "X-Workspace-Code"?: string | undefined;
  body: models.ObjectRecordCreateRequest$Outbound;
};

/** @internal */
export const CreatePublicTicketApiV2PublicTicketsPostRequest$outboundSchema:
  z.ZodMiniType<
    CreatePublicTicketApiV2PublicTicketsPostRequest$Outbound,
    CreatePublicTicketApiV2PublicTicketsPostRequest
  > = z.pipe(
    z.object({
      workspaceId: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
      body: models.ObjectRecordCreateRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        workspaceId: "workspace_id",
        xWorkspaceCode: "X-Workspace-Code",
      });
    }),
  );

export function createPublicTicketApiV2PublicTicketsPostRequestToJSON(
  createPublicTicketApiV2PublicTicketsPostRequest:
    CreatePublicTicketApiV2PublicTicketsPostRequest,
): string {
  return JSON.stringify(
    CreatePublicTicketApiV2PublicTicketsPostRequest$outboundSchema.parse(
      createPublicTicketApiV2PublicTicketsPostRequest,
    ),
  );
}

/** @internal */
export const CreatePublicTicketApiV2PublicTicketsPostResponse$inboundSchema:
  z.ZodMiniType<CreatePublicTicketApiV2PublicTicketsPostResponse, unknown> = z
    .pipe(
      z.object({
        Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
        Result:
          models
            .CreatePublicTicketApiV2PublicTicketsPost200Envelope$inboundSchema,
      }),
      z.transform((v) => {
        return remap$(v, {
          "Headers": "headers",
          "Result": "result",
        });
      }),
    );

export function createPublicTicketApiV2PublicTicketsPostResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  CreatePublicTicketApiV2PublicTicketsPostResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CreatePublicTicketApiV2PublicTicketsPostResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'CreatePublicTicketApiV2PublicTicketsPostResponse' from JSON`,
  );
}
