/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CreatePublicLocationApiV2PublicLocationsPostRequest = {
  workspaceId?: string | null | undefined;
  xWorkspaceCode?: string | undefined;
  body: models.ObjectRecordCreateRequest;
};

export type CreatePublicLocationApiV2PublicLocationsPostResponse = {
  headers: { [k: string]: Array<string> };
  result: models.CreatePublicLocationApiV2PublicLocationsPost200Envelope;
};

/** @internal */
export type CreatePublicLocationApiV2PublicLocationsPostRequest$Outbound = {
  workspace_id?: string | null | undefined;
  "X-Workspace-Code"?: string | undefined;
  body: models.ObjectRecordCreateRequest$Outbound;
};

/** @internal */
export const CreatePublicLocationApiV2PublicLocationsPostRequest$outboundSchema:
  z.ZodMiniType<
    CreatePublicLocationApiV2PublicLocationsPostRequest$Outbound,
    CreatePublicLocationApiV2PublicLocationsPostRequest
  > = z.pipe(
    z.object({
      workspaceId: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
      body: models.ObjectRecordCreateRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        workspaceId: "workspace_id",
        xWorkspaceCode: "X-Workspace-Code",
      });
    }),
  );

export function createPublicLocationApiV2PublicLocationsPostRequestToJSON(
  createPublicLocationApiV2PublicLocationsPostRequest:
    CreatePublicLocationApiV2PublicLocationsPostRequest,
): string {
  return JSON.stringify(
    CreatePublicLocationApiV2PublicLocationsPostRequest$outboundSchema.parse(
      createPublicLocationApiV2PublicLocationsPostRequest,
    ),
  );
}

/** @internal */
export const CreatePublicLocationApiV2PublicLocationsPostResponse$inboundSchema:
  z.ZodMiniType<CreatePublicLocationApiV2PublicLocationsPostResponse, unknown> =
    z.pipe(
      z.object({
        Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
        Result:
          models
            .CreatePublicLocationApiV2PublicLocationsPost200Envelope$inboundSchema,
      }),
      z.transform((v) => {
        return remap$(v, {
          "Headers": "headers",
          "Result": "result",
        });
      }),
    );

export function createPublicLocationApiV2PublicLocationsPostResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  CreatePublicLocationApiV2PublicLocationsPostResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CreatePublicLocationApiV2PublicLocationsPostResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'CreatePublicLocationApiV2PublicLocationsPostResponse' from JSON`,
  );
}
