/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CreatePublicInventoryApiV2PublicInventoriesPostRequest = {
  workspaceId?: string | null | undefined;
  xWorkspaceCode?: string | undefined;
  body: models.PublicObjectRecordMutationRequest;
};

export type CreatePublicInventoryApiV2PublicInventoriesPostResponse = {
  headers: { [k: string]: Array<string> };
  result: models.CreatePublicInventoryApiV2PublicInventoriesPost200Envelope;
};

/** @internal */
export type CreatePublicInventoryApiV2PublicInventoriesPostRequest$Outbound = {
  workspace_id?: string | null | undefined;
  "X-Workspace-Code"?: string | undefined;
  body: models.PublicObjectRecordMutationRequest$Outbound;
};

/** @internal */
export const CreatePublicInventoryApiV2PublicInventoriesPostRequest$outboundSchema:
  z.ZodMiniType<
    CreatePublicInventoryApiV2PublicInventoriesPostRequest$Outbound,
    CreatePublicInventoryApiV2PublicInventoriesPostRequest
  > = z.pipe(
    z.object({
      workspaceId: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
      body: models.PublicObjectRecordMutationRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        workspaceId: "workspace_id",
        xWorkspaceCode: "X-Workspace-Code",
      });
    }),
  );

export function createPublicInventoryApiV2PublicInventoriesPostRequestToJSON(
  createPublicInventoryApiV2PublicInventoriesPostRequest:
    CreatePublicInventoryApiV2PublicInventoriesPostRequest,
): string {
  return JSON.stringify(
    CreatePublicInventoryApiV2PublicInventoriesPostRequest$outboundSchema.parse(
      createPublicInventoryApiV2PublicInventoriesPostRequest,
    ),
  );
}

/** @internal */
export const CreatePublicInventoryApiV2PublicInventoriesPostResponse$inboundSchema:
  z.ZodMiniType<
    CreatePublicInventoryApiV2PublicInventoriesPostResponse,
    unknown
  > = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result:
        models
          .CreatePublicInventoryApiV2PublicInventoriesPost200Envelope$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function createPublicInventoryApiV2PublicInventoriesPostResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  CreatePublicInventoryApiV2PublicInventoriesPostResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CreatePublicInventoryApiV2PublicInventoriesPostResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'CreatePublicInventoryApiV2PublicInventoriesPostResponse' from JSON`,
  );
}
