/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CreatePublicFerryDiagramApiV2PublicFerryDiagramsPostRequest = {
  workspaceId?: string | null | undefined;
  xWorkspaceCode?: string | undefined;
  body: models.FerryDiagramCreateRequest;
};

export type CreatePublicFerryDiagramApiV2PublicFerryDiagramsPostResponse = {
  headers: { [k: string]: Array<string> };
  result:
    models.CreatePublicFerryDiagramApiV2PublicFerryDiagramsPost200Envelope;
};

/** @internal */
export type CreatePublicFerryDiagramApiV2PublicFerryDiagramsPostRequest$Outbound =
  {
    workspace_id?: string | null | undefined;
    "X-Workspace-Code"?: string | undefined;
    body: models.FerryDiagramCreateRequest$Outbound;
  };

/** @internal */
export const CreatePublicFerryDiagramApiV2PublicFerryDiagramsPostRequest$outboundSchema:
  z.ZodMiniType<
    CreatePublicFerryDiagramApiV2PublicFerryDiagramsPostRequest$Outbound,
    CreatePublicFerryDiagramApiV2PublicFerryDiagramsPostRequest
  > = z.pipe(
    z.object({
      workspaceId: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
      body: models.FerryDiagramCreateRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        workspaceId: "workspace_id",
        xWorkspaceCode: "X-Workspace-Code",
      });
    }),
  );

export function createPublicFerryDiagramApiV2PublicFerryDiagramsPostRequestToJSON(
  createPublicFerryDiagramApiV2PublicFerryDiagramsPostRequest:
    CreatePublicFerryDiagramApiV2PublicFerryDiagramsPostRequest,
): string {
  return JSON.stringify(
    CreatePublicFerryDiagramApiV2PublicFerryDiagramsPostRequest$outboundSchema
      .parse(createPublicFerryDiagramApiV2PublicFerryDiagramsPostRequest),
  );
}

/** @internal */
export const CreatePublicFerryDiagramApiV2PublicFerryDiagramsPostResponse$inboundSchema:
  z.ZodMiniType<
    CreatePublicFerryDiagramApiV2PublicFerryDiagramsPostResponse,
    unknown
  > = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result:
        models
          .CreatePublicFerryDiagramApiV2PublicFerryDiagramsPost200Envelope$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function createPublicFerryDiagramApiV2PublicFerryDiagramsPostResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  CreatePublicFerryDiagramApiV2PublicFerryDiagramsPostResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CreatePublicFerryDiagramApiV2PublicFerryDiagramsPostResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'CreatePublicFerryDiagramApiV2PublicFerryDiagramsPostResponse' from JSON`,
  );
}
