/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CreatePublicProjectApiV2PublicProjectsPostRequest = {
  workspaceId?: string | null | undefined;
  xLanguage?: string | null | undefined;
  acceptLanguage?: string | null | undefined;
  xWorkspaceCode?: string | undefined;
  body: models.PublicProjectRequest;
};

export type CreatePublicProjectApiV2PublicProjectsPostResponse = {
  headers: { [k: string]: Array<string> };
  result: models.CreatePublicProjectApiV2PublicProjectsPost200Envelope;
};

/** @internal */
export type CreatePublicProjectApiV2PublicProjectsPostRequest$Outbound = {
  workspace_id?: string | null | undefined;
  "X-Language"?: string | null | undefined;
  "Accept-Language"?: string | null | undefined;
  "X-Workspace-Code"?: string | undefined;
  body: models.PublicProjectRequest$Outbound;
};

/** @internal */
export const CreatePublicProjectApiV2PublicProjectsPostRequest$outboundSchema:
  z.ZodMiniType<
    CreatePublicProjectApiV2PublicProjectsPostRequest$Outbound,
    CreatePublicProjectApiV2PublicProjectsPostRequest
  > = z.pipe(
    z.object({
      workspaceId: z.optional(z.nullable(z.string())),
      xLanguage: z.optional(z.nullable(z.string())),
      acceptLanguage: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
      body: models.PublicProjectRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        workspaceId: "workspace_id",
        xLanguage: "X-Language",
        acceptLanguage: "Accept-Language",
        xWorkspaceCode: "X-Workspace-Code",
      });
    }),
  );

export function createPublicProjectApiV2PublicProjectsPostRequestToJSON(
  createPublicProjectApiV2PublicProjectsPostRequest:
    CreatePublicProjectApiV2PublicProjectsPostRequest,
): string {
  return JSON.stringify(
    CreatePublicProjectApiV2PublicProjectsPostRequest$outboundSchema.parse(
      createPublicProjectApiV2PublicProjectsPostRequest,
    ),
  );
}

/** @internal */
export const CreatePublicProjectApiV2PublicProjectsPostResponse$inboundSchema:
  z.ZodMiniType<CreatePublicProjectApiV2PublicProjectsPostResponse, unknown> = z
    .pipe(
      z.object({
        Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
        Result:
          models
            .CreatePublicProjectApiV2PublicProjectsPost200Envelope$inboundSchema,
      }),
      z.transform((v) => {
        return remap$(v, {
          "Headers": "headers",
          "Result": "result",
        });
      }),
    );

export function createPublicProjectApiV2PublicProjectsPostResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  CreatePublicProjectApiV2PublicProjectsPostResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CreatePublicProjectApiV2PublicProjectsPostResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'CreatePublicProjectApiV2PublicProjectsPostResponse' from JSON`,
  );
}
