/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CreatePublicProgramPresentationExportRequest = {
  programId: string;
  presentationId: string;
  workspaceId?: string | null | undefined;
  idempotencyKey?: string | null | undefined;
  xWorkspaceCode?: string | undefined;
  body: models.PresentationExportRequest;
};

export type CreatePublicProgramPresentationExportResponse = {
  headers: { [k: string]: Array<string> };
  result: models.CreatePublicProgramPresentationExport202Envelope;
};

/** @internal */
export type CreatePublicProgramPresentationExportRequest$Outbound = {
  program_id: string;
  presentation_id: string;
  workspace_id?: string | null | undefined;
  "Idempotency-Key"?: string | null | undefined;
  "X-Workspace-Code"?: string | undefined;
  body: models.PresentationExportRequest$Outbound;
};

/** @internal */
export const CreatePublicProgramPresentationExportRequest$outboundSchema:
  z.ZodMiniType<
    CreatePublicProgramPresentationExportRequest$Outbound,
    CreatePublicProgramPresentationExportRequest
  > = z.pipe(
    z.object({
      programId: z.string(),
      presentationId: z.string(),
      workspaceId: z.optional(z.nullable(z.string())),
      idempotencyKey: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
      body: models.PresentationExportRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        programId: "program_id",
        presentationId: "presentation_id",
        workspaceId: "workspace_id",
        idempotencyKey: "Idempotency-Key",
        xWorkspaceCode: "X-Workspace-Code",
      });
    }),
  );

export function createPublicProgramPresentationExportRequestToJSON(
  createPublicProgramPresentationExportRequest:
    CreatePublicProgramPresentationExportRequest,
): string {
  return JSON.stringify(
    CreatePublicProgramPresentationExportRequest$outboundSchema.parse(
      createPublicProgramPresentationExportRequest,
    ),
  );
}

/** @internal */
export const CreatePublicProgramPresentationExportResponse$inboundSchema:
  z.ZodMiniType<CreatePublicProgramPresentationExportResponse, unknown> = z
    .pipe(
      z.object({
        Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
        Result:
          models.CreatePublicProgramPresentationExport202Envelope$inboundSchema,
      }),
      z.transform((v) => {
        return remap$(v, {
          "Headers": "headers",
          "Result": "result",
        });
      }),
    );

export function createPublicProgramPresentationExportResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  CreatePublicProgramPresentationExportResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CreatePublicProgramPresentationExportResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'CreatePublicProgramPresentationExportResponse' from JSON`,
  );
}
