/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CreatePublicDisbursementAllocationApiV2PublicDisbursementsDisbursementIdAllocationsPostRequest =
  {
    disbursementId: string;
    externalId?: string | null | undefined;
    lang?: string | null | undefined;
    language?: string | null | undefined;
    workspaceId?: string | null | undefined;
    xWorkspaceCode?: string | undefined;
    body: { [k: string]: any };
  };

export type CreatePublicDisbursementAllocationApiV2PublicDisbursementsDisbursementIdAllocationsPostResponse =
  {
    headers: { [k: string]: Array<string> };
    result:
      models.CreatePublicDisbursementAllocationApiV2PublicDisbursementsDisbursementIdAllocationsPost200Envelope;
  };

/** @internal */
export type CreatePublicDisbursementAllocationApiV2PublicDisbursementsDisbursementIdAllocationsPostRequest$Outbound =
  {
    disbursement_id: string;
    external_id?: string | null | undefined;
    lang?: string | null | undefined;
    language?: string | null | undefined;
    workspace_id?: string | null | undefined;
    "X-Workspace-Code"?: string | undefined;
    body: { [k: string]: any };
  };

/** @internal */
export const CreatePublicDisbursementAllocationApiV2PublicDisbursementsDisbursementIdAllocationsPostRequest$outboundSchema:
  z.ZodMiniType<
    CreatePublicDisbursementAllocationApiV2PublicDisbursementsDisbursementIdAllocationsPostRequest$Outbound,
    CreatePublicDisbursementAllocationApiV2PublicDisbursementsDisbursementIdAllocationsPostRequest
  > = z.pipe(
    z.object({
      disbursementId: z.string(),
      externalId: z.optional(z.nullable(z.string())),
      lang: z.optional(z.nullable(z.string())),
      language: z.optional(z.nullable(z.string())),
      workspaceId: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
      body: z.record(z.string(), z.any()),
    }),
    z.transform((v) => {
      return remap$(v, {
        disbursementId: "disbursement_id",
        externalId: "external_id",
        workspaceId: "workspace_id",
        xWorkspaceCode: "X-Workspace-Code",
      });
    }),
  );

export function createPublicDisbursementAllocationApiV2PublicDisbursementsDisbursementIdAllocationsPostRequestToJSON(
  createPublicDisbursementAllocationApiV2PublicDisbursementsDisbursementIdAllocationsPostRequest:
    CreatePublicDisbursementAllocationApiV2PublicDisbursementsDisbursementIdAllocationsPostRequest,
): string {
  return JSON.stringify(
    CreatePublicDisbursementAllocationApiV2PublicDisbursementsDisbursementIdAllocationsPostRequest$outboundSchema
      .parse(
        createPublicDisbursementAllocationApiV2PublicDisbursementsDisbursementIdAllocationsPostRequest,
      ),
  );
}

/** @internal */
export const CreatePublicDisbursementAllocationApiV2PublicDisbursementsDisbursementIdAllocationsPostResponse$inboundSchema:
  z.ZodMiniType<
    CreatePublicDisbursementAllocationApiV2PublicDisbursementsDisbursementIdAllocationsPostResponse,
    unknown
  > = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result:
        models
          .CreatePublicDisbursementAllocationApiV2PublicDisbursementsDisbursementIdAllocationsPost200Envelope$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function createPublicDisbursementAllocationApiV2PublicDisbursementsDisbursementIdAllocationsPostResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  CreatePublicDisbursementAllocationApiV2PublicDisbursementsDisbursementIdAllocationsPostResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CreatePublicDisbursementAllocationApiV2PublicDisbursementsDisbursementIdAllocationsPostResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'CreatePublicDisbursementAllocationApiV2PublicDisbursementsDisbursementIdAllocationsPostResponse' from JSON`,
  );
}
