/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type DeletePublicCompanyApiV2PublicCompaniesCompanyIdDeleteRequest = {
  companyId: string;
  externalId?: string | null | undefined;
  target?: string | null | undefined;
  provider?: string | null | undefined;
  channelId?: string | null | undefined;
  externalObjectType?: string | null | undefined;
  dryRun?: boolean | undefined;
  confirm?: boolean | undefined;
  workspaceId?: string | null | undefined;
  xWorkspaceCode?: string | undefined;
};

export type DeletePublicCompanyApiV2PublicCompaniesCompanyIdDeleteResponse = {
  headers: { [k: string]: Array<string> };
  result:
    models.DeletePublicCompanyApiV2PublicCompaniesCompanyIdDelete200Envelope;
};

/** @internal */
export type DeletePublicCompanyApiV2PublicCompaniesCompanyIdDeleteRequest$Outbound =
  {
    company_id: string;
    external_id?: string | null | undefined;
    target?: string | null | undefined;
    provider?: string | null | undefined;
    channel_id?: string | null | undefined;
    external_object_type?: string | null | undefined;
    dry_run: boolean;
    confirm: boolean;
    workspace_id?: string | null | undefined;
    "X-Workspace-Code"?: string | undefined;
  };

/** @internal */
export const DeletePublicCompanyApiV2PublicCompaniesCompanyIdDeleteRequest$outboundSchema:
  z.ZodMiniType<
    DeletePublicCompanyApiV2PublicCompaniesCompanyIdDeleteRequest$Outbound,
    DeletePublicCompanyApiV2PublicCompaniesCompanyIdDeleteRequest
  > = z.pipe(
    z.object({
      companyId: z.string(),
      externalId: z.optional(z.nullable(z.string())),
      target: z.optional(z.nullable(z.string())),
      provider: z.optional(z.nullable(z.string())),
      channelId: z.optional(z.nullable(z.string())),
      externalObjectType: z.optional(z.nullable(z.string())),
      dryRun: z._default(z.boolean(), false),
      confirm: z._default(z.boolean(), false),
      workspaceId: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        companyId: "company_id",
        externalId: "external_id",
        channelId: "channel_id",
        externalObjectType: "external_object_type",
        dryRun: "dry_run",
        workspaceId: "workspace_id",
        xWorkspaceCode: "X-Workspace-Code",
      });
    }),
  );

export function deletePublicCompanyApiV2PublicCompaniesCompanyIdDeleteRequestToJSON(
  deletePublicCompanyApiV2PublicCompaniesCompanyIdDeleteRequest:
    DeletePublicCompanyApiV2PublicCompaniesCompanyIdDeleteRequest,
): string {
  return JSON.stringify(
    DeletePublicCompanyApiV2PublicCompaniesCompanyIdDeleteRequest$outboundSchema
      .parse(deletePublicCompanyApiV2PublicCompaniesCompanyIdDeleteRequest),
  );
}

/** @internal */
export const DeletePublicCompanyApiV2PublicCompaniesCompanyIdDeleteResponse$inboundSchema:
  z.ZodMiniType<
    DeletePublicCompanyApiV2PublicCompaniesCompanyIdDeleteResponse,
    unknown
  > = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result:
        models
          .DeletePublicCompanyApiV2PublicCompaniesCompanyIdDelete200Envelope$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function deletePublicCompanyApiV2PublicCompaniesCompanyIdDeleteResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  DeletePublicCompanyApiV2PublicCompaniesCompanyIdDeleteResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeletePublicCompanyApiV2PublicCompaniesCompanyIdDeleteResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'DeletePublicCompanyApiV2PublicCompaniesCompanyIdDeleteResponse' from JSON`,
  );
}
