/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type DeletePublicJournalApiV2PublicJournalsJournalIdDeleteRequest = {
  journalId: string;
  workspaceId?: string | null | undefined;
  xWorkspaceCode?: string | undefined;
};

export type DeletePublicJournalApiV2PublicJournalsJournalIdDeleteResponse = {
  headers: { [k: string]: Array<string> };
  result:
    models.DeletePublicJournalApiV2PublicJournalsJournalIdDelete200Envelope;
};

/** @internal */
export type DeletePublicJournalApiV2PublicJournalsJournalIdDeleteRequest$Outbound =
  {
    journal_id: string;
    workspace_id?: string | null | undefined;
    "X-Workspace-Code"?: string | undefined;
  };

/** @internal */
export const DeletePublicJournalApiV2PublicJournalsJournalIdDeleteRequest$outboundSchema:
  z.ZodMiniType<
    DeletePublicJournalApiV2PublicJournalsJournalIdDeleteRequest$Outbound,
    DeletePublicJournalApiV2PublicJournalsJournalIdDeleteRequest
  > = z.pipe(
    z.object({
      journalId: z.string(),
      workspaceId: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        journalId: "journal_id",
        workspaceId: "workspace_id",
        xWorkspaceCode: "X-Workspace-Code",
      });
    }),
  );

export function deletePublicJournalApiV2PublicJournalsJournalIdDeleteRequestToJSON(
  deletePublicJournalApiV2PublicJournalsJournalIdDeleteRequest:
    DeletePublicJournalApiV2PublicJournalsJournalIdDeleteRequest,
): string {
  return JSON.stringify(
    DeletePublicJournalApiV2PublicJournalsJournalIdDeleteRequest$outboundSchema
      .parse(deletePublicJournalApiV2PublicJournalsJournalIdDeleteRequest),
  );
}

/** @internal */
export const DeletePublicJournalApiV2PublicJournalsJournalIdDeleteResponse$inboundSchema:
  z.ZodMiniType<
    DeletePublicJournalApiV2PublicJournalsJournalIdDeleteResponse,
    unknown
  > = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result:
        models
          .DeletePublicJournalApiV2PublicJournalsJournalIdDelete200Envelope$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function deletePublicJournalApiV2PublicJournalsJournalIdDeleteResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  DeletePublicJournalApiV2PublicJournalsJournalIdDeleteResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeletePublicJournalApiV2PublicJournalsJournalIdDeleteResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'DeletePublicJournalApiV2PublicJournalsJournalIdDeleteResponse' from JSON`,
  );
}
