/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type DeletePublicLockRuleApiV2PublicLockRulesRuleIdDeleteRequest = {
  ruleId: string;
  object?: string | null | undefined;
  objectName?: string | null | undefined;
  objectType?: string | null | undefined;
  settingType?: string | null | undefined;
  language?: string | null | undefined;
  workspaceId?: string | null | undefined;
  xWorkspaceCode?: string | undefined;
};

export type DeletePublicLockRuleApiV2PublicLockRulesRuleIdDeleteResponse = {
  headers: { [k: string]: Array<string> };
  result:
    models.DeletePublicLockRuleApiV2PublicLockRulesRuleIdDelete200Envelope;
};

/** @internal */
export type DeletePublicLockRuleApiV2PublicLockRulesRuleIdDeleteRequest$Outbound =
  {
    rule_id: string;
    object?: string | null | undefined;
    object_name?: string | null | undefined;
    object_type?: string | null | undefined;
    setting_type?: string | null | undefined;
    language?: string | null | undefined;
    workspace_id?: string | null | undefined;
    "X-Workspace-Code"?: string | undefined;
  };

/** @internal */
export const DeletePublicLockRuleApiV2PublicLockRulesRuleIdDeleteRequest$outboundSchema:
  z.ZodMiniType<
    DeletePublicLockRuleApiV2PublicLockRulesRuleIdDeleteRequest$Outbound,
    DeletePublicLockRuleApiV2PublicLockRulesRuleIdDeleteRequest
  > = z.pipe(
    z.object({
      ruleId: z.string(),
      object: z.optional(z.nullable(z.string())),
      objectName: z.optional(z.nullable(z.string())),
      objectType: z.optional(z.nullable(z.string())),
      settingType: z.optional(z.nullable(z.string())),
      language: z.optional(z.nullable(z.string())),
      workspaceId: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        ruleId: "rule_id",
        objectName: "object_name",
        objectType: "object_type",
        settingType: "setting_type",
        workspaceId: "workspace_id",
        xWorkspaceCode: "X-Workspace-Code",
      });
    }),
  );

export function deletePublicLockRuleApiV2PublicLockRulesRuleIdDeleteRequestToJSON(
  deletePublicLockRuleApiV2PublicLockRulesRuleIdDeleteRequest:
    DeletePublicLockRuleApiV2PublicLockRulesRuleIdDeleteRequest,
): string {
  return JSON.stringify(
    DeletePublicLockRuleApiV2PublicLockRulesRuleIdDeleteRequest$outboundSchema
      .parse(deletePublicLockRuleApiV2PublicLockRulesRuleIdDeleteRequest),
  );
}

/** @internal */
export const DeletePublicLockRuleApiV2PublicLockRulesRuleIdDeleteResponse$inboundSchema:
  z.ZodMiniType<
    DeletePublicLockRuleApiV2PublicLockRulesRuleIdDeleteResponse,
    unknown
  > = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result:
        models
          .DeletePublicLockRuleApiV2PublicLockRulesRuleIdDelete200Envelope$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function deletePublicLockRuleApiV2PublicLockRulesRuleIdDeleteResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  DeletePublicLockRuleApiV2PublicLockRulesRuleIdDeleteResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeletePublicLockRuleApiV2PublicLockRulesRuleIdDeleteResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'DeletePublicLockRuleApiV2PublicLockRulesRuleIdDeleteResponse' from JSON`,
  );
}
