/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type DeletePublicEstimateApiV2PublicEstimatesEstimateIdDeleteRequest = {
  estimateId: string;
  externalId?: string | null | undefined;
  workspaceId?: string | null | undefined;
  xWorkspaceCode?: string | undefined;
};

export type DeletePublicEstimateApiV2PublicEstimatesEstimateIdDeleteResponse = {
  headers: { [k: string]: Array<string> };
  result:
    models.DeletePublicEstimateApiV2PublicEstimatesEstimateIdDelete200Envelope;
};

/** @internal */
export type DeletePublicEstimateApiV2PublicEstimatesEstimateIdDeleteRequest$Outbound =
  {
    estimate_id: string;
    external_id?: string | null | undefined;
    workspace_id?: string | null | undefined;
    "X-Workspace-Code"?: string | undefined;
  };

/** @internal */
export const DeletePublicEstimateApiV2PublicEstimatesEstimateIdDeleteRequest$outboundSchema:
  z.ZodMiniType<
    DeletePublicEstimateApiV2PublicEstimatesEstimateIdDeleteRequest$Outbound,
    DeletePublicEstimateApiV2PublicEstimatesEstimateIdDeleteRequest
  > = z.pipe(
    z.object({
      estimateId: z.string(),
      externalId: z.optional(z.nullable(z.string())),
      workspaceId: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        estimateId: "estimate_id",
        externalId: "external_id",
        workspaceId: "workspace_id",
        xWorkspaceCode: "X-Workspace-Code",
      });
    }),
  );

export function deletePublicEstimateApiV2PublicEstimatesEstimateIdDeleteRequestToJSON(
  deletePublicEstimateApiV2PublicEstimatesEstimateIdDeleteRequest:
    DeletePublicEstimateApiV2PublicEstimatesEstimateIdDeleteRequest,
): string {
  return JSON.stringify(
    DeletePublicEstimateApiV2PublicEstimatesEstimateIdDeleteRequest$outboundSchema
      .parse(deletePublicEstimateApiV2PublicEstimatesEstimateIdDeleteRequest),
  );
}

/** @internal */
export const DeletePublicEstimateApiV2PublicEstimatesEstimateIdDeleteResponse$inboundSchema:
  z.ZodMiniType<
    DeletePublicEstimateApiV2PublicEstimatesEstimateIdDeleteResponse,
    unknown
  > = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result:
        models
          .DeletePublicEstimateApiV2PublicEstimatesEstimateIdDelete200Envelope$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function deletePublicEstimateApiV2PublicEstimatesEstimateIdDeleteResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  DeletePublicEstimateApiV2PublicEstimatesEstimateIdDeleteResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeletePublicEstimateApiV2PublicEstimatesEstimateIdDeleteResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'DeletePublicEstimateApiV2PublicEstimatesEstimateIdDeleteResponse' from JSON`,
  );
}
