/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type DeletePublicFerryProgramTodoApiV2PublicFerryProgramsProgramIdTodosTodoIdDeleteRequest =
  {
    programId: string;
    todoId: string;
    workspaceId?: string | null | undefined;
    xWorkspaceCode?: string | undefined;
  };

export type DeletePublicFerryProgramTodoApiV2PublicFerryProgramsProgramIdTodosTodoIdDeleteResponse =
  {
    headers: { [k: string]: Array<string> };
    result:
      models.DeletePublicFerryProgramTodoApiV2PublicFerryProgramsProgramIdTodosTodoIdDelete200Envelope;
  };

/** @internal */
export type DeletePublicFerryProgramTodoApiV2PublicFerryProgramsProgramIdTodosTodoIdDeleteRequest$Outbound =
  {
    program_id: string;
    todo_id: string;
    workspace_id?: string | null | undefined;
    "X-Workspace-Code"?: string | undefined;
  };

/** @internal */
export const DeletePublicFerryProgramTodoApiV2PublicFerryProgramsProgramIdTodosTodoIdDeleteRequest$outboundSchema:
  z.ZodMiniType<
    DeletePublicFerryProgramTodoApiV2PublicFerryProgramsProgramIdTodosTodoIdDeleteRequest$Outbound,
    DeletePublicFerryProgramTodoApiV2PublicFerryProgramsProgramIdTodosTodoIdDeleteRequest
  > = z.pipe(
    z.object({
      programId: z.string(),
      todoId: z.string(),
      workspaceId: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        programId: "program_id",
        todoId: "todo_id",
        workspaceId: "workspace_id",
        xWorkspaceCode: "X-Workspace-Code",
      });
    }),
  );

export function deletePublicFerryProgramTodoApiV2PublicFerryProgramsProgramIdTodosTodoIdDeleteRequestToJSON(
  deletePublicFerryProgramTodoApiV2PublicFerryProgramsProgramIdTodosTodoIdDeleteRequest:
    DeletePublicFerryProgramTodoApiV2PublicFerryProgramsProgramIdTodosTodoIdDeleteRequest,
): string {
  return JSON.stringify(
    DeletePublicFerryProgramTodoApiV2PublicFerryProgramsProgramIdTodosTodoIdDeleteRequest$outboundSchema
      .parse(
        deletePublicFerryProgramTodoApiV2PublicFerryProgramsProgramIdTodosTodoIdDeleteRequest,
      ),
  );
}

/** @internal */
export const DeletePublicFerryProgramTodoApiV2PublicFerryProgramsProgramIdTodosTodoIdDeleteResponse$inboundSchema:
  z.ZodMiniType<
    DeletePublicFerryProgramTodoApiV2PublicFerryProgramsProgramIdTodosTodoIdDeleteResponse,
    unknown
  > = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result:
        models
          .DeletePublicFerryProgramTodoApiV2PublicFerryProgramsProgramIdTodosTodoIdDelete200Envelope$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function deletePublicFerryProgramTodoApiV2PublicFerryProgramsProgramIdTodosTodoIdDeleteResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  DeletePublicFerryProgramTodoApiV2PublicFerryProgramsProgramIdTodosTodoIdDeleteResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeletePublicFerryProgramTodoApiV2PublicFerryProgramsProgramIdTodosTodoIdDeleteResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'DeletePublicFerryProgramTodoApiV2PublicFerryProgramsProgramIdTodosTodoIdDeleteResponse' from JSON`,
  );
}
