/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type DeletePublicViewApiV2PublicViewsViewIdDeleteRequest = {
  viewId: string;
  workspaceId?: string | null | undefined;
  xWorkspaceCode?: string | undefined;
};

export type DeletePublicViewApiV2PublicViewsViewIdDeleteResponse = {
  headers: { [k: string]: Array<string> };
  result: models.DeletePublicViewApiV2PublicViewsViewIdDelete200Envelope;
};

/** @internal */
export type DeletePublicViewApiV2PublicViewsViewIdDeleteRequest$Outbound = {
  view_id: string;
  workspace_id?: string | null | undefined;
  "X-Workspace-Code"?: string | undefined;
};

/** @internal */
export const DeletePublicViewApiV2PublicViewsViewIdDeleteRequest$outboundSchema:
  z.ZodMiniType<
    DeletePublicViewApiV2PublicViewsViewIdDeleteRequest$Outbound,
    DeletePublicViewApiV2PublicViewsViewIdDeleteRequest
  > = z.pipe(
    z.object({
      viewId: z.string(),
      workspaceId: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        viewId: "view_id",
        workspaceId: "workspace_id",
        xWorkspaceCode: "X-Workspace-Code",
      });
    }),
  );

export function deletePublicViewApiV2PublicViewsViewIdDeleteRequestToJSON(
  deletePublicViewApiV2PublicViewsViewIdDeleteRequest:
    DeletePublicViewApiV2PublicViewsViewIdDeleteRequest,
): string {
  return JSON.stringify(
    DeletePublicViewApiV2PublicViewsViewIdDeleteRequest$outboundSchema.parse(
      deletePublicViewApiV2PublicViewsViewIdDeleteRequest,
    ),
  );
}

/** @internal */
export const DeletePublicViewApiV2PublicViewsViewIdDeleteResponse$inboundSchema:
  z.ZodMiniType<DeletePublicViewApiV2PublicViewsViewIdDeleteResponse, unknown> =
    z.pipe(
      z.object({
        Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
        Result:
          models
            .DeletePublicViewApiV2PublicViewsViewIdDelete200Envelope$inboundSchema,
      }),
      z.transform((v) => {
        return remap$(v, {
          "Headers": "headers",
          "Result": "result",
        });
      }),
    );

export function deletePublicViewApiV2PublicViewsViewIdDeleteResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  DeletePublicViewApiV2PublicViewsViewIdDeleteResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeletePublicViewApiV2PublicViewsViewIdDeleteResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DeletePublicViewApiV2PublicViewsViewIdDeleteResponse' from JSON`,
  );
}
