/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type DeletePublicBillApiV2PublicBillsBillIdDeleteRequest = {
  billId: string;
  externalId?: string | null | undefined;
  workspaceId?: string | null | undefined;
  xWorkspaceCode?: string | undefined;
};

export type DeletePublicBillApiV2PublicBillsBillIdDeleteResponse = {
  headers: { [k: string]: Array<string> };
  result: models.DeletePublicBillApiV2PublicBillsBillIdDelete200Envelope;
};

/** @internal */
export type DeletePublicBillApiV2PublicBillsBillIdDeleteRequest$Outbound = {
  bill_id: string;
  external_id?: string | null | undefined;
  workspace_id?: string | null | undefined;
  "X-Workspace-Code"?: string | undefined;
};

/** @internal */
export const DeletePublicBillApiV2PublicBillsBillIdDeleteRequest$outboundSchema:
  z.ZodMiniType<
    DeletePublicBillApiV2PublicBillsBillIdDeleteRequest$Outbound,
    DeletePublicBillApiV2PublicBillsBillIdDeleteRequest
  > = z.pipe(
    z.object({
      billId: z.string(),
      externalId: z.optional(z.nullable(z.string())),
      workspaceId: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        billId: "bill_id",
        externalId: "external_id",
        workspaceId: "workspace_id",
        xWorkspaceCode: "X-Workspace-Code",
      });
    }),
  );

export function deletePublicBillApiV2PublicBillsBillIdDeleteRequestToJSON(
  deletePublicBillApiV2PublicBillsBillIdDeleteRequest:
    DeletePublicBillApiV2PublicBillsBillIdDeleteRequest,
): string {
  return JSON.stringify(
    DeletePublicBillApiV2PublicBillsBillIdDeleteRequest$outboundSchema.parse(
      deletePublicBillApiV2PublicBillsBillIdDeleteRequest,
    ),
  );
}

/** @internal */
export const DeletePublicBillApiV2PublicBillsBillIdDeleteResponse$inboundSchema:
  z.ZodMiniType<DeletePublicBillApiV2PublicBillsBillIdDeleteResponse, unknown> =
    z.pipe(
      z.object({
        Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
        Result:
          models
            .DeletePublicBillApiV2PublicBillsBillIdDelete200Envelope$inboundSchema,
      }),
      z.transform((v) => {
        return remap$(v, {
          "Headers": "headers",
          "Result": "result",
        });
      }),
    );

export function deletePublicBillApiV2PublicBillsBillIdDeleteResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  DeletePublicBillApiV2PublicBillsBillIdDeleteResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeletePublicBillApiV2PublicBillsBillIdDeleteResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DeletePublicBillApiV2PublicBillsBillIdDeleteResponse' from JSON`,
  );
}
