/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type DownloadPublicProgramPresentationExportRequest = {
  programId: string;
  presentationId: string;
  exportId: string;
  workspaceId?: string | null | undefined;
  xWorkspaceCode?: string | undefined;
};

export type DownloadPublicProgramPresentationExportResponseResult =
  | ReadableStream<Uint8Array>
  | ReadableStream<Uint8Array>;

export type DownloadPublicProgramPresentationExportResponse = {
  headers: { [k: string]: Array<string> };
  result: ReadableStream<Uint8Array> | ReadableStream<Uint8Array>;
};

/** @internal */
export type DownloadPublicProgramPresentationExportRequest$Outbound = {
  program_id: string;
  presentation_id: string;
  export_id: string;
  workspace_id?: string | null | undefined;
  "X-Workspace-Code"?: string | undefined;
};

/** @internal */
export const DownloadPublicProgramPresentationExportRequest$outboundSchema:
  z.ZodMiniType<
    DownloadPublicProgramPresentationExportRequest$Outbound,
    DownloadPublicProgramPresentationExportRequest
  > = z.pipe(
    z.object({
      programId: z.string(),
      presentationId: z.string(),
      exportId: z.string(),
      workspaceId: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        programId: "program_id",
        presentationId: "presentation_id",
        exportId: "export_id",
        workspaceId: "workspace_id",
        xWorkspaceCode: "X-Workspace-Code",
      });
    }),
  );

export function downloadPublicProgramPresentationExportRequestToJSON(
  downloadPublicProgramPresentationExportRequest:
    DownloadPublicProgramPresentationExportRequest,
): string {
  return JSON.stringify(
    DownloadPublicProgramPresentationExportRequest$outboundSchema.parse(
      downloadPublicProgramPresentationExportRequest,
    ),
  );
}

/** @internal */
export const DownloadPublicProgramPresentationExportResponseResult$inboundSchema:
  z.ZodMiniType<
    DownloadPublicProgramPresentationExportResponseResult,
    unknown
  > = smartUnion([
    z.custom<ReadableStream<Uint8Array>>(x => x instanceof ReadableStream),
    z.custom<ReadableStream<Uint8Array>>(x => x instanceof ReadableStream),
  ]);

export function downloadPublicProgramPresentationExportResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<
  DownloadPublicProgramPresentationExportResponseResult,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DownloadPublicProgramPresentationExportResponseResult$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DownloadPublicProgramPresentationExportResponseResult' from JSON`,
  );
}

/** @internal */
export const DownloadPublicProgramPresentationExportResponse$inboundSchema:
  z.ZodMiniType<DownloadPublicProgramPresentationExportResponse, unknown> = z
    .pipe(
      z.object({
        Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
        Result: smartUnion([
          z.custom<ReadableStream<Uint8Array>>(x =>
            x instanceof ReadableStream
          ),
          z.custom<ReadableStream<Uint8Array>>(x =>
            x instanceof ReadableStream
          ),
        ]),
      }),
      z.transform((v) => {
        return remap$(v, {
          "Headers": "headers",
          "Result": "result",
        });
      }),
    );

export function downloadPublicProgramPresentationExportResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  DownloadPublicProgramPresentationExportResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DownloadPublicProgramPresentationExportResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DownloadPublicProgramPresentationExportResponse' from JSON`,
  );
}
