/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type DownloadPublicEstimatePdfApiV2PublicEstimatesEstimateIdPdfGetRequest =
  {
    estimateId: string;
    externalId?: string | null | undefined;
    templateId?: string | null | undefined;
    templateSelect?: string | null | undefined;
    language?: string | null | undefined;
    workspaceId?: string | null | undefined;
    acceptLanguage?: string | null | undefined;
    xWorkspaceCode?: string | undefined;
  };

export type DownloadPublicEstimatePdfApiV2PublicEstimatesEstimateIdPdfGetResponse =
  {
    headers: { [k: string]: Array<string> };
    result: ReadableStream<Uint8Array>;
  };

/** @internal */
export type DownloadPublicEstimatePdfApiV2PublicEstimatesEstimateIdPdfGetRequest$Outbound =
  {
    estimate_id: string;
    external_id?: string | null | undefined;
    template_id?: string | null | undefined;
    template_select?: string | null | undefined;
    language?: string | null | undefined;
    workspace_id?: string | null | undefined;
    "Accept-Language"?: string | null | undefined;
    "X-Workspace-Code"?: string | undefined;
  };

/** @internal */
export const DownloadPublicEstimatePdfApiV2PublicEstimatesEstimateIdPdfGetRequest$outboundSchema:
  z.ZodMiniType<
    DownloadPublicEstimatePdfApiV2PublicEstimatesEstimateIdPdfGetRequest$Outbound,
    DownloadPublicEstimatePdfApiV2PublicEstimatesEstimateIdPdfGetRequest
  > = z.pipe(
    z.object({
      estimateId: z.string(),
      externalId: z.optional(z.nullable(z.string())),
      templateId: z.optional(z.nullable(z.string())),
      templateSelect: z.optional(z.nullable(z.string())),
      language: z.optional(z.nullable(z.string())),
      workspaceId: z.optional(z.nullable(z.string())),
      acceptLanguage: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        estimateId: "estimate_id",
        externalId: "external_id",
        templateId: "template_id",
        templateSelect: "template_select",
        workspaceId: "workspace_id",
        acceptLanguage: "Accept-Language",
        xWorkspaceCode: "X-Workspace-Code",
      });
    }),
  );

export function downloadPublicEstimatePdfApiV2PublicEstimatesEstimateIdPdfGetRequestToJSON(
  downloadPublicEstimatePdfApiV2PublicEstimatesEstimateIdPdfGetRequest:
    DownloadPublicEstimatePdfApiV2PublicEstimatesEstimateIdPdfGetRequest,
): string {
  return JSON.stringify(
    DownloadPublicEstimatePdfApiV2PublicEstimatesEstimateIdPdfGetRequest$outboundSchema
      .parse(
        downloadPublicEstimatePdfApiV2PublicEstimatesEstimateIdPdfGetRequest,
      ),
  );
}

/** @internal */
export const DownloadPublicEstimatePdfApiV2PublicEstimatesEstimateIdPdfGetResponse$inboundSchema:
  z.ZodMiniType<
    DownloadPublicEstimatePdfApiV2PublicEstimatesEstimateIdPdfGetResponse,
    unknown
  > = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result: z.custom<ReadableStream<Uint8Array>>(x =>
        x instanceof ReadableStream
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function downloadPublicEstimatePdfApiV2PublicEstimatesEstimateIdPdfGetResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  DownloadPublicEstimatePdfApiV2PublicEstimatesEstimateIdPdfGetResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DownloadPublicEstimatePdfApiV2PublicEstimatesEstimateIdPdfGetResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'DownloadPublicEstimatePdfApiV2PublicEstimatesEstimateIdPdfGetResponse' from JSON`,
  );
}
