/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetFleetRequest = {
  fleetId: string;
  workspaceId?: string | null | undefined;
  xWorkspaceCode?: string | undefined;
};

export type GetFleetResponse = {
  headers: { [k: string]: Array<string> };
  result:
    models.DeveloperCloudGetFleetApiV2MigrateCloudFleetsFleetIdGet200Envelope;
};

/** @internal */
export type GetFleetRequest$Outbound = {
  fleet_id: string;
  workspace_id?: string | null | undefined;
  "X-Workspace-Code"?: string | undefined;
};

/** @internal */
export const GetFleetRequest$outboundSchema: z.ZodMiniType<
  GetFleetRequest$Outbound,
  GetFleetRequest
> = z.pipe(
  z.object({
    fleetId: z.string(),
    workspaceId: z.optional(z.nullable(z.string())),
    xWorkspaceCode: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      fleetId: "fleet_id",
      workspaceId: "workspace_id",
      xWorkspaceCode: "X-Workspace-Code",
    });
  }),
);

export function getFleetRequestToJSON(
  getFleetRequest: GetFleetRequest,
): string {
  return JSON.stringify(GetFleetRequest$outboundSchema.parse(getFleetRequest));
}

/** @internal */
export const GetFleetResponse$inboundSchema: z.ZodMiniType<
  GetFleetResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result:
      models
        .DeveloperCloudGetFleetApiV2MigrateCloudFleetsFleetIdGet200Envelope$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getFleetResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetFleetResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetFleetResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetFleetResponse' from JSON`,
  );
}
