/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetPublicPresentationRequest = {
  presentationId: string;
  workspaceId?: string | null | undefined;
  xWorkspaceCode?: string | undefined;
};

export type GetPublicPresentationResponse = {
  headers: { [k: string]: Array<string> };
  result: models.GetPublicPresentation200Envelope;
};

/** @internal */
export type GetPublicPresentationRequest$Outbound = {
  presentation_id: string;
  workspace_id?: string | null | undefined;
  "X-Workspace-Code"?: string | undefined;
};

/** @internal */
export const GetPublicPresentationRequest$outboundSchema: z.ZodMiniType<
  GetPublicPresentationRequest$Outbound,
  GetPublicPresentationRequest
> = z.pipe(
  z.object({
    presentationId: z.string(),
    workspaceId: z.optional(z.nullable(z.string())),
    xWorkspaceCode: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      presentationId: "presentation_id",
      workspaceId: "workspace_id",
      xWorkspaceCode: "X-Workspace-Code",
    });
  }),
);

export function getPublicPresentationRequestToJSON(
  getPublicPresentationRequest: GetPublicPresentationRequest,
): string {
  return JSON.stringify(
    GetPublicPresentationRequest$outboundSchema.parse(
      getPublicPresentationRequest,
    ),
  );
}

/** @internal */
export const GetPublicPresentationResponse$inboundSchema: z.ZodMiniType<
  GetPublicPresentationResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.GetPublicPresentation200Envelope$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getPublicPresentationResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetPublicPresentationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPublicPresentationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPublicPresentationResponse' from JSON`,
  );
}
