/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetPublicReportApiV2PublicReportsReportIdGetRequest = {
  reportId: string;
  workspaceId?: string | null | undefined;
  xWorkspaceCode?: string | undefined;
};

export type GetPublicReportApiV2PublicReportsReportIdGetResponse = {
  headers: { [k: string]: Array<string> };
  result: models.GetPublicReportApiV2PublicReportsReportIdGet200Envelope;
};

/** @internal */
export type GetPublicReportApiV2PublicReportsReportIdGetRequest$Outbound = {
  report_id: string;
  workspace_id?: string | null | undefined;
  "X-Workspace-Code"?: string | undefined;
};

/** @internal */
export const GetPublicReportApiV2PublicReportsReportIdGetRequest$outboundSchema:
  z.ZodMiniType<
    GetPublicReportApiV2PublicReportsReportIdGetRequest$Outbound,
    GetPublicReportApiV2PublicReportsReportIdGetRequest
  > = z.pipe(
    z.object({
      reportId: z.string(),
      workspaceId: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        reportId: "report_id",
        workspaceId: "workspace_id",
        xWorkspaceCode: "X-Workspace-Code",
      });
    }),
  );

export function getPublicReportApiV2PublicReportsReportIdGetRequestToJSON(
  getPublicReportApiV2PublicReportsReportIdGetRequest:
    GetPublicReportApiV2PublicReportsReportIdGetRequest,
): string {
  return JSON.stringify(
    GetPublicReportApiV2PublicReportsReportIdGetRequest$outboundSchema.parse(
      getPublicReportApiV2PublicReportsReportIdGetRequest,
    ),
  );
}

/** @internal */
export const GetPublicReportApiV2PublicReportsReportIdGetResponse$inboundSchema:
  z.ZodMiniType<GetPublicReportApiV2PublicReportsReportIdGetResponse, unknown> =
    z.pipe(
      z.object({
        Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
        Result:
          models
            .GetPublicReportApiV2PublicReportsReportIdGet200Envelope$inboundSchema,
      }),
      z.transform((v) => {
        return remap$(v, {
          "Headers": "headers",
          "Result": "result",
        });
      }),
    );

export function getPublicReportApiV2PublicReportsReportIdGetResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetPublicReportApiV2PublicReportsReportIdGetResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetPublicReportApiV2PublicReportsReportIdGetResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetPublicReportApiV2PublicReportsReportIdGetResponse' from JSON`,
  );
}
