/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetPublicOrderApiV2PublicOrdersOrderIdGetRequest = {
  orderId: string;
  externalId?: string | null | undefined;
  workspaceId?: string | null | undefined;
  viewId?: string | null | undefined;
  formViewId?: string | null | undefined;
  xWorkspaceCode?: string | undefined;
};

export type GetPublicOrderApiV2PublicOrdersOrderIdGetResponse = {
  headers: { [k: string]: Array<string> };
  result: models.GetPublicOrderApiV2PublicOrdersOrderIdGet200Envelope;
};

/** @internal */
export type GetPublicOrderApiV2PublicOrdersOrderIdGetRequest$Outbound = {
  order_id: string;
  external_id?: string | null | undefined;
  workspace_id?: string | null | undefined;
  view_id?: string | null | undefined;
  form_view_id?: string | null | undefined;
  "X-Workspace-Code"?: string | undefined;
};

/** @internal */
export const GetPublicOrderApiV2PublicOrdersOrderIdGetRequest$outboundSchema:
  z.ZodMiniType<
    GetPublicOrderApiV2PublicOrdersOrderIdGetRequest$Outbound,
    GetPublicOrderApiV2PublicOrdersOrderIdGetRequest
  > = z.pipe(
    z.object({
      orderId: z.string(),
      externalId: z.optional(z.nullable(z.string())),
      workspaceId: z.optional(z.nullable(z.string())),
      viewId: z.optional(z.nullable(z.string())),
      formViewId: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        orderId: "order_id",
        externalId: "external_id",
        workspaceId: "workspace_id",
        viewId: "view_id",
        formViewId: "form_view_id",
        xWorkspaceCode: "X-Workspace-Code",
      });
    }),
  );

export function getPublicOrderApiV2PublicOrdersOrderIdGetRequestToJSON(
  getPublicOrderApiV2PublicOrdersOrderIdGetRequest:
    GetPublicOrderApiV2PublicOrdersOrderIdGetRequest,
): string {
  return JSON.stringify(
    GetPublicOrderApiV2PublicOrdersOrderIdGetRequest$outboundSchema.parse(
      getPublicOrderApiV2PublicOrdersOrderIdGetRequest,
    ),
  );
}

/** @internal */
export const GetPublicOrderApiV2PublicOrdersOrderIdGetResponse$inboundSchema:
  z.ZodMiniType<GetPublicOrderApiV2PublicOrdersOrderIdGetResponse, unknown> = z
    .pipe(
      z.object({
        Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
        Result:
          models
            .GetPublicOrderApiV2PublicOrdersOrderIdGet200Envelope$inboundSchema,
      }),
      z.transform((v) => {
        return remap$(v, {
          "Headers": "headers",
          "Result": "result",
        });
      }),
    );

export function getPublicOrderApiV2PublicOrdersOrderIdGetResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetPublicOrderApiV2PublicOrdersOrderIdGetResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetPublicOrderApiV2PublicOrdersOrderIdGetResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetPublicOrderApiV2PublicOrdersOrderIdGetResponse' from JSON`,
  );
}
