/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetPublicIncentiveBatchApiV2PublicIncentivesBatchesBatchIdGetRequest =
  {
    batchId: string;
    workspaceId?: string | null | undefined;
    xWorkspaceCode?: string | undefined;
  };

export type GetPublicIncentiveBatchApiV2PublicIncentivesBatchesBatchIdGetResponse =
  {
    headers: { [k: string]: Array<string> };
    result:
      models.GetPublicIncentiveBatchApiV2PublicIncentivesBatchesBatchIdGet200Envelope;
  };

/** @internal */
export type GetPublicIncentiveBatchApiV2PublicIncentivesBatchesBatchIdGetRequest$Outbound =
  {
    batch_id: string;
    workspace_id?: string | null | undefined;
    "X-Workspace-Code"?: string | undefined;
  };

/** @internal */
export const GetPublicIncentiveBatchApiV2PublicIncentivesBatchesBatchIdGetRequest$outboundSchema:
  z.ZodMiniType<
    GetPublicIncentiveBatchApiV2PublicIncentivesBatchesBatchIdGetRequest$Outbound,
    GetPublicIncentiveBatchApiV2PublicIncentivesBatchesBatchIdGetRequest
  > = z.pipe(
    z.object({
      batchId: z.string(),
      workspaceId: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        batchId: "batch_id",
        workspaceId: "workspace_id",
        xWorkspaceCode: "X-Workspace-Code",
      });
    }),
  );

export function getPublicIncentiveBatchApiV2PublicIncentivesBatchesBatchIdGetRequestToJSON(
  getPublicIncentiveBatchApiV2PublicIncentivesBatchesBatchIdGetRequest:
    GetPublicIncentiveBatchApiV2PublicIncentivesBatchesBatchIdGetRequest,
): string {
  return JSON.stringify(
    GetPublicIncentiveBatchApiV2PublicIncentivesBatchesBatchIdGetRequest$outboundSchema
      .parse(
        getPublicIncentiveBatchApiV2PublicIncentivesBatchesBatchIdGetRequest,
      ),
  );
}

/** @internal */
export const GetPublicIncentiveBatchApiV2PublicIncentivesBatchesBatchIdGetResponse$inboundSchema:
  z.ZodMiniType<
    GetPublicIncentiveBatchApiV2PublicIncentivesBatchesBatchIdGetResponse,
    unknown
  > = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result:
        models
          .GetPublicIncentiveBatchApiV2PublicIncentivesBatchesBatchIdGet200Envelope$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function getPublicIncentiveBatchApiV2PublicIncentivesBatchesBatchIdGetResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetPublicIncentiveBatchApiV2PublicIncentivesBatchesBatchIdGetResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetPublicIncentiveBatchApiV2PublicIncentivesBatchesBatchIdGetResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetPublicIncentiveBatchApiV2PublicIncentivesBatchesBatchIdGetResponse' from JSON`,
  );
}
