/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetPublicContactApiV2PublicContactsContactIdGetRequest = {
  contactId: string;
  externalId?: string | null | undefined;
  workspaceId?: string | null | undefined;
  viewId?: string | null | undefined;
  formViewId?: string | null | undefined;
  xWorkspaceCode?: string | undefined;
};

export type GetPublicContactApiV2PublicContactsContactIdGetResponse = {
  headers: { [k: string]: Array<string> };
  result: models.GetPublicContactApiV2PublicContactsContactIdGet200Envelope;
};

/** @internal */
export type GetPublicContactApiV2PublicContactsContactIdGetRequest$Outbound = {
  contact_id: string;
  external_id?: string | null | undefined;
  workspace_id?: string | null | undefined;
  view_id?: string | null | undefined;
  form_view_id?: string | null | undefined;
  "X-Workspace-Code"?: string | undefined;
};

/** @internal */
export const GetPublicContactApiV2PublicContactsContactIdGetRequest$outboundSchema:
  z.ZodMiniType<
    GetPublicContactApiV2PublicContactsContactIdGetRequest$Outbound,
    GetPublicContactApiV2PublicContactsContactIdGetRequest
  > = z.pipe(
    z.object({
      contactId: z.string(),
      externalId: z.optional(z.nullable(z.string())),
      workspaceId: z.optional(z.nullable(z.string())),
      viewId: z.optional(z.nullable(z.string())),
      formViewId: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        contactId: "contact_id",
        externalId: "external_id",
        workspaceId: "workspace_id",
        viewId: "view_id",
        formViewId: "form_view_id",
        xWorkspaceCode: "X-Workspace-Code",
      });
    }),
  );

export function getPublicContactApiV2PublicContactsContactIdGetRequestToJSON(
  getPublicContactApiV2PublicContactsContactIdGetRequest:
    GetPublicContactApiV2PublicContactsContactIdGetRequest,
): string {
  return JSON.stringify(
    GetPublicContactApiV2PublicContactsContactIdGetRequest$outboundSchema.parse(
      getPublicContactApiV2PublicContactsContactIdGetRequest,
    ),
  );
}

/** @internal */
export const GetPublicContactApiV2PublicContactsContactIdGetResponse$inboundSchema:
  z.ZodMiniType<
    GetPublicContactApiV2PublicContactsContactIdGetResponse,
    unknown
  > = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result:
        models
          .GetPublicContactApiV2PublicContactsContactIdGet200Envelope$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function getPublicContactApiV2PublicContactsContactIdGetResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetPublicContactApiV2PublicContactsContactIdGetResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetPublicContactApiV2PublicContactsContactIdGetResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetPublicContactApiV2PublicContactsContactIdGetResponse' from JSON`,
  );
}
