/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetPublicPresentationExportRequest = {
  presentationId: string;
  exportId: string;
  workspaceId?: string | null | undefined;
  xWorkspaceCode?: string | undefined;
};

export type GetPublicPresentationExportResponse = {
  headers: { [k: string]: Array<string> };
  result: models.GetPublicPresentationExport200Envelope;
};

/** @internal */
export type GetPublicPresentationExportRequest$Outbound = {
  presentation_id: string;
  export_id: string;
  workspace_id?: string | null | undefined;
  "X-Workspace-Code"?: string | undefined;
};

/** @internal */
export const GetPublicPresentationExportRequest$outboundSchema: z.ZodMiniType<
  GetPublicPresentationExportRequest$Outbound,
  GetPublicPresentationExportRequest
> = z.pipe(
  z.object({
    presentationId: z.string(),
    exportId: z.string(),
    workspaceId: z.optional(z.nullable(z.string())),
    xWorkspaceCode: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      presentationId: "presentation_id",
      exportId: "export_id",
      workspaceId: "workspace_id",
      xWorkspaceCode: "X-Workspace-Code",
    });
  }),
);

export function getPublicPresentationExportRequestToJSON(
  getPublicPresentationExportRequest: GetPublicPresentationExportRequest,
): string {
  return JSON.stringify(
    GetPublicPresentationExportRequest$outboundSchema.parse(
      getPublicPresentationExportRequest,
    ),
  );
}

/** @internal */
export const GetPublicPresentationExportResponse$inboundSchema: z.ZodMiniType<
  GetPublicPresentationExportResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.GetPublicPresentationExport200Envelope$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getPublicPresentationExportResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetPublicPresentationExportResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetPublicPresentationExportResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPublicPresentationExportResponse' from JSON`,
  );
}
