/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetPublicPayrollRunApiV2PublicPayrollRunsRunIdGetRequest = {
  runId: string;
  workspaceId?: string | null | undefined;
  xWorkspaceCode?: string | undefined;
};

export type GetPublicPayrollRunApiV2PublicPayrollRunsRunIdGetResponse = {
  headers: { [k: string]: Array<string> };
  result: models.GetPublicPayrollRunApiV2PublicPayrollRunsRunIdGet200Envelope;
};

/** @internal */
export type GetPublicPayrollRunApiV2PublicPayrollRunsRunIdGetRequest$Outbound =
  {
    run_id: string;
    workspace_id?: string | null | undefined;
    "X-Workspace-Code"?: string | undefined;
  };

/** @internal */
export const GetPublicPayrollRunApiV2PublicPayrollRunsRunIdGetRequest$outboundSchema:
  z.ZodMiniType<
    GetPublicPayrollRunApiV2PublicPayrollRunsRunIdGetRequest$Outbound,
    GetPublicPayrollRunApiV2PublicPayrollRunsRunIdGetRequest
  > = z.pipe(
    z.object({
      runId: z.string(),
      workspaceId: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        runId: "run_id",
        workspaceId: "workspace_id",
        xWorkspaceCode: "X-Workspace-Code",
      });
    }),
  );

export function getPublicPayrollRunApiV2PublicPayrollRunsRunIdGetRequestToJSON(
  getPublicPayrollRunApiV2PublicPayrollRunsRunIdGetRequest:
    GetPublicPayrollRunApiV2PublicPayrollRunsRunIdGetRequest,
): string {
  return JSON.stringify(
    GetPublicPayrollRunApiV2PublicPayrollRunsRunIdGetRequest$outboundSchema
      .parse(getPublicPayrollRunApiV2PublicPayrollRunsRunIdGetRequest),
  );
}

/** @internal */
export const GetPublicPayrollRunApiV2PublicPayrollRunsRunIdGetResponse$inboundSchema:
  z.ZodMiniType<
    GetPublicPayrollRunApiV2PublicPayrollRunsRunIdGetResponse,
    unknown
  > = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result:
        models
          .GetPublicPayrollRunApiV2PublicPayrollRunsRunIdGet200Envelope$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function getPublicPayrollRunApiV2PublicPayrollRunsRunIdGetResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetPublicPayrollRunApiV2PublicPayrollRunsRunIdGetResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetPublicPayrollRunApiV2PublicPayrollRunsRunIdGetResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetPublicPayrollRunApiV2PublicPayrollRunsRunIdGetResponse' from JSON`,
  );
}
