/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ImportPublicPresentationImageRequest = {
  presentationId: string;
  workspaceId?: string | null | undefined;
  xWorkspaceCode?: string | undefined;
  body: models.PresentationImageImportRequest;
};

export type ImportPublicPresentationImageResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ImportPublicPresentationImage201Envelope;
};

/** @internal */
export type ImportPublicPresentationImageRequest$Outbound = {
  presentation_id: string;
  workspace_id?: string | null | undefined;
  "X-Workspace-Code"?: string | undefined;
  body: models.PresentationImageImportRequest$Outbound;
};

/** @internal */
export const ImportPublicPresentationImageRequest$outboundSchema: z.ZodMiniType<
  ImportPublicPresentationImageRequest$Outbound,
  ImportPublicPresentationImageRequest
> = z.pipe(
  z.object({
    presentationId: z.string(),
    workspaceId: z.optional(z.nullable(z.string())),
    xWorkspaceCode: z.optional(z.string()),
    body: models.PresentationImageImportRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      presentationId: "presentation_id",
      workspaceId: "workspace_id",
      xWorkspaceCode: "X-Workspace-Code",
    });
  }),
);

export function importPublicPresentationImageRequestToJSON(
  importPublicPresentationImageRequest: ImportPublicPresentationImageRequest,
): string {
  return JSON.stringify(
    ImportPublicPresentationImageRequest$outboundSchema.parse(
      importPublicPresentationImageRequest,
    ),
  );
}

/** @internal */
export const ImportPublicPresentationImageResponse$inboundSchema: z.ZodMiniType<
  ImportPublicPresentationImageResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.ImportPublicPresentationImage201Envelope$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function importPublicPresentationImageResponseFromJSON(
  jsonString: string,
): SafeParseResult<ImportPublicPresentationImageResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ImportPublicPresentationImageResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ImportPublicPresentationImageResponse' from JSON`,
  );
}
