/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListPublicPayrollRunsApiV2PublicPayrollRunsGetRequest = {
  period?: string | null | undefined;
  workspaceId?: string | null | undefined;
  xWorkspaceCode?: string | undefined;
};

export type ListPublicPayrollRunsApiV2PublicPayrollRunsGetResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ListPublicPayrollRunsApiV2PublicPayrollRunsGet200Envelope;
};

/** @internal */
export type ListPublicPayrollRunsApiV2PublicPayrollRunsGetRequest$Outbound = {
  period?: string | null | undefined;
  workspace_id?: string | null | undefined;
  "X-Workspace-Code"?: string | undefined;
};

/** @internal */
export const ListPublicPayrollRunsApiV2PublicPayrollRunsGetRequest$outboundSchema:
  z.ZodMiniType<
    ListPublicPayrollRunsApiV2PublicPayrollRunsGetRequest$Outbound,
    ListPublicPayrollRunsApiV2PublicPayrollRunsGetRequest
  > = z.pipe(
    z.object({
      period: z.optional(z.nullable(z.string())),
      workspaceId: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        workspaceId: "workspace_id",
        xWorkspaceCode: "X-Workspace-Code",
      });
    }),
  );

export function listPublicPayrollRunsApiV2PublicPayrollRunsGetRequestToJSON(
  listPublicPayrollRunsApiV2PublicPayrollRunsGetRequest:
    ListPublicPayrollRunsApiV2PublicPayrollRunsGetRequest,
): string {
  return JSON.stringify(
    ListPublicPayrollRunsApiV2PublicPayrollRunsGetRequest$outboundSchema.parse(
      listPublicPayrollRunsApiV2PublicPayrollRunsGetRequest,
    ),
  );
}

/** @internal */
export const ListPublicPayrollRunsApiV2PublicPayrollRunsGetResponse$inboundSchema:
  z.ZodMiniType<
    ListPublicPayrollRunsApiV2PublicPayrollRunsGetResponse,
    unknown
  > = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result:
        models
          .ListPublicPayrollRunsApiV2PublicPayrollRunsGet200Envelope$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function listPublicPayrollRunsApiV2PublicPayrollRunsGetResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ListPublicPayrollRunsApiV2PublicPayrollRunsGetResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListPublicPayrollRunsApiV2PublicPayrollRunsGetResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ListPublicPayrollRunsApiV2PublicPayrollRunsGetResponse' from JSON`,
  );
}
