/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListProviderActionsApiV2LookoutProviderActionsGetRequest = {
  provider?: string | null | undefined;
  status?: string | null | undefined;
  runId?: string | null | undefined;
  limit?: number | undefined;
  workspaceId?: string | null | undefined;
  xWorkspaceCode?: string | undefined;
};

export type ListProviderActionsApiV2LookoutProviderActionsGetResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ListProviderActionsApiV2LookoutProviderActionsGet200Envelope;
};

/** @internal */
export type ListProviderActionsApiV2LookoutProviderActionsGetRequest$Outbound =
  {
    provider?: string | null | undefined;
    status?: string | null | undefined;
    run_id?: string | null | undefined;
    limit: number;
    workspace_id?: string | null | undefined;
    "X-Workspace-Code"?: string | undefined;
  };

/** @internal */
export const ListProviderActionsApiV2LookoutProviderActionsGetRequest$outboundSchema:
  z.ZodMiniType<
    ListProviderActionsApiV2LookoutProviderActionsGetRequest$Outbound,
    ListProviderActionsApiV2LookoutProviderActionsGetRequest
  > = z.pipe(
    z.object({
      provider: z.optional(z.nullable(z.string())),
      status: z.optional(z.nullable(z.string())),
      runId: z.optional(z.nullable(z.string())),
      limit: z._default(z.int(), 50),
      workspaceId: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        runId: "run_id",
        workspaceId: "workspace_id",
        xWorkspaceCode: "X-Workspace-Code",
      });
    }),
  );

export function listProviderActionsApiV2LookoutProviderActionsGetRequestToJSON(
  listProviderActionsApiV2LookoutProviderActionsGetRequest:
    ListProviderActionsApiV2LookoutProviderActionsGetRequest,
): string {
  return JSON.stringify(
    ListProviderActionsApiV2LookoutProviderActionsGetRequest$outboundSchema
      .parse(listProviderActionsApiV2LookoutProviderActionsGetRequest),
  );
}

/** @internal */
export const ListProviderActionsApiV2LookoutProviderActionsGetResponse$inboundSchema:
  z.ZodMiniType<
    ListProviderActionsApiV2LookoutProviderActionsGetResponse,
    unknown
  > = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result:
        models
          .ListProviderActionsApiV2LookoutProviderActionsGet200Envelope$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function listProviderActionsApiV2LookoutProviderActionsGetResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ListProviderActionsApiV2LookoutProviderActionsGetResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListProviderActionsApiV2LookoutProviderActionsGetResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ListProviderActionsApiV2LookoutProviderActionsGetResponse' from JSON`,
  );
}
