/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListEventsRequest = {
  runId: string;
  cursor?: number | undefined;
  limit?: number | undefined;
  workspaceId?: string | null | undefined;
  xWorkspaceCode?: string | undefined;
};

export type ListEventsResponse = {
  headers: { [k: string]: Array<string> };
  result:
    models.DeveloperCloudCloudRunEventsApiV2MigrateCloudRunsRunIdEventsGet200Envelope;
};

/** @internal */
export type ListEventsRequest$Outbound = {
  run_id: string;
  cursor: number;
  limit: number;
  workspace_id?: string | null | undefined;
  "X-Workspace-Code"?: string | undefined;
};

/** @internal */
export const ListEventsRequest$outboundSchema: z.ZodMiniType<
  ListEventsRequest$Outbound,
  ListEventsRequest
> = z.pipe(
  z.object({
    runId: z.string(),
    cursor: z._default(z.int(), 0),
    limit: z._default(z.int(), 100),
    workspaceId: z.optional(z.nullable(z.string())),
    xWorkspaceCode: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      runId: "run_id",
      workspaceId: "workspace_id",
      xWorkspaceCode: "X-Workspace-Code",
    });
  }),
);

export function listEventsRequestToJSON(
  listEventsRequest: ListEventsRequest,
): string {
  return JSON.stringify(
    ListEventsRequest$outboundSchema.parse(listEventsRequest),
  );
}

/** @internal */
export const ListEventsResponse$inboundSchema: z.ZodMiniType<
  ListEventsResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result:
      models
        .DeveloperCloudCloudRunEventsApiV2MigrateCloudRunsRunIdEventsGet200Envelope$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function listEventsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListEventsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListEventsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListEventsResponse' from JSON`,
  );
}
