/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListPublicApprovalRulesApiV2PublicApprovalRulesGetRequest = {
  object?: string | null | undefined;
  objectName?: string | null | undefined;
  objectType?: string | null | undefined;
  settingType?: string | null | undefined;
  language?: string | null | undefined;
  workspaceId?: string | null | undefined;
  xWorkspaceCode?: string | undefined;
};

export type ListPublicApprovalRulesApiV2PublicApprovalRulesGetResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ListPublicApprovalRulesApiV2PublicApprovalRulesGet200Envelope;
};

/** @internal */
export type ListPublicApprovalRulesApiV2PublicApprovalRulesGetRequest$Outbound =
  {
    object?: string | null | undefined;
    object_name?: string | null | undefined;
    object_type?: string | null | undefined;
    setting_type?: string | null | undefined;
    language?: string | null | undefined;
    workspace_id?: string | null | undefined;
    "X-Workspace-Code"?: string | undefined;
  };

/** @internal */
export const ListPublicApprovalRulesApiV2PublicApprovalRulesGetRequest$outboundSchema:
  z.ZodMiniType<
    ListPublicApprovalRulesApiV2PublicApprovalRulesGetRequest$Outbound,
    ListPublicApprovalRulesApiV2PublicApprovalRulesGetRequest
  > = z.pipe(
    z.object({
      object: z.optional(z.nullable(z.string())),
      objectName: z.optional(z.nullable(z.string())),
      objectType: z.optional(z.nullable(z.string())),
      settingType: z.optional(z.nullable(z.string())),
      language: z.optional(z.nullable(z.string())),
      workspaceId: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        objectName: "object_name",
        objectType: "object_type",
        settingType: "setting_type",
        workspaceId: "workspace_id",
        xWorkspaceCode: "X-Workspace-Code",
      });
    }),
  );

export function listPublicApprovalRulesApiV2PublicApprovalRulesGetRequestToJSON(
  listPublicApprovalRulesApiV2PublicApprovalRulesGetRequest:
    ListPublicApprovalRulesApiV2PublicApprovalRulesGetRequest,
): string {
  return JSON.stringify(
    ListPublicApprovalRulesApiV2PublicApprovalRulesGetRequest$outboundSchema
      .parse(listPublicApprovalRulesApiV2PublicApprovalRulesGetRequest),
  );
}

/** @internal */
export const ListPublicApprovalRulesApiV2PublicApprovalRulesGetResponse$inboundSchema:
  z.ZodMiniType<
    ListPublicApprovalRulesApiV2PublicApprovalRulesGetResponse,
    unknown
  > = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result:
        models
          .ListPublicApprovalRulesApiV2PublicApprovalRulesGet200Envelope$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function listPublicApprovalRulesApiV2PublicApprovalRulesGetResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ListPublicApprovalRulesApiV2PublicApprovalRulesGetResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListPublicApprovalRulesApiV2PublicApprovalRulesGetResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ListPublicApprovalRulesApiV2PublicApprovalRulesGetResponse' from JSON`,
  );
}
