/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListPublicTasksApiV2PublicTasksGetRequest = {
  projectId?: string | null | undefined;
  pId?: string | null | undefined;
  workspaceId?: string | null | undefined;
  viewId?: string | null | undefined;
  search?: string | null | undefined;
  language?: string | null | undefined;
  status?: string | null | undefined;
  usageStatus?: string | null | undefined;
  page?: number | undefined;
  limit?: number | null | undefined;
  cursor?: string | null | undefined;
  sort?: string | null | undefined;
  createdAtFrom?: string | null | undefined;
  createdAtTo?: string | null | undefined;
  updatedAtFrom?: string | null | undefined;
  updatedAtTo?: string | null | undefined;
  xWorkspaceCode?: string | undefined;
  xLanguage?: string | null | undefined;
  acceptLanguage?: string | null | undefined;
};

export type ListPublicTasksApiV2PublicTasksGetResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ListPublicTasksApiV2PublicTasksGet200Envelope;
};

/** @internal */
export type ListPublicTasksApiV2PublicTasksGetRequest$Outbound = {
  project_id?: string | null | undefined;
  p_id?: string | null | undefined;
  workspace_id?: string | null | undefined;
  view_id?: string | null | undefined;
  search?: string | null | undefined;
  language?: string | null | undefined;
  status?: string | null | undefined;
  usage_status?: string | null | undefined;
  page: number;
  limit?: number | null | undefined;
  cursor?: string | null | undefined;
  sort?: string | null | undefined;
  created_at_from?: string | null | undefined;
  created_at_to?: string | null | undefined;
  updated_at_from?: string | null | undefined;
  updated_at_to?: string | null | undefined;
  "X-Workspace-Code"?: string | undefined;
  "X-Language"?: string | null | undefined;
  "Accept-Language"?: string | null | undefined;
};

/** @internal */
export const ListPublicTasksApiV2PublicTasksGetRequest$outboundSchema:
  z.ZodMiniType<
    ListPublicTasksApiV2PublicTasksGetRequest$Outbound,
    ListPublicTasksApiV2PublicTasksGetRequest
  > = z.pipe(
    z.object({
      projectId: z.optional(z.nullable(z.string())),
      pId: z.optional(z.nullable(z.string())),
      workspaceId: z.optional(z.nullable(z.string())),
      viewId: z.optional(z.nullable(z.string())),
      search: z.optional(z.nullable(z.string())),
      language: z.optional(z.nullable(z.string())),
      status: z.optional(z.nullable(z.string())),
      usageStatus: z.optional(z.nullable(z.string())),
      page: z._default(z.int(), 1),
      limit: z.optional(z.nullable(z.int())),
      cursor: z.optional(z.nullable(z.string())),
      sort: z.optional(z.nullable(z.string())),
      createdAtFrom: z.optional(z.nullable(z.string())),
      createdAtTo: z.optional(z.nullable(z.string())),
      updatedAtFrom: z.optional(z.nullable(z.string())),
      updatedAtTo: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
      xLanguage: z.optional(z.nullable(z.string())),
      acceptLanguage: z.optional(z.nullable(z.string())),
    }),
    z.transform((v) => {
      return remap$(v, {
        projectId: "project_id",
        pId: "p_id",
        workspaceId: "workspace_id",
        viewId: "view_id",
        usageStatus: "usage_status",
        createdAtFrom: "created_at_from",
        createdAtTo: "created_at_to",
        updatedAtFrom: "updated_at_from",
        updatedAtTo: "updated_at_to",
        xWorkspaceCode: "X-Workspace-Code",
        xLanguage: "X-Language",
        acceptLanguage: "Accept-Language",
      });
    }),
  );

export function listPublicTasksApiV2PublicTasksGetRequestToJSON(
  listPublicTasksApiV2PublicTasksGetRequest:
    ListPublicTasksApiV2PublicTasksGetRequest,
): string {
  return JSON.stringify(
    ListPublicTasksApiV2PublicTasksGetRequest$outboundSchema.parse(
      listPublicTasksApiV2PublicTasksGetRequest,
    ),
  );
}

/** @internal */
export const ListPublicTasksApiV2PublicTasksGetResponse$inboundSchema:
  z.ZodMiniType<ListPublicTasksApiV2PublicTasksGetResponse, unknown> = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result:
        models.ListPublicTasksApiV2PublicTasksGet200Envelope$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function listPublicTasksApiV2PublicTasksGetResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ListPublicTasksApiV2PublicTasksGetResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListPublicTasksApiV2PublicTasksGetResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListPublicTasksApiV2PublicTasksGetResponse' from JSON`,
  );
}
