/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListPublicLocationsApiV2PublicLocationsGetRequest = {
  workspaceId?: string | null | undefined;
  viewId?: string | null | undefined;
  search?: string | null | undefined;
  language?: string | null | undefined;
  status?: string | null | undefined;
  usageStatus?: string | null | undefined;
  page?: number | undefined;
  limit?: number | null | undefined;
  sort?: string | null | undefined;
  xWorkspaceCode?: string | undefined;
  xLanguage?: string | null | undefined;
  acceptLanguage?: string | null | undefined;
};

export type ListPublicLocationsApiV2PublicLocationsGetResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ListPublicLocationsApiV2PublicLocationsGet200Envelope;
};

/** @internal */
export type ListPublicLocationsApiV2PublicLocationsGetRequest$Outbound = {
  workspace_id?: string | null | undefined;
  view_id?: string | null | undefined;
  search?: string | null | undefined;
  language?: string | null | undefined;
  status?: string | null | undefined;
  usage_status?: string | null | undefined;
  page: number;
  limit?: number | null | undefined;
  sort?: string | null | undefined;
  "X-Workspace-Code"?: string | undefined;
  "X-Language"?: string | null | undefined;
  "Accept-Language"?: string | null | undefined;
};

/** @internal */
export const ListPublicLocationsApiV2PublicLocationsGetRequest$outboundSchema:
  z.ZodMiniType<
    ListPublicLocationsApiV2PublicLocationsGetRequest$Outbound,
    ListPublicLocationsApiV2PublicLocationsGetRequest
  > = z.pipe(
    z.object({
      workspaceId: z.optional(z.nullable(z.string())),
      viewId: z.optional(z.nullable(z.string())),
      search: z.optional(z.nullable(z.string())),
      language: z.optional(z.nullable(z.string())),
      status: z.optional(z.nullable(z.string())),
      usageStatus: z.optional(z.nullable(z.string())),
      page: z._default(z.int(), 1),
      limit: z.optional(z.nullable(z.int())),
      sort: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
      xLanguage: z.optional(z.nullable(z.string())),
      acceptLanguage: z.optional(z.nullable(z.string())),
    }),
    z.transform((v) => {
      return remap$(v, {
        workspaceId: "workspace_id",
        viewId: "view_id",
        usageStatus: "usage_status",
        xWorkspaceCode: "X-Workspace-Code",
        xLanguage: "X-Language",
        acceptLanguage: "Accept-Language",
      });
    }),
  );

export function listPublicLocationsApiV2PublicLocationsGetRequestToJSON(
  listPublicLocationsApiV2PublicLocationsGetRequest:
    ListPublicLocationsApiV2PublicLocationsGetRequest,
): string {
  return JSON.stringify(
    ListPublicLocationsApiV2PublicLocationsGetRequest$outboundSchema.parse(
      listPublicLocationsApiV2PublicLocationsGetRequest,
    ),
  );
}

/** @internal */
export const ListPublicLocationsApiV2PublicLocationsGetResponse$inboundSchema:
  z.ZodMiniType<ListPublicLocationsApiV2PublicLocationsGetResponse, unknown> = z
    .pipe(
      z.object({
        Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
        Result:
          models
            .ListPublicLocationsApiV2PublicLocationsGet200Envelope$inboundSchema,
      }),
      z.transform((v) => {
        return remap$(v, {
          "Headers": "headers",
          "Result": "result",
        });
      }),
    );

export function listPublicLocationsApiV2PublicLocationsGetResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ListPublicLocationsApiV2PublicLocationsGetResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListPublicLocationsApiV2PublicLocationsGetResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListPublicLocationsApiV2PublicLocationsGetResponse' from JSON`,
  );
}
