/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListPublicDealsApiV2PublicDealsGetRequest = {
  workspaceId?: string | null | undefined;
  viewId?: string | null | undefined;
  search?: string | null | undefined;
  language?: string | null | undefined;
  status?: string | null | undefined;
  usageStatus?: string | null | undefined;
  page?: number | undefined;
  limit?: number | null | undefined;
  sort?: string | null | undefined;
  xWorkspaceCode?: string | undefined;
  xLanguage?: string | null | undefined;
  acceptLanguage?: string | null | undefined;
};

export type ListPublicDealsApiV2PublicDealsGetResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ListPublicDealsApiV2PublicDealsGet200Envelope;
};

/** @internal */
export type ListPublicDealsApiV2PublicDealsGetRequest$Outbound = {
  workspace_id?: string | null | undefined;
  view_id?: string | null | undefined;
  search?: string | null | undefined;
  language?: string | null | undefined;
  status?: string | null | undefined;
  usage_status?: string | null | undefined;
  page: number;
  limit?: number | null | undefined;
  sort?: string | null | undefined;
  "X-Workspace-Code"?: string | undefined;
  "X-Language"?: string | null | undefined;
  "Accept-Language"?: string | null | undefined;
};

/** @internal */
export const ListPublicDealsApiV2PublicDealsGetRequest$outboundSchema:
  z.ZodMiniType<
    ListPublicDealsApiV2PublicDealsGetRequest$Outbound,
    ListPublicDealsApiV2PublicDealsGetRequest
  > = z.pipe(
    z.object({
      workspaceId: z.optional(z.nullable(z.string())),
      viewId: z.optional(z.nullable(z.string())),
      search: z.optional(z.nullable(z.string())),
      language: z.optional(z.nullable(z.string())),
      status: z.optional(z.nullable(z.string())),
      usageStatus: z.optional(z.nullable(z.string())),
      page: z._default(z.int(), 1),
      limit: z.optional(z.nullable(z.int())),
      sort: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
      xLanguage: z.optional(z.nullable(z.string())),
      acceptLanguage: z.optional(z.nullable(z.string())),
    }),
    z.transform((v) => {
      return remap$(v, {
        workspaceId: "workspace_id",
        viewId: "view_id",
        usageStatus: "usage_status",
        xWorkspaceCode: "X-Workspace-Code",
        xLanguage: "X-Language",
        acceptLanguage: "Accept-Language",
      });
    }),
  );

export function listPublicDealsApiV2PublicDealsGetRequestToJSON(
  listPublicDealsApiV2PublicDealsGetRequest:
    ListPublicDealsApiV2PublicDealsGetRequest,
): string {
  return JSON.stringify(
    ListPublicDealsApiV2PublicDealsGetRequest$outboundSchema.parse(
      listPublicDealsApiV2PublicDealsGetRequest,
    ),
  );
}

/** @internal */
export const ListPublicDealsApiV2PublicDealsGetResponse$inboundSchema:
  z.ZodMiniType<ListPublicDealsApiV2PublicDealsGetResponse, unknown> = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result:
        models.ListPublicDealsApiV2PublicDealsGet200Envelope$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function listPublicDealsApiV2PublicDealsGetResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ListPublicDealsApiV2PublicDealsGetResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListPublicDealsApiV2PublicDealsGetResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListPublicDealsApiV2PublicDealsGetResponse' from JSON`,
  );
}
