/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListPublicProgramPresentationsRequest = {
  programId: string;
  /**
   * Only presentations in this Docs folder.
   */
  folderId?: string | null | undefined;
  /**
   * `nextCursor` from the previous page.
   */
  cursor?: string | null | undefined;
  limit?: number | undefined;
  includeArchived?: boolean | undefined;
  workspaceId?: string | null | undefined;
  xWorkspaceCode?: string | undefined;
};

export type ListPublicProgramPresentationsResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ListPublicProgramPresentations200Envelope;
};

/** @internal */
export type ListPublicProgramPresentationsRequest$Outbound = {
  program_id: string;
  folder_id?: string | null | undefined;
  cursor?: string | null | undefined;
  limit: number;
  include_archived: boolean;
  workspace_id?: string | null | undefined;
  "X-Workspace-Code"?: string | undefined;
};

/** @internal */
export const ListPublicProgramPresentationsRequest$outboundSchema:
  z.ZodMiniType<
    ListPublicProgramPresentationsRequest$Outbound,
    ListPublicProgramPresentationsRequest
  > = z.pipe(
    z.object({
      programId: z.string(),
      folderId: z.optional(z.nullable(z.string())),
      cursor: z.optional(z.nullable(z.string())),
      limit: z._default(z.int(), 50),
      includeArchived: z._default(z.boolean(), false),
      workspaceId: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        programId: "program_id",
        folderId: "folder_id",
        includeArchived: "include_archived",
        workspaceId: "workspace_id",
        xWorkspaceCode: "X-Workspace-Code",
      });
    }),
  );

export function listPublicProgramPresentationsRequestToJSON(
  listPublicProgramPresentationsRequest: ListPublicProgramPresentationsRequest,
): string {
  return JSON.stringify(
    ListPublicProgramPresentationsRequest$outboundSchema.parse(
      listPublicProgramPresentationsRequest,
    ),
  );
}

/** @internal */
export const ListPublicProgramPresentationsResponse$inboundSchema:
  z.ZodMiniType<ListPublicProgramPresentationsResponse, unknown> = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result: models.ListPublicProgramPresentations200Envelope$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function listPublicProgramPresentationsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListPublicProgramPresentationsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListPublicProgramPresentationsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPublicProgramPresentationsResponse' from JSON`,
  );
}
