/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type PlanPublicWorkflowTemplateApiV2PublicWorkflowsTemplatesPlanPostRequest =
  {
    workspaceId?: string | null | undefined;
    xWorkspaceCode?: string | undefined;
    body: models.PublicFlowTemplatePlanRequest;
  };

export type PlanPublicWorkflowTemplateApiV2PublicWorkflowsTemplatesPlanPostResponse =
  {
    headers: { [k: string]: Array<string> };
    result:
      models.PlanPublicWorkflowTemplateApiV2PublicWorkflowsTemplatesPlanPost200Envelope;
  };

/** @internal */
export type PlanPublicWorkflowTemplateApiV2PublicWorkflowsTemplatesPlanPostRequest$Outbound =
  {
    workspace_id?: string | null | undefined;
    "X-Workspace-Code"?: string | undefined;
    body: models.PublicFlowTemplatePlanRequest$Outbound;
  };

/** @internal */
export const PlanPublicWorkflowTemplateApiV2PublicWorkflowsTemplatesPlanPostRequest$outboundSchema:
  z.ZodMiniType<
    PlanPublicWorkflowTemplateApiV2PublicWorkflowsTemplatesPlanPostRequest$Outbound,
    PlanPublicWorkflowTemplateApiV2PublicWorkflowsTemplatesPlanPostRequest
  > = z.pipe(
    z.object({
      workspaceId: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
      body: models.PublicFlowTemplatePlanRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        workspaceId: "workspace_id",
        xWorkspaceCode: "X-Workspace-Code",
      });
    }),
  );

export function planPublicWorkflowTemplateApiV2PublicWorkflowsTemplatesPlanPostRequestToJSON(
  planPublicWorkflowTemplateApiV2PublicWorkflowsTemplatesPlanPostRequest:
    PlanPublicWorkflowTemplateApiV2PublicWorkflowsTemplatesPlanPostRequest,
): string {
  return JSON.stringify(
    PlanPublicWorkflowTemplateApiV2PublicWorkflowsTemplatesPlanPostRequest$outboundSchema
      .parse(
        planPublicWorkflowTemplateApiV2PublicWorkflowsTemplatesPlanPostRequest,
      ),
  );
}

/** @internal */
export const PlanPublicWorkflowTemplateApiV2PublicWorkflowsTemplatesPlanPostResponse$inboundSchema:
  z.ZodMiniType<
    PlanPublicWorkflowTemplateApiV2PublicWorkflowsTemplatesPlanPostResponse,
    unknown
  > = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result:
        models
          .PlanPublicWorkflowTemplateApiV2PublicWorkflowsTemplatesPlanPost200Envelope$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function planPublicWorkflowTemplateApiV2PublicWorkflowsTemplatesPlanPostResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  PlanPublicWorkflowTemplateApiV2PublicWorkflowsTemplatesPlanPostResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PlanPublicWorkflowTemplateApiV2PublicWorkflowsTemplatesPlanPostResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PlanPublicWorkflowTemplateApiV2PublicWorkflowsTemplatesPlanPostResponse' from JSON`,
  );
}
