/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type PreviewPublicWorkflowCompatApiV2PublicWorkflowRunsPreviewPostRequest =
  {
    workspaceId?: string | null | undefined;
    xWorkspaceCode?: string | undefined;
    body: models.PublicWorkflowRuntimeRequest;
  };

export type PreviewPublicWorkflowCompatApiV2PublicWorkflowRunsPreviewPostResponse =
  {
    headers: { [k: string]: Array<string> };
    result:
      models.PreviewPublicWorkflowCompatApiV2PublicWorkflowRunsPreviewPost200Envelope;
  };

/** @internal */
export type PreviewPublicWorkflowCompatApiV2PublicWorkflowRunsPreviewPostRequest$Outbound =
  {
    workspace_id?: string | null | undefined;
    "X-Workspace-Code"?: string | undefined;
    body: models.PublicWorkflowRuntimeRequest$Outbound;
  };

/** @internal */
export const PreviewPublicWorkflowCompatApiV2PublicWorkflowRunsPreviewPostRequest$outboundSchema:
  z.ZodMiniType<
    PreviewPublicWorkflowCompatApiV2PublicWorkflowRunsPreviewPostRequest$Outbound,
    PreviewPublicWorkflowCompatApiV2PublicWorkflowRunsPreviewPostRequest
  > = z.pipe(
    z.object({
      workspaceId: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
      body: models.PublicWorkflowRuntimeRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        workspaceId: "workspace_id",
        xWorkspaceCode: "X-Workspace-Code",
      });
    }),
  );

export function previewPublicWorkflowCompatApiV2PublicWorkflowRunsPreviewPostRequestToJSON(
  previewPublicWorkflowCompatApiV2PublicWorkflowRunsPreviewPostRequest:
    PreviewPublicWorkflowCompatApiV2PublicWorkflowRunsPreviewPostRequest,
): string {
  return JSON.stringify(
    PreviewPublicWorkflowCompatApiV2PublicWorkflowRunsPreviewPostRequest$outboundSchema
      .parse(
        previewPublicWorkflowCompatApiV2PublicWorkflowRunsPreviewPostRequest,
      ),
  );
}

/** @internal */
export const PreviewPublicWorkflowCompatApiV2PublicWorkflowRunsPreviewPostResponse$inboundSchema:
  z.ZodMiniType<
    PreviewPublicWorkflowCompatApiV2PublicWorkflowRunsPreviewPostResponse,
    unknown
  > = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result:
        models
          .PreviewPublicWorkflowCompatApiV2PublicWorkflowRunsPreviewPost200Envelope$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function previewPublicWorkflowCompatApiV2PublicWorkflowRunsPreviewPostResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  PreviewPublicWorkflowCompatApiV2PublicWorkflowRunsPreviewPostResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PreviewPublicWorkflowCompatApiV2PublicWorkflowRunsPreviewPostResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PreviewPublicWorkflowCompatApiV2PublicWorkflowRunsPreviewPostResponse' from JSON`,
  );
}
