/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ReplacePublicPresentationRequest = {
  presentationId: string;
  workspaceId?: string | null | undefined;
  xWorkspaceCode?: string | undefined;
  body: models.PresentationReplaceRequest;
};

export type ReplacePublicPresentationResponse = {
  headers: { [k: string]: Array<string> };
  result: models.ReplacePublicPresentation200Envelope;
};

/** @internal */
export type ReplacePublicPresentationRequest$Outbound = {
  presentation_id: string;
  workspace_id?: string | null | undefined;
  "X-Workspace-Code"?: string | undefined;
  body: models.PresentationReplaceRequest$Outbound;
};

/** @internal */
export const ReplacePublicPresentationRequest$outboundSchema: z.ZodMiniType<
  ReplacePublicPresentationRequest$Outbound,
  ReplacePublicPresentationRequest
> = z.pipe(
  z.object({
    presentationId: z.string(),
    workspaceId: z.optional(z.nullable(z.string())),
    xWorkspaceCode: z.optional(z.string()),
    body: models.PresentationReplaceRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      presentationId: "presentation_id",
      workspaceId: "workspace_id",
      xWorkspaceCode: "X-Workspace-Code",
    });
  }),
);

export function replacePublicPresentationRequestToJSON(
  replacePublicPresentationRequest: ReplacePublicPresentationRequest,
): string {
  return JSON.stringify(
    ReplacePublicPresentationRequest$outboundSchema.parse(
      replacePublicPresentationRequest,
    ),
  );
}

/** @internal */
export const ReplacePublicPresentationResponse$inboundSchema: z.ZodMiniType<
  ReplacePublicPresentationResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.ReplacePublicPresentation200Envelope$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function replacePublicPresentationResponseFromJSON(
  jsonString: string,
): SafeParseResult<ReplacePublicPresentationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReplacePublicPresentationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReplacePublicPresentationResponse' from JSON`,
  );
}
