/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ResolvePublicWorkflowRecordApiV2PublicWorkflowRunsResolveRecordPostRequest =
  {
    workspaceId?: string | null | undefined;
    xWorkspaceCode?: string | undefined;
    body: models.PublicWorkflowResolveRecordRequest;
  };

export type ResolvePublicWorkflowRecordApiV2PublicWorkflowRunsResolveRecordPostResponse =
  {
    headers: { [k: string]: Array<string> };
    result:
      models.ResolvePublicWorkflowRecordApiV2PublicWorkflowRunsResolveRecordPost200Envelope;
  };

/** @internal */
export type ResolvePublicWorkflowRecordApiV2PublicWorkflowRunsResolveRecordPostRequest$Outbound =
  {
    workspace_id?: string | null | undefined;
    "X-Workspace-Code"?: string | undefined;
    body: models.PublicWorkflowResolveRecordRequest$Outbound;
  };

/** @internal */
export const ResolvePublicWorkflowRecordApiV2PublicWorkflowRunsResolveRecordPostRequest$outboundSchema:
  z.ZodMiniType<
    ResolvePublicWorkflowRecordApiV2PublicWorkflowRunsResolveRecordPostRequest$Outbound,
    ResolvePublicWorkflowRecordApiV2PublicWorkflowRunsResolveRecordPostRequest
  > = z.pipe(
    z.object({
      workspaceId: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
      body: models.PublicWorkflowResolveRecordRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        workspaceId: "workspace_id",
        xWorkspaceCode: "X-Workspace-Code",
      });
    }),
  );

export function resolvePublicWorkflowRecordApiV2PublicWorkflowRunsResolveRecordPostRequestToJSON(
  resolvePublicWorkflowRecordApiV2PublicWorkflowRunsResolveRecordPostRequest:
    ResolvePublicWorkflowRecordApiV2PublicWorkflowRunsResolveRecordPostRequest,
): string {
  return JSON.stringify(
    ResolvePublicWorkflowRecordApiV2PublicWorkflowRunsResolveRecordPostRequest$outboundSchema
      .parse(
        resolvePublicWorkflowRecordApiV2PublicWorkflowRunsResolveRecordPostRequest,
      ),
  );
}

/** @internal */
export const ResolvePublicWorkflowRecordApiV2PublicWorkflowRunsResolveRecordPostResponse$inboundSchema:
  z.ZodMiniType<
    ResolvePublicWorkflowRecordApiV2PublicWorkflowRunsResolveRecordPostResponse,
    unknown
  > = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result:
        models
          .ResolvePublicWorkflowRecordApiV2PublicWorkflowRunsResolveRecordPost200Envelope$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function resolvePublicWorkflowRecordApiV2PublicWorkflowRunsResolveRecordPostResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ResolvePublicWorkflowRecordApiV2PublicWorkflowRunsResolveRecordPostResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ResolvePublicWorkflowRecordApiV2PublicWorkflowRunsResolveRecordPostResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ResolvePublicWorkflowRecordApiV2PublicWorkflowRunsResolveRecordPostResponse' from JSON`,
  );
}
