/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type StartPublicWorkflowCompatApiV2PublicWorkflowRunsStartPostRequest = {
  workspaceId?: string | null | undefined;
  xWorkspaceCode?: string | undefined;
  body: models.PublicWorkflowRuntimeRequest;
};

export type StartPublicWorkflowCompatApiV2PublicWorkflowRunsStartPostResponse =
  {
    headers: { [k: string]: Array<string> };
    result:
      models.StartPublicWorkflowCompatApiV2PublicWorkflowRunsStartPost200Envelope;
  };

/** @internal */
export type StartPublicWorkflowCompatApiV2PublicWorkflowRunsStartPostRequest$Outbound =
  {
    workspace_id?: string | null | undefined;
    "X-Workspace-Code"?: string | undefined;
    body: models.PublicWorkflowRuntimeRequest$Outbound;
  };

/** @internal */
export const StartPublicWorkflowCompatApiV2PublicWorkflowRunsStartPostRequest$outboundSchema:
  z.ZodMiniType<
    StartPublicWorkflowCompatApiV2PublicWorkflowRunsStartPostRequest$Outbound,
    StartPublicWorkflowCompatApiV2PublicWorkflowRunsStartPostRequest
  > = z.pipe(
    z.object({
      workspaceId: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
      body: models.PublicWorkflowRuntimeRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        workspaceId: "workspace_id",
        xWorkspaceCode: "X-Workspace-Code",
      });
    }),
  );

export function startPublicWorkflowCompatApiV2PublicWorkflowRunsStartPostRequestToJSON(
  startPublicWorkflowCompatApiV2PublicWorkflowRunsStartPostRequest:
    StartPublicWorkflowCompatApiV2PublicWorkflowRunsStartPostRequest,
): string {
  return JSON.stringify(
    StartPublicWorkflowCompatApiV2PublicWorkflowRunsStartPostRequest$outboundSchema
      .parse(startPublicWorkflowCompatApiV2PublicWorkflowRunsStartPostRequest),
  );
}

/** @internal */
export const StartPublicWorkflowCompatApiV2PublicWorkflowRunsStartPostResponse$inboundSchema:
  z.ZodMiniType<
    StartPublicWorkflowCompatApiV2PublicWorkflowRunsStartPostResponse,
    unknown
  > = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result:
        models
          .StartPublicWorkflowCompatApiV2PublicWorkflowRunsStartPost200Envelope$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function startPublicWorkflowCompatApiV2PublicWorkflowRunsStartPostResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  StartPublicWorkflowCompatApiV2PublicWorkflowRunsStartPostResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      StartPublicWorkflowCompatApiV2PublicWorkflowRunsStartPostResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'StartPublicWorkflowCompatApiV2PublicWorkflowRunsStartPostResponse' from JSON`,
  );
}
