/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type StartPublicMoneyforwardInvoiceExportApiV2PublicInvoicesExportsMoneyforwardPostRequest =
  {
    workspaceId?: string | null | undefined;
    xWorkspaceCode?: string | undefined;
    body: { [k: string]: any };
  };

export type StartPublicMoneyforwardInvoiceExportApiV2PublicInvoicesExportsMoneyforwardPostResponse =
  {
    headers: { [k: string]: Array<string> };
    result:
      models.StartPublicMoneyforwardInvoiceExportApiV2PublicInvoicesExportsMoneyforwardPost200Envelope;
  };

/** @internal */
export type StartPublicMoneyforwardInvoiceExportApiV2PublicInvoicesExportsMoneyforwardPostRequest$Outbound =
  {
    workspace_id?: string | null | undefined;
    "X-Workspace-Code"?: string | undefined;
    body: { [k: string]: any };
  };

/** @internal */
export const StartPublicMoneyforwardInvoiceExportApiV2PublicInvoicesExportsMoneyforwardPostRequest$outboundSchema:
  z.ZodMiniType<
    StartPublicMoneyforwardInvoiceExportApiV2PublicInvoicesExportsMoneyforwardPostRequest$Outbound,
    StartPublicMoneyforwardInvoiceExportApiV2PublicInvoicesExportsMoneyforwardPostRequest
  > = z.pipe(
    z.object({
      workspaceId: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
      body: z.record(z.string(), z.any()),
    }),
    z.transform((v) => {
      return remap$(v, {
        workspaceId: "workspace_id",
        xWorkspaceCode: "X-Workspace-Code",
      });
    }),
  );

export function startPublicMoneyforwardInvoiceExportApiV2PublicInvoicesExportsMoneyforwardPostRequestToJSON(
  startPublicMoneyforwardInvoiceExportApiV2PublicInvoicesExportsMoneyforwardPostRequest:
    StartPublicMoneyforwardInvoiceExportApiV2PublicInvoicesExportsMoneyforwardPostRequest,
): string {
  return JSON.stringify(
    StartPublicMoneyforwardInvoiceExportApiV2PublicInvoicesExportsMoneyforwardPostRequest$outboundSchema
      .parse(
        startPublicMoneyforwardInvoiceExportApiV2PublicInvoicesExportsMoneyforwardPostRequest,
      ),
  );
}

/** @internal */
export const StartPublicMoneyforwardInvoiceExportApiV2PublicInvoicesExportsMoneyforwardPostResponse$inboundSchema:
  z.ZodMiniType<
    StartPublicMoneyforwardInvoiceExportApiV2PublicInvoicesExportsMoneyforwardPostResponse,
    unknown
  > = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result:
        models
          .StartPublicMoneyforwardInvoiceExportApiV2PublicInvoicesExportsMoneyforwardPost200Envelope$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function startPublicMoneyforwardInvoiceExportApiV2PublicInvoicesExportsMoneyforwardPostResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  StartPublicMoneyforwardInvoiceExportApiV2PublicInvoicesExportsMoneyforwardPostResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      StartPublicMoneyforwardInvoiceExportApiV2PublicInvoicesExportsMoneyforwardPostResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'StartPublicMoneyforwardInvoiceExportApiV2PublicInvoicesExportsMoneyforwardPostResponse' from JSON`,
  );
}
