/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type SwitchPublicAuthMcpSessionWorkspaceApiV2PublicAuthMcpSessionSwitchWorkspacePostRequest =
  {
    workspaceId?: string | null | undefined;
    xSankaMCPSessionID?: string | null | undefined;
    xWorkspaceCode?: string | undefined;
    body: models.AuthWorkspaceSwitchRequest;
  };

export type SwitchPublicAuthMcpSessionWorkspaceApiV2PublicAuthMcpSessionSwitchWorkspacePostResponse =
  {
    headers: { [k: string]: Array<string> };
    result:
      models.SwitchPublicAuthMcpSessionWorkspaceApiV2PublicAuthMcpSessionSwitchWorkspacePost200Envelope;
  };

/** @internal */
export type SwitchPublicAuthMcpSessionWorkspaceApiV2PublicAuthMcpSessionSwitchWorkspacePostRequest$Outbound =
  {
    workspace_id?: string | null | undefined;
    "X-Sanka-MCP-Session-ID"?: string | null | undefined;
    "X-Workspace-Code"?: string | undefined;
    body: models.AuthWorkspaceSwitchRequest$Outbound;
  };

/** @internal */
export const SwitchPublicAuthMcpSessionWorkspaceApiV2PublicAuthMcpSessionSwitchWorkspacePostRequest$outboundSchema:
  z.ZodMiniType<
    SwitchPublicAuthMcpSessionWorkspaceApiV2PublicAuthMcpSessionSwitchWorkspacePostRequest$Outbound,
    SwitchPublicAuthMcpSessionWorkspaceApiV2PublicAuthMcpSessionSwitchWorkspacePostRequest
  > = z.pipe(
    z.object({
      workspaceId: z.optional(z.nullable(z.string())),
      xSankaMCPSessionID: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
      body: models.AuthWorkspaceSwitchRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        workspaceId: "workspace_id",
        xSankaMCPSessionID: "X-Sanka-MCP-Session-ID",
        xWorkspaceCode: "X-Workspace-Code",
      });
    }),
  );

export function switchPublicAuthMcpSessionWorkspaceApiV2PublicAuthMcpSessionSwitchWorkspacePostRequestToJSON(
  switchPublicAuthMcpSessionWorkspaceApiV2PublicAuthMcpSessionSwitchWorkspacePostRequest:
    SwitchPublicAuthMcpSessionWorkspaceApiV2PublicAuthMcpSessionSwitchWorkspacePostRequest,
): string {
  return JSON.stringify(
    SwitchPublicAuthMcpSessionWorkspaceApiV2PublicAuthMcpSessionSwitchWorkspacePostRequest$outboundSchema
      .parse(
        switchPublicAuthMcpSessionWorkspaceApiV2PublicAuthMcpSessionSwitchWorkspacePostRequest,
      ),
  );
}

/** @internal */
export const SwitchPublicAuthMcpSessionWorkspaceApiV2PublicAuthMcpSessionSwitchWorkspacePostResponse$inboundSchema:
  z.ZodMiniType<
    SwitchPublicAuthMcpSessionWorkspaceApiV2PublicAuthMcpSessionSwitchWorkspacePostResponse,
    unknown
  > = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result:
        models
          .SwitchPublicAuthMcpSessionWorkspaceApiV2PublicAuthMcpSessionSwitchWorkspacePost200Envelope$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function switchPublicAuthMcpSessionWorkspaceApiV2PublicAuthMcpSessionSwitchWorkspacePostResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  SwitchPublicAuthMcpSessionWorkspaceApiV2PublicAuthMcpSessionSwitchWorkspacePostResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      SwitchPublicAuthMcpSessionWorkspaceApiV2PublicAuthMcpSessionSwitchWorkspacePostResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'SwitchPublicAuthMcpSessionWorkspaceApiV2PublicAuthMcpSessionSwitchWorkspacePostResponse' from JSON`,
  );
}
