/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type UpdatePublicDealPipelineApiV2PublicDealsPipelinesPipelineIdPatchRequest =
  {
    pipelineId: string;
    workspaceId?: string | null | undefined;
    xWorkspaceCode?: string | undefined;
    body: models.DealPipelineUpdateRequest;
  };

export type UpdatePublicDealPipelineApiV2PublicDealsPipelinesPipelineIdPatchResponse =
  {
    headers: { [k: string]: Array<string> };
    result:
      models.UpdatePublicDealPipelineApiV2PublicDealsPipelinesPipelineIdPatch200Envelope;
  };

/** @internal */
export type UpdatePublicDealPipelineApiV2PublicDealsPipelinesPipelineIdPatchRequest$Outbound =
  {
    pipeline_id: string;
    workspace_id?: string | null | undefined;
    "X-Workspace-Code"?: string | undefined;
    body: models.DealPipelineUpdateRequest$Outbound;
  };

/** @internal */
export const UpdatePublicDealPipelineApiV2PublicDealsPipelinesPipelineIdPatchRequest$outboundSchema:
  z.ZodMiniType<
    UpdatePublicDealPipelineApiV2PublicDealsPipelinesPipelineIdPatchRequest$Outbound,
    UpdatePublicDealPipelineApiV2PublicDealsPipelinesPipelineIdPatchRequest
  > = z.pipe(
    z.object({
      pipelineId: z.string(),
      workspaceId: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
      body: models.DealPipelineUpdateRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        pipelineId: "pipeline_id",
        workspaceId: "workspace_id",
        xWorkspaceCode: "X-Workspace-Code",
      });
    }),
  );

export function updatePublicDealPipelineApiV2PublicDealsPipelinesPipelineIdPatchRequestToJSON(
  updatePublicDealPipelineApiV2PublicDealsPipelinesPipelineIdPatchRequest:
    UpdatePublicDealPipelineApiV2PublicDealsPipelinesPipelineIdPatchRequest,
): string {
  return JSON.stringify(
    UpdatePublicDealPipelineApiV2PublicDealsPipelinesPipelineIdPatchRequest$outboundSchema
      .parse(
        updatePublicDealPipelineApiV2PublicDealsPipelinesPipelineIdPatchRequest,
      ),
  );
}

/** @internal */
export const UpdatePublicDealPipelineApiV2PublicDealsPipelinesPipelineIdPatchResponse$inboundSchema:
  z.ZodMiniType<
    UpdatePublicDealPipelineApiV2PublicDealsPipelinesPipelineIdPatchResponse,
    unknown
  > = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result:
        models
          .UpdatePublicDealPipelineApiV2PublicDealsPipelinesPipelineIdPatch200Envelope$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function updatePublicDealPipelineApiV2PublicDealsPipelinesPipelineIdPatchResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  UpdatePublicDealPipelineApiV2PublicDealsPipelinesPipelineIdPatchResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      UpdatePublicDealPipelineApiV2PublicDealsPipelinesPipelineIdPatchResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'UpdatePublicDealPipelineApiV2PublicDealsPipelinesPipelineIdPatchResponse' from JSON`,
  );
}
