/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type UpdatePublicWorkflowApiV2PublicWorkflowsWorkflowIdPatchRequest = {
  workflowId: string;
  workspaceId?: string | null | undefined;
  xWorkspaceCode?: string | undefined;
  body: models.PublicWorkflowMutationRequest;
};

export type UpdatePublicWorkflowApiV2PublicWorkflowsWorkflowIdPatchResponse = {
  headers: { [k: string]: Array<string> };
  result:
    models.UpdatePublicWorkflowApiV2PublicWorkflowsWorkflowIdPatch200Envelope;
};

/** @internal */
export type UpdatePublicWorkflowApiV2PublicWorkflowsWorkflowIdPatchRequest$Outbound =
  {
    workflow_id: string;
    workspace_id?: string | null | undefined;
    "X-Workspace-Code"?: string | undefined;
    body: models.PublicWorkflowMutationRequest$Outbound;
  };

/** @internal */
export const UpdatePublicWorkflowApiV2PublicWorkflowsWorkflowIdPatchRequest$outboundSchema:
  z.ZodMiniType<
    UpdatePublicWorkflowApiV2PublicWorkflowsWorkflowIdPatchRequest$Outbound,
    UpdatePublicWorkflowApiV2PublicWorkflowsWorkflowIdPatchRequest
  > = z.pipe(
    z.object({
      workflowId: z.string(),
      workspaceId: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
      body: models.PublicWorkflowMutationRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        workflowId: "workflow_id",
        workspaceId: "workspace_id",
        xWorkspaceCode: "X-Workspace-Code",
      });
    }),
  );

export function updatePublicWorkflowApiV2PublicWorkflowsWorkflowIdPatchRequestToJSON(
  updatePublicWorkflowApiV2PublicWorkflowsWorkflowIdPatchRequest:
    UpdatePublicWorkflowApiV2PublicWorkflowsWorkflowIdPatchRequest,
): string {
  return JSON.stringify(
    UpdatePublicWorkflowApiV2PublicWorkflowsWorkflowIdPatchRequest$outboundSchema
      .parse(updatePublicWorkflowApiV2PublicWorkflowsWorkflowIdPatchRequest),
  );
}

/** @internal */
export const UpdatePublicWorkflowApiV2PublicWorkflowsWorkflowIdPatchResponse$inboundSchema:
  z.ZodMiniType<
    UpdatePublicWorkflowApiV2PublicWorkflowsWorkflowIdPatchResponse,
    unknown
  > = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result:
        models
          .UpdatePublicWorkflowApiV2PublicWorkflowsWorkflowIdPatch200Envelope$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function updatePublicWorkflowApiV2PublicWorkflowsWorkflowIdPatchResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  UpdatePublicWorkflowApiV2PublicWorkflowsWorkflowIdPatchResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      UpdatePublicWorkflowApiV2PublicWorkflowsWorkflowIdPatchResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'UpdatePublicWorkflowApiV2PublicWorkflowsWorkflowIdPatchResponse' from JSON`,
  );
}
