/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type UpdatePublicProjectApiV2PublicProjectsProjectIdPutRequest = {
  projectId: string;
  xWorkspaceCode?: string | undefined;
  xLanguage?: string | null | undefined;
  acceptLanguage?: string | null | undefined;
  body: models.PublicProjectRequest;
};

export type UpdatePublicProjectApiV2PublicProjectsProjectIdPutResponse = {
  headers: { [k: string]: Array<string> };
  result: models.UpdatePublicProjectApiV2PublicProjectsProjectIdPut200Envelope;
};

/** @internal */
export type UpdatePublicProjectApiV2PublicProjectsProjectIdPutRequest$Outbound =
  {
    project_id: string;
    "X-Workspace-Code"?: string | undefined;
    "X-Language"?: string | null | undefined;
    "Accept-Language"?: string | null | undefined;
    body: models.PublicProjectRequest$Outbound;
  };

/** @internal */
export const UpdatePublicProjectApiV2PublicProjectsProjectIdPutRequest$outboundSchema:
  z.ZodMiniType<
    UpdatePublicProjectApiV2PublicProjectsProjectIdPutRequest$Outbound,
    UpdatePublicProjectApiV2PublicProjectsProjectIdPutRequest
  > = z.pipe(
    z.object({
      projectId: z.string(),
      xWorkspaceCode: z.optional(z.string()),
      xLanguage: z.optional(z.nullable(z.string())),
      acceptLanguage: z.optional(z.nullable(z.string())),
      body: models.PublicProjectRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        projectId: "project_id",
        xWorkspaceCode: "X-Workspace-Code",
        xLanguage: "X-Language",
        acceptLanguage: "Accept-Language",
      });
    }),
  );

export function updatePublicProjectApiV2PublicProjectsProjectIdPutRequestToJSON(
  updatePublicProjectApiV2PublicProjectsProjectIdPutRequest:
    UpdatePublicProjectApiV2PublicProjectsProjectIdPutRequest,
): string {
  return JSON.stringify(
    UpdatePublicProjectApiV2PublicProjectsProjectIdPutRequest$outboundSchema
      .parse(updatePublicProjectApiV2PublicProjectsProjectIdPutRequest),
  );
}

/** @internal */
export const UpdatePublicProjectApiV2PublicProjectsProjectIdPutResponse$inboundSchema:
  z.ZodMiniType<
    UpdatePublicProjectApiV2PublicProjectsProjectIdPutResponse,
    unknown
  > = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result:
        models
          .UpdatePublicProjectApiV2PublicProjectsProjectIdPut200Envelope$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function updatePublicProjectApiV2PublicProjectsProjectIdPutResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  UpdatePublicProjectApiV2PublicProjectsProjectIdPutResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      UpdatePublicProjectApiV2PublicProjectsProjectIdPutResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'UpdatePublicProjectApiV2PublicProjectsProjectIdPutResponse' from JSON`,
  );
}
