/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type UpdatePublicInventoryTransactionApiV2PublicInventoryTransactionsTransactionIdPutRequest =
  {
    transactionId: string;
    workspaceId?: string | null | undefined;
    xWorkspaceCode?: string | undefined;
    body: models.PublicObjectRecordMutationRequest;
  };

export type UpdatePublicInventoryTransactionApiV2PublicInventoryTransactionsTransactionIdPutResponse =
  {
    headers: { [k: string]: Array<string> };
    result:
      models.UpdatePublicInventoryTransactionApiV2PublicInventoryTransactionsTransactionIdPut200Envelope;
  };

/** @internal */
export type UpdatePublicInventoryTransactionApiV2PublicInventoryTransactionsTransactionIdPutRequest$Outbound =
  {
    transaction_id: string;
    workspace_id?: string | null | undefined;
    "X-Workspace-Code"?: string | undefined;
    body: models.PublicObjectRecordMutationRequest$Outbound;
  };

/** @internal */
export const UpdatePublicInventoryTransactionApiV2PublicInventoryTransactionsTransactionIdPutRequest$outboundSchema:
  z.ZodMiniType<
    UpdatePublicInventoryTransactionApiV2PublicInventoryTransactionsTransactionIdPutRequest$Outbound,
    UpdatePublicInventoryTransactionApiV2PublicInventoryTransactionsTransactionIdPutRequest
  > = z.pipe(
    z.object({
      transactionId: z.string(),
      workspaceId: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
      body: models.PublicObjectRecordMutationRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        transactionId: "transaction_id",
        workspaceId: "workspace_id",
        xWorkspaceCode: "X-Workspace-Code",
      });
    }),
  );

export function updatePublicInventoryTransactionApiV2PublicInventoryTransactionsTransactionIdPutRequestToJSON(
  updatePublicInventoryTransactionApiV2PublicInventoryTransactionsTransactionIdPutRequest:
    UpdatePublicInventoryTransactionApiV2PublicInventoryTransactionsTransactionIdPutRequest,
): string {
  return JSON.stringify(
    UpdatePublicInventoryTransactionApiV2PublicInventoryTransactionsTransactionIdPutRequest$outboundSchema
      .parse(
        updatePublicInventoryTransactionApiV2PublicInventoryTransactionsTransactionIdPutRequest,
      ),
  );
}

/** @internal */
export const UpdatePublicInventoryTransactionApiV2PublicInventoryTransactionsTransactionIdPutResponse$inboundSchema:
  z.ZodMiniType<
    UpdatePublicInventoryTransactionApiV2PublicInventoryTransactionsTransactionIdPutResponse,
    unknown
  > = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result:
        models
          .UpdatePublicInventoryTransactionApiV2PublicInventoryTransactionsTransactionIdPut200Envelope$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function updatePublicInventoryTransactionApiV2PublicInventoryTransactionsTransactionIdPutResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  UpdatePublicInventoryTransactionApiV2PublicInventoryTransactionsTransactionIdPutResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      UpdatePublicInventoryTransactionApiV2PublicInventoryTransactionsTransactionIdPutResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'UpdatePublicInventoryTransactionApiV2PublicInventoryTransactionsTransactionIdPutResponse' from JSON`,
  );
}
