/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type UploadPublicExpenseFileApiV2PublicExpensesFilesPostRequest = {
  workspaceId?: string | null | undefined;
  xWorkspaceCode?: string | undefined;
  body: models.BodyUploadPublicExpenseFileApiV2PublicExpensesFilesPost;
};

export type UploadPublicExpenseFileApiV2PublicExpensesFilesPostResponse = {
  headers: { [k: string]: Array<string> };
  result: models.UploadPublicExpenseFileApiV2PublicExpensesFilesPost200Envelope;
};

/** @internal */
export type UploadPublicExpenseFileApiV2PublicExpensesFilesPostRequest$Outbound =
  {
    workspace_id?: string | null | undefined;
    "X-Workspace-Code"?: string | undefined;
    body:
      models.BodyUploadPublicExpenseFileApiV2PublicExpensesFilesPost$Outbound;
  };

/** @internal */
export const UploadPublicExpenseFileApiV2PublicExpensesFilesPostRequest$outboundSchema:
  z.ZodMiniType<
    UploadPublicExpenseFileApiV2PublicExpensesFilesPostRequest$Outbound,
    UploadPublicExpenseFileApiV2PublicExpensesFilesPostRequest
  > = z.pipe(
    z.object({
      workspaceId: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
      body:
        models
          .BodyUploadPublicExpenseFileApiV2PublicExpensesFilesPost$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        workspaceId: "workspace_id",
        xWorkspaceCode: "X-Workspace-Code",
      });
    }),
  );

export function uploadPublicExpenseFileApiV2PublicExpensesFilesPostRequestToJSON(
  uploadPublicExpenseFileApiV2PublicExpensesFilesPostRequest:
    UploadPublicExpenseFileApiV2PublicExpensesFilesPostRequest,
): string {
  return JSON.stringify(
    UploadPublicExpenseFileApiV2PublicExpensesFilesPostRequest$outboundSchema
      .parse(uploadPublicExpenseFileApiV2PublicExpensesFilesPostRequest),
  );
}

/** @internal */
export const UploadPublicExpenseFileApiV2PublicExpensesFilesPostResponse$inboundSchema:
  z.ZodMiniType<
    UploadPublicExpenseFileApiV2PublicExpensesFilesPostResponse,
    unknown
  > = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result:
        models
          .UploadPublicExpenseFileApiV2PublicExpensesFilesPost200Envelope$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function uploadPublicExpenseFileApiV2PublicExpensesFilesPostResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  UploadPublicExpenseFileApiV2PublicExpensesFilesPostResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      UploadPublicExpenseFileApiV2PublicExpensesFilesPostResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'UploadPublicExpenseFileApiV2PublicExpensesFilesPostResponse' from JSON`,
  );
}
