/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type UpsertPublicPayrollProfileApiV2PublicPayrollProfilesPostRequest = {
  workspaceId?: string | null | undefined;
  xWorkspaceCode?: string | undefined;
  body: models.PayrollProfileUpsertRequest;
};

export type UpsertPublicPayrollProfileApiV2PublicPayrollProfilesPostResponse = {
  headers: { [k: string]: Array<string> };
  result:
    models.UpsertPublicPayrollProfileApiV2PublicPayrollProfilesPost200Envelope;
};

/** @internal */
export type UpsertPublicPayrollProfileApiV2PublicPayrollProfilesPostRequest$Outbound =
  {
    workspace_id?: string | null | undefined;
    "X-Workspace-Code"?: string | undefined;
    body: models.PayrollProfileUpsertRequest$Outbound;
  };

/** @internal */
export const UpsertPublicPayrollProfileApiV2PublicPayrollProfilesPostRequest$outboundSchema:
  z.ZodMiniType<
    UpsertPublicPayrollProfileApiV2PublicPayrollProfilesPostRequest$Outbound,
    UpsertPublicPayrollProfileApiV2PublicPayrollProfilesPostRequest
  > = z.pipe(
    z.object({
      workspaceId: z.optional(z.nullable(z.string())),
      xWorkspaceCode: z.optional(z.string()),
      body: models.PayrollProfileUpsertRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        workspaceId: "workspace_id",
        xWorkspaceCode: "X-Workspace-Code",
      });
    }),
  );

export function upsertPublicPayrollProfileApiV2PublicPayrollProfilesPostRequestToJSON(
  upsertPublicPayrollProfileApiV2PublicPayrollProfilesPostRequest:
    UpsertPublicPayrollProfileApiV2PublicPayrollProfilesPostRequest,
): string {
  return JSON.stringify(
    UpsertPublicPayrollProfileApiV2PublicPayrollProfilesPostRequest$outboundSchema
      .parse(upsertPublicPayrollProfileApiV2PublicPayrollProfilesPostRequest),
  );
}

/** @internal */
export const UpsertPublicPayrollProfileApiV2PublicPayrollProfilesPostResponse$inboundSchema:
  z.ZodMiniType<
    UpsertPublicPayrollProfileApiV2PublicPayrollProfilesPostResponse,
    unknown
  > = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result:
        models
          .UpsertPublicPayrollProfileApiV2PublicPayrollProfilesPost200Envelope$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function upsertPublicPayrollProfileApiV2PublicPayrollProfilesPostResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  UpsertPublicPayrollProfileApiV2PublicPayrollProfilesPostResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      UpsertPublicPayrollProfileApiV2PublicPayrollProfilesPostResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'UpsertPublicPayrollProfileApiV2PublicPayrollProfilesPostResponse' from JSON`,
  );
}
