/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ActivityLogActor = {
  name?: string | null | undefined;
};

/** @internal */
export const ActivityLogActor$inboundSchema: z.ZodMiniType<
  ActivityLogActor,
  unknown
> = z.object({
  name: z.optional(z.nullable(types.string())),
});

export function activityLogActorFromJSON(
  jsonString: string,
): SafeParseResult<ActivityLogActor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActivityLogActor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActivityLogActor' from JSON`,
  );
}
