/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ActivityLogActor,
  ActivityLogActor$inboundSchema,
} from "./activity-log-actor.js";
import {
  ActivityLogEnvironment,
  ActivityLogEnvironment$inboundSchema,
} from "./activity-log-environment.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ActivityLogItem = {
  id: string;
  displayId?: string | null | undefined;
  action?: string | null | undefined;
  target?: string | null | undefined;
  objectType?: string | null | undefined;
  objectId?: string | null | undefined;
  objectDisplay?: string | null | undefined;
  fieldName?: string | null | undefined;
  oldValue?: any | undefined;
  newValue?: any | undefined;
  actionUid?: string | null | undefined;
  actor?: ActivityLogActor | null | undefined;
  environment?: ActivityLogEnvironment | null | undefined;
  governanceExecutionId?: string | null | undefined;
  createdAt?: string | null | undefined;
};

/** @internal */
export const ActivityLogItem$inboundSchema: z.ZodMiniType<
  ActivityLogItem,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    display_id: z.optional(z.nullable(types.string())),
    action: z.optional(z.nullable(types.string())),
    target: z.optional(z.nullable(types.string())),
    object_type: z.optional(z.nullable(types.string())),
    object_id: z.optional(z.nullable(types.string())),
    object_display: z.optional(z.nullable(types.string())),
    field_name: z.optional(z.nullable(types.string())),
    old_value: types.optional(z.any()),
    new_value: types.optional(z.any()),
    action_uid: z.optional(z.nullable(types.string())),
    actor: z.optional(z.nullable(ActivityLogActor$inboundSchema)),
    environment: z.optional(z.nullable(ActivityLogEnvironment$inboundSchema)),
    governance_execution_id: z.optional(z.nullable(types.string())),
    created_at: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "display_id": "displayId",
      "object_type": "objectType",
      "object_id": "objectId",
      "object_display": "objectDisplay",
      "field_name": "fieldName",
      "old_value": "oldValue",
      "new_value": "newValue",
      "action_uid": "actionUid",
      "governance_execution_id": "governanceExecutionId",
      "created_at": "createdAt",
    });
  }),
);

export function activityLogItemFromJSON(
  jsonString: string,
): SafeParseResult<ActivityLogItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActivityLogItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActivityLogItem' from JSON`,
  );
}
