/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { EnvelopeMeta, EnvelopeMeta$inboundSchema } from "./envelope-meta.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  ObjectRecordBulkActionData,
  ObjectRecordBulkActionData$inboundSchema,
} from "./object-record-bulk-action-data.js";

export type BulkUpdatePublicInvoicesApiV2PublicInvoicesBulkUpdatePost200Envelope =
  {
    success: true;
    data: ObjectRecordBulkActionData;
    meta: EnvelopeMeta;
  };

/** @internal */
export const BulkUpdatePublicInvoicesApiV2PublicInvoicesBulkUpdatePost200Envelope$inboundSchema:
  z.ZodMiniType<
    BulkUpdatePublicInvoicesApiV2PublicInvoicesBulkUpdatePost200Envelope,
    unknown
  > = z.object({
    success: types.literal(true),
    data: ObjectRecordBulkActionData$inboundSchema,
    meta: EnvelopeMeta$inboundSchema,
  });

export function bulkUpdatePublicInvoicesApiV2PublicInvoicesBulkUpdatePost200EnvelopeFromJSON(
  jsonString: string,
): SafeParseResult<
  BulkUpdatePublicInvoicesApiV2PublicInvoicesBulkUpdatePost200Envelope,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      BulkUpdatePublicInvoicesApiV2PublicInvoicesBulkUpdatePost200Envelope$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'BulkUpdatePublicInvoicesApiV2PublicInvoicesBulkUpdatePost200Envelope' from JSON`,
  );
}
