/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smart-union.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type MeterId = string | number;

export type CommerceMeterSchema = {
  id?: string | null | undefined;
  meterId?: string | number | null | undefined;
  contactId?: string | null | undefined;
  companyId?: string | null | undefined;
  itemId?: string | null | undefined;
  subscriptionId?: string | null | undefined;
  usage?: number | null | undefined;
  usageStatus?: string | null | undefined;
  usageAt?: Date | null | undefined;
  createdAt: Date;
  updatedAt: Date;
  contactName?: string | null | undefined;
  companyName?: string | null | undefined;
  itemName?: string | null | undefined;
  subscriptionName?: string | null | undefined;
};

/** @internal */
export const MeterId$inboundSchema: z.ZodMiniType<MeterId, unknown> =
  smartUnion([types.string(), types.number()]);

export function meterIdFromJSON(
  jsonString: string,
): SafeParseResult<MeterId, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MeterId$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MeterId' from JSON`,
  );
}

/** @internal */
export const CommerceMeterSchema$inboundSchema: z.ZodMiniType<
  CommerceMeterSchema,
  unknown
> = z.pipe(
  z.object({
    id: z.optional(z.nullable(types.string())),
    meter_id: z.optional(
      z.nullable(smartUnion([types.string(), types.number()])),
    ),
    contact_id: z.optional(z.nullable(types.string())),
    company_id: z.optional(z.nullable(types.string())),
    item_id: z.optional(z.nullable(types.string())),
    subscription_id: z.optional(z.nullable(types.string())),
    usage: z.optional(z.nullable(types.number())),
    usage_status: z.optional(z.nullable(types.string())),
    usage_at: z.optional(z.nullable(types.date())),
    created_at: types.date(),
    updated_at: types.date(),
    contact_name: z.optional(z.nullable(types.string())),
    company_name: z.optional(z.nullable(types.string())),
    item_name: z.optional(z.nullable(types.string())),
    subscription_name: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "meter_id": "meterId",
      "contact_id": "contactId",
      "company_id": "companyId",
      "item_id": "itemId",
      "subscription_id": "subscriptionId",
      "usage_status": "usageStatus",
      "usage_at": "usageAt",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
      "contact_name": "contactName",
      "company_name": "companyName",
      "item_name": "itemName",
      "subscription_name": "subscriptionName",
    });
  }),
);

export function commerceMeterSchemaFromJSON(
  jsonString: string,
): SafeParseResult<CommerceMeterSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CommerceMeterSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CommerceMeterSchema' from JSON`,
  );
}
