/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { EnvelopeMeta, EnvelopeMeta$inboundSchema } from "./envelope-meta.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PresentationData,
  PresentationData$inboundSchema,
} from "./presentation-data.js";

export type CreatePublicProgramPresentation201Envelope = {
  success: true;
  data: PresentationData;
  meta: EnvelopeMeta;
};

/** @internal */
export const CreatePublicProgramPresentation201Envelope$inboundSchema:
  z.ZodMiniType<CreatePublicProgramPresentation201Envelope, unknown> = z.object(
    {
      success: types.literal(true),
      data: PresentationData$inboundSchema,
      meta: EnvelopeMeta$inboundSchema,
    },
  );

export function createPublicProgramPresentation201EnvelopeFromJSON(
  jsonString: string,
): SafeParseResult<
  CreatePublicProgramPresentation201Envelope,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CreatePublicProgramPresentation201Envelope$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'CreatePublicProgramPresentation201Envelope' from JSON`,
  );
}
