/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { EnvelopeMeta, EnvelopeMeta$inboundSchema } from "./envelope-meta.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  WorkforcePositionData,
  WorkforcePositionData$inboundSchema,
} from "./workforce-position-data.js";

export type CreatePublicWorkforcePosition200Envelope = {
  success: true;
  data: WorkforcePositionData;
  meta: EnvelopeMeta;
};

/** @internal */
export const CreatePublicWorkforcePosition200Envelope$inboundSchema:
  z.ZodMiniType<CreatePublicWorkforcePosition200Envelope, unknown> = z.object({
    success: types.literal(true),
    data: WorkforcePositionData$inboundSchema,
    meta: EnvelopeMeta$inboundSchema,
  });

export function createPublicWorkforcePosition200EnvelopeFromJSON(
  jsonString: string,
): SafeParseResult<
  CreatePublicWorkforcePosition200Envelope,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CreatePublicWorkforcePosition200Envelope$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'CreatePublicWorkforcePosition200Envelope' from JSON`,
  );
}
