/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type DeckFooter = {
  pageNumbers: boolean;
  text: string;
};

/** @internal */
export const DeckFooter$inboundSchema: z.ZodMiniType<DeckFooter, unknown> = z
  .object({
    pageNumbers: z._default(types.boolean(), true),
    text: z._default(types.string(), ""),
  });

export function deckFooterFromJSON(
  jsonString: string,
): SafeParseResult<DeckFooter, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeckFooter$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeckFooter' from JSON`,
  );
}
