/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { EnvelopeMeta, EnvelopeMeta$inboundSchema } from "./envelope-meta.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PublicProjectDeleteData,
  PublicProjectDeleteData$inboundSchema,
} from "./public-project-delete-data.js";

export type DeletePublicProjectApiV2PublicProjectsProjectIdDelete200Envelope = {
  success: true;
  data: PublicProjectDeleteData;
  meta: EnvelopeMeta;
};

/** @internal */
export const DeletePublicProjectApiV2PublicProjectsProjectIdDelete200Envelope$inboundSchema:
  z.ZodMiniType<
    DeletePublicProjectApiV2PublicProjectsProjectIdDelete200Envelope,
    unknown
  > = z.object({
    success: types.literal(true),
    data: PublicProjectDeleteData$inboundSchema,
    meta: EnvelopeMeta$inboundSchema,
  });

export function deletePublicProjectApiV2PublicProjectsProjectIdDelete200EnvelopeFromJSON(
  jsonString: string,
): SafeParseResult<
  DeletePublicProjectApiV2PublicProjectsProjectIdDelete200Envelope,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeletePublicProjectApiV2PublicProjectsProjectIdDelete200Envelope$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'DeletePublicProjectApiV2PublicProjectsProjectIdDelete200Envelope' from JSON`,
  );
}
