/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  DeveloperCloudFleetData,
  DeveloperCloudFleetData$inboundSchema,
} from "./developer-cloud-fleet-data.js";
import { EnvelopeMeta, EnvelopeMeta$inboundSchema } from "./envelope-meta.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type DeveloperCloudCancelFleetApiV2MigrateCloudFleetsFleetIdCancelPost200Envelope =
  {
    success: true;
    data: DeveloperCloudFleetData;
    meta: EnvelopeMeta;
  };

/** @internal */
export const DeveloperCloudCancelFleetApiV2MigrateCloudFleetsFleetIdCancelPost200Envelope$inboundSchema:
  z.ZodMiniType<
    DeveloperCloudCancelFleetApiV2MigrateCloudFleetsFleetIdCancelPost200Envelope,
    unknown
  > = z.object({
    success: types.literal(true),
    data: DeveloperCloudFleetData$inboundSchema,
    meta: EnvelopeMeta$inboundSchema,
  });

export function developerCloudCancelFleetApiV2MigrateCloudFleetsFleetIdCancelPost200EnvelopeFromJSON(
  jsonString: string,
): SafeParseResult<
  DeveloperCloudCancelFleetApiV2MigrateCloudFleetsFleetIdCancelPost200Envelope,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeveloperCloudCancelFleetApiV2MigrateCloudFleetsFleetIdCancelPost200Envelope$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'DeveloperCloudCancelFleetApiV2MigrateCloudFleetsFleetIdCancelPost200Envelope' from JSON`,
  );
}
