/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  DeveloperCloudCloudRunData,
  DeveloperCloudCloudRunData$inboundSchema,
} from "./developer-cloud-cloud-run-data.js";
import { EnvelopeMeta, EnvelopeMeta$inboundSchema } from "./envelope-meta.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type DeveloperCloudGetCloudRunApiV2MigrateCloudRunsRunIdGet200Envelope =
  {
    success: true;
    data: DeveloperCloudCloudRunData;
    meta: EnvelopeMeta;
  };

/** @internal */
export const DeveloperCloudGetCloudRunApiV2MigrateCloudRunsRunIdGet200Envelope$inboundSchema:
  z.ZodMiniType<
    DeveloperCloudGetCloudRunApiV2MigrateCloudRunsRunIdGet200Envelope,
    unknown
  > = z.object({
    success: types.literal(true),
    data: DeveloperCloudCloudRunData$inboundSchema,
    meta: EnvelopeMeta$inboundSchema,
  });

export function developerCloudGetCloudRunApiV2MigrateCloudRunsRunIdGet200EnvelopeFromJSON(
  jsonString: string,
): SafeParseResult<
  DeveloperCloudGetCloudRunApiV2MigrateCloudRunsRunIdGet200Envelope,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeveloperCloudGetCloudRunApiV2MigrateCloudRunsRunIdGet200Envelope$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'DeveloperCloudGetCloudRunApiV2MigrateCloudRunsRunIdGet200Envelope' from JSON`,
  );
}
