/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  DeveloperCloudCloudEventData,
  DeveloperCloudCloudEventData$inboundSchema,
} from "./developer-cloud-cloud-event-data.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type DeveloperCloudCloudEventListData = {
  events: Array<DeveloperCloudCloudEventData>;
  nextCursor?: number | null | undefined;
};

/** @internal */
export const DeveloperCloudCloudEventListData$inboundSchema: z.ZodMiniType<
  DeveloperCloudCloudEventListData,
  unknown
> = z.pipe(
  z.object({
    events: z.array(DeveloperCloudCloudEventData$inboundSchema),
    next_cursor: z.optional(z.nullable(types.number())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "next_cursor": "nextCursor",
    });
  }),
);

export function developerCloudCloudEventListDataFromJSON(
  jsonString: string,
): SafeParseResult<DeveloperCloudCloudEventListData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeveloperCloudCloudEventListData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeveloperCloudCloudEventListData' from JSON`,
  );
}
