/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { EnvelopeMeta, EnvelopeMeta$inboundSchema } from "./envelope-meta.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type DeveloperCloudDownloadCloudArtifactApiV2MigrateCloudRunsRunIdArtifactsNameGet200Envelope =
  {
    success: true;
    data: any;
    meta: EnvelopeMeta;
  };

/** @internal */
export const DeveloperCloudDownloadCloudArtifactApiV2MigrateCloudRunsRunIdArtifactsNameGet200Envelope$inboundSchema:
  z.ZodMiniType<
    DeveloperCloudDownloadCloudArtifactApiV2MigrateCloudRunsRunIdArtifactsNameGet200Envelope,
    unknown
  > = z.object({
    success: types.literal(true),
    data: z.any(),
    meta: EnvelopeMeta$inboundSchema,
  });

export function developerCloudDownloadCloudArtifactApiV2MigrateCloudRunsRunIdArtifactsNameGet200EnvelopeFromJSON(
  jsonString: string,
): SafeParseResult<
  DeveloperCloudDownloadCloudArtifactApiV2MigrateCloudRunsRunIdArtifactsNameGet200Envelope,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeveloperCloudDownloadCloudArtifactApiV2MigrateCloudRunsRunIdArtifactsNameGet200Envelope$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'DeveloperCloudDownloadCloudArtifactApiV2MigrateCloudRunsRunIdArtifactsNameGet200Envelope' from JSON`,
  );
}
