/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  DeveloperCloudCloudArtifactListData,
  DeveloperCloudCloudArtifactListData$inboundSchema,
} from "./developer-cloud-cloud-artifact-list-data.js";
import { EnvelopeMeta, EnvelopeMeta$inboundSchema } from "./envelope-meta.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type DeveloperCloudCloudRunArtifactsApiV2MigrateCloudRunsRunIdArtifactsGet200Envelope =
  {
    success: true;
    data: DeveloperCloudCloudArtifactListData;
    meta: EnvelopeMeta;
  };

/** @internal */
export const DeveloperCloudCloudRunArtifactsApiV2MigrateCloudRunsRunIdArtifactsGet200Envelope$inboundSchema:
  z.ZodMiniType<
    DeveloperCloudCloudRunArtifactsApiV2MigrateCloudRunsRunIdArtifactsGet200Envelope,
    unknown
  > = z.object({
    success: types.literal(true),
    data: DeveloperCloudCloudArtifactListData$inboundSchema,
    meta: EnvelopeMeta$inboundSchema,
  });

export function developerCloudCloudRunArtifactsApiV2MigrateCloudRunsRunIdArtifactsGet200EnvelopeFromJSON(
  jsonString: string,
): SafeParseResult<
  DeveloperCloudCloudRunArtifactsApiV2MigrateCloudRunsRunIdArtifactsGet200Envelope,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeveloperCloudCloudRunArtifactsApiV2MigrateCloudRunsRunIdArtifactsGet200Envelope$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'DeveloperCloudCloudRunArtifactsApiV2MigrateCloudRunsRunIdArtifactsGet200Envelope' from JSON`,
  );
}
