/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  DeveloperCloudCloudReceiptData,
  DeveloperCloudCloudReceiptData$inboundSchema,
} from "./developer-cloud-cloud-receipt-data.js";
import {
  DeveloperCloudCloudRunData,
  DeveloperCloudCloudRunData$inboundSchema,
} from "./developer-cloud-cloud-run-data.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type DeveloperCloudFleetItemData = {
  key: string;
  repository: string;
  revision: string;
  waitingForCapacity: boolean;
  run: DeveloperCloudCloudRunData;
  receipt?: DeveloperCloudCloudReceiptData | null | undefined;
  retriedRunId?: string | null | undefined;
};

/** @internal */
export const DeveloperCloudFleetItemData$inboundSchema: z.ZodMiniType<
  DeveloperCloudFleetItemData,
  unknown
> = z.pipe(
  z.object({
    key: types.string(),
    repository: types.string(),
    revision: types.string(),
    waiting_for_capacity: types.boolean(),
    run: DeveloperCloudCloudRunData$inboundSchema,
    receipt: z.optional(
      z.nullable(DeveloperCloudCloudReceiptData$inboundSchema),
    ),
    retried_run_id: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "waiting_for_capacity": "waitingForCapacity",
      "retried_run_id": "retriedRunId",
    });
  }),
);

export function developerCloudFleetItemDataFromJSON(
  jsonString: string,
): SafeParseResult<DeveloperCloudFleetItemData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeveloperCloudFleetItemData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeveloperCloudFleetItemData' from JSON`,
  );
}
