/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type DividerBlock = {
  type: "divider";
  id?: string | null | undefined;
};

/** @internal */
export const DividerBlock$inboundSchema: z.ZodMiniType<DividerBlock, unknown> =
  z.object({
    type: types.literal("divider"),
    id: z.optional(z.nullable(types.string())),
  });

export function dividerBlockFromJSON(
  jsonString: string,
): SafeParseResult<DividerBlock, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DividerBlock$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DividerBlock' from JSON`,
  );
}
