/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { EnvelopeMeta, EnvelopeMeta$inboundSchema } from "./envelope-meta.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type DownloadPublicPayrollPayslipPdfApiV2PublicPayrollRunsRunIdPayslipsPdfGet200Envelope =
  {
    success: true;
    data: any;
    meta: EnvelopeMeta;
  };

/** @internal */
export const DownloadPublicPayrollPayslipPdfApiV2PublicPayrollRunsRunIdPayslipsPdfGet200Envelope$inboundSchema:
  z.ZodMiniType<
    DownloadPublicPayrollPayslipPdfApiV2PublicPayrollRunsRunIdPayslipsPdfGet200Envelope,
    unknown
  > = z.object({
    success: types.literal(true),
    data: z.any(),
    meta: EnvelopeMeta$inboundSchema,
  });

export function downloadPublicPayrollPayslipPdfApiV2PublicPayrollRunsRunIdPayslipsPdfGet200EnvelopeFromJSON(
  jsonString: string,
): SafeParseResult<
  DownloadPublicPayrollPayslipPdfApiV2PublicPayrollRunsRunIdPayslipsPdfGet200Envelope,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DownloadPublicPayrollPayslipPdfApiV2PublicPayrollRunsRunIdPayslipsPdfGet200Envelope$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'DownloadPublicPayrollPayslipPdfApiV2PublicPayrollRunsRunIdPayslipsPdfGet200Envelope' from JSON`,
  );
}
