/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type EnrichCompanySeed = {
  name?: string | null | undefined;
  url?: string | null | undefined;
  externalId?: string | null | undefined;
};

/** @internal */
export type EnrichCompanySeed$Outbound = {
  name?: string | null | undefined;
  url?: string | null | undefined;
  external_id?: string | null | undefined;
};

/** @internal */
export const EnrichCompanySeed$outboundSchema: z.ZodMiniType<
  EnrichCompanySeed$Outbound,
  EnrichCompanySeed
> = z.pipe(
  z.object({
    name: z.optional(z.nullable(z.string())),
    url: z.optional(z.nullable(z.string())),
    externalId: z.optional(z.nullable(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      externalId: "external_id",
    });
  }),
);

export function enrichCompanySeedToJSON(
  enrichCompanySeed: EnrichCompanySeed,
): string {
  return JSON.stringify(
    EnrichCompanySeed$outboundSchema.parse(enrichCompanySeed),
  );
}
