/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  EnrichCompanySeed,
  EnrichCompanySeed$Outbound,
  EnrichCompanySeed$outboundSchema,
} from "./enrich-company-seed.js";

export type EnrichRequest = {
  objectType: string;
  recordId?: string | null | undefined;
  seed?: EnrichCompanySeed | undefined;
  customFieldMap?: { [k: string]: string } | undefined;
  dryRun?: boolean | undefined;
  forceRefresh?: boolean | undefined;
};

/** @internal */
export type EnrichRequest$Outbound = {
  object_type: string;
  record_id?: string | null | undefined;
  seed?: EnrichCompanySeed$Outbound | undefined;
  custom_field_map?: { [k: string]: string } | undefined;
  dry_run: boolean;
  force_refresh: boolean;
};

/** @internal */
export const EnrichRequest$outboundSchema: z.ZodMiniType<
  EnrichRequest$Outbound,
  EnrichRequest
> = z.pipe(
  z.object({
    objectType: z.string(),
    recordId: z.optional(z.nullable(z.string())),
    seed: z.optional(EnrichCompanySeed$outboundSchema),
    customFieldMap: z.optional(z.record(z.string(), z.string())),
    dryRun: z._default(z.boolean(), false),
    forceRefresh: z._default(z.boolean(), false),
  }),
  z.transform((v) => {
    return remap$(v, {
      objectType: "object_type",
      recordId: "record_id",
      customFieldMap: "custom_field_map",
      dryRun: "dry_run",
      forceRefresh: "force_refresh",
    });
  }),
);

export function enrichRequestToJSON(enrichRequest: EnrichRequest): string {
  return JSON.stringify(EnrichRequest$outboundSchema.parse(enrichRequest));
}
