/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const FerryProgramTodoStatus = {
  NotStarted: "not_started",
  InProgress: "in_progress",
  Completed: "completed",
  Blocked: "blocked",
} as const;
export type FerryProgramTodoStatus = OpenEnum<typeof FerryProgramTodoStatus>;

export const FerryProgramTodoPriority = {
  P0: "P0",
  P1: "P1",
  P2: "P2",
  P3: "P3",
  P4: "P4",
} as const;
export type FerryProgramTodoPriority = OpenEnum<
  typeof FerryProgramTodoPriority
>;

export type FerryProgramTodo = {
  id: string;
  title: string;
  titleJa?: string | null | undefined;
  description: string;
  descriptionJa?: string | null | undefined;
  category: string;
  required: boolean;
  status: FerryProgramTodoStatus;
  notes?: string | null | undefined;
  startDate?: string | null | undefined;
  dueDate?: string | null | undefined;
  priority: FerryProgramTodoPriority;
  sourceRef?: string | null | undefined;
  phaseId?: string | null | undefined;
  parentTodoId?: string | null | undefined;
  sortOrder?: number | null | undefined;
};

/** @internal */
export const FerryProgramTodoStatus$inboundSchema: z.ZodMiniType<
  FerryProgramTodoStatus,
  unknown
> = openEnums.inboundSchema(FerryProgramTodoStatus);

/** @internal */
export const FerryProgramTodoPriority$inboundSchema: z.ZodMiniType<
  FerryProgramTodoPriority,
  unknown
> = openEnums.inboundSchema(FerryProgramTodoPriority);

/** @internal */
export const FerryProgramTodo$inboundSchema: z.ZodMiniType<
  FerryProgramTodo,
  unknown
> = z.object({
  id: types.string(),
  title: types.string(),
  titleJa: z.optional(z.nullable(types.string())),
  description: z._default(types.string(), ""),
  descriptionJa: z.optional(z.nullable(types.string())),
  category: z._default(types.string(), "planning"),
  required: z._default(types.boolean(), true),
  status: z._default(FerryProgramTodoStatus$inboundSchema, "not_started"),
  notes: z.optional(z.nullable(types.string())),
  startDate: z.optional(z.nullable(types.string())),
  dueDate: z.optional(z.nullable(types.string())),
  priority: z._default(FerryProgramTodoPriority$inboundSchema, "P2"),
  sourceRef: z.optional(z.nullable(types.string())),
  phaseId: z.optional(z.nullable(types.string())),
  parentTodoId: z.optional(z.nullable(types.string())),
  sortOrder: z.optional(z.nullable(types.number())),
});

export function ferryProgramTodoFromJSON(
  jsonString: string,
): SafeParseResult<FerryProgramTodo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FerryProgramTodo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FerryProgramTodo' from JSON`,
  );
}
