/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type FerryDiagramViewport = {
  x?: number | undefined;
  y?: number | undefined;
  zoom?: number | undefined;
};

/** @internal */
export const FerryDiagramViewport$inboundSchema: z.ZodMiniType<
  FerryDiagramViewport,
  unknown
> = z.object({
  x: z._default(types.number(), 0),
  y: z._default(types.number(), 0),
  zoom: z._default(types.number(), 1),
});
/** @internal */
export type FerryDiagramViewport$Outbound = {
  x: number;
  y: number;
  zoom: number;
};

/** @internal */
export const FerryDiagramViewport$outboundSchema: z.ZodMiniType<
  FerryDiagramViewport$Outbound,
  FerryDiagramViewport
> = z.object({
  x: z._default(z.number(), 0),
  y: z._default(z.number(), 0),
  zoom: z._default(z.number(), 1),
});

export function ferryDiagramViewportToJSON(
  ferryDiagramViewport: FerryDiagramViewport,
): string {
  return JSON.stringify(
    FerryDiagramViewport$outboundSchema.parse(ferryDiagramViewport),
  );
}
export function ferryDiagramViewportFromJSON(
  jsonString: string,
): SafeParseResult<FerryDiagramViewport, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FerryDiagramViewport$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FerryDiagramViewport' from JSON`,
  );
}
