/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  FerryProgramData,
  FerryProgramData$inboundSchema,
} from "./ferry-program-data.js";

export type FerryProgramTodoBatchUpsertData = {
  program: FerryProgramData;
  createdCount: number;
  updatedCount: number;
};

/** @internal */
export const FerryProgramTodoBatchUpsertData$inboundSchema: z.ZodMiniType<
  FerryProgramTodoBatchUpsertData,
  unknown
> = z.object({
  program: FerryProgramData$inboundSchema,
  createdCount: types.number(),
  updatedCount: types.number(),
});

export function ferryProgramTodoBatchUpsertDataFromJSON(
  jsonString: string,
): SafeParseResult<FerryProgramTodoBatchUpsertData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FerryProgramTodoBatchUpsertData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FerryProgramTodoBatchUpsertData' from JSON`,
  );
}
