/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  FerryDiagramSummary,
  FerryDiagramSummary$inboundSchema,
} from "./ferry-diagram-summary.js";

export type FerryDiagramListData = {
  diagrams: Array<FerryDiagramSummary>;
  count: number;
};

/** @internal */
export const FerryDiagramListData$inboundSchema: z.ZodMiniType<
  FerryDiagramListData,
  unknown
> = z.object({
  diagrams: z.array(FerryDiagramSummary$inboundSchema),
  count: types.number(),
});

export function ferryDiagramListDataFromJSON(
  jsonString: string,
): SafeParseResult<FerryDiagramListData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FerryDiagramListData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FerryDiagramListData' from JSON`,
  );
}
