/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { EnvelopeMeta, EnvelopeMeta$inboundSchema } from "./envelope-meta.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const AuthMode = {
  DeveloperApiToken: "developer_api_token",
  OauthApp: "oauth_app",
} as const;
export type AuthMode = OpenEnum<typeof AuthMode>;

export type PublicDeveloperWhoamiData = {
  userId: string;
  username?: string | null | undefined;
  email?: string | null | undefined;
  workspaceId?: string | null | undefined;
  workspaceCode?: string | null | undefined;
  workspaceName?: string | null | undefined;
  authMode: AuthMode;
  principalKey: string;
  tokenId?: string | null | undefined;
  tokenName?: string | null | undefined;
  permissionLevel?: string | null | undefined;
  permissions?: Array<string> | undefined;
  scopes?: Array<string> | undefined;
  oauthAppId?: string | null | undefined;
  expiresAt?: Date | null | undefined;
  message: string;
  [additionalProperties: string]: unknown;
};

export type GetPublicAuthWhoamiApiV2PublicAuthWhoamiGet200Envelope = {
  success: true;
  data: PublicDeveloperWhoamiData;
  meta: EnvelopeMeta;
};

/** @internal */
export const AuthMode$inboundSchema: z.ZodMiniType<AuthMode, unknown> =
  openEnums.inboundSchema(AuthMode);

/** @internal */
export const PublicDeveloperWhoamiData$inboundSchema: z.ZodMiniType<
  PublicDeveloperWhoamiData,
  unknown
> = z.pipe(
  z.catchall(
    z.object({
      user_id: types.string(),
      username: z.optional(z.nullable(types.string())),
      email: z.optional(z.nullable(types.string())),
      workspace_id: z.optional(z.nullable(types.string())),
      workspace_code: z.optional(z.nullable(types.string())),
      workspace_name: z.optional(z.nullable(types.string())),
      auth_mode: AuthMode$inboundSchema,
      principal_key: types.string(),
      token_id: z.optional(z.nullable(types.string())),
      token_name: z.optional(z.nullable(types.string())),
      permission_level: z.optional(z.nullable(types.string())),
      permissions: types.optional(z.array(types.string())),
      scopes: types.optional(z.array(types.string())),
      oauth_app_id: z.optional(z.nullable(types.string())),
      expires_at: z.optional(z.nullable(types.date())),
      message: z._default(types.string(), "OK"),
    }),
    z.any(),
  ),
  z.transform((v) => {
    return remap$(v, {
      "user_id": "userId",
      "workspace_id": "workspaceId",
      "workspace_code": "workspaceCode",
      "workspace_name": "workspaceName",
      "auth_mode": "authMode",
      "principal_key": "principalKey",
      "token_id": "tokenId",
      "token_name": "tokenName",
      "permission_level": "permissionLevel",
      "oauth_app_id": "oauthAppId",
      "expires_at": "expiresAt",
    });
  }),
);

export function publicDeveloperWhoamiDataFromJSON(
  jsonString: string,
): SafeParseResult<PublicDeveloperWhoamiData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PublicDeveloperWhoamiData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PublicDeveloperWhoamiData' from JSON`,
  );
}

/** @internal */
export const GetPublicAuthWhoamiApiV2PublicAuthWhoamiGet200Envelope$inboundSchema:
  z.ZodMiniType<
    GetPublicAuthWhoamiApiV2PublicAuthWhoamiGet200Envelope,
    unknown
  > = z.object({
    success: types.literal(true),
    data: z.lazy(() => PublicDeveloperWhoamiData$inboundSchema),
    meta: EnvelopeMeta$inboundSchema,
  });

export function getPublicAuthWhoamiApiV2PublicAuthWhoamiGet200EnvelopeFromJSON(
  jsonString: string,
): SafeParseResult<
  GetPublicAuthWhoamiApiV2PublicAuthWhoamiGet200Envelope,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetPublicAuthWhoamiApiV2PublicAuthWhoamiGet200Envelope$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetPublicAuthWhoamiApiV2PublicAuthWhoamiGet200Envelope' from JSON`,
  );
}
