/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { EnvelopeMeta, EnvelopeMeta$inboundSchema } from "./envelope-meta.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type GetPublicLockRuleOptionsApiV2PublicLockRulesOptionsGet200Envelope =
  {
    success: true;
    data: { [k: string]: any };
    meta: EnvelopeMeta;
  };

/** @internal */
export const GetPublicLockRuleOptionsApiV2PublicLockRulesOptionsGet200Envelope$inboundSchema:
  z.ZodMiniType<
    GetPublicLockRuleOptionsApiV2PublicLockRulesOptionsGet200Envelope,
    unknown
  > = z.object({
    success: types.literal(true),
    data: z.record(z.string(), z.any()),
    meta: EnvelopeMeta$inboundSchema,
  });

export function getPublicLockRuleOptionsApiV2PublicLockRulesOptionsGet200EnvelopeFromJSON(
  jsonString: string,
): SafeParseResult<
  GetPublicLockRuleOptionsApiV2PublicLockRulesOptionsGet200Envelope,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetPublicLockRuleOptionsApiV2PublicLockRulesOptionsGet200Envelope$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetPublicLockRuleOptionsApiV2PublicLockRulesOptionsGet200Envelope' from JSON`,
  );
}
