/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { EnvelopeMeta, EnvelopeMeta$inboundSchema } from "./envelope-meta.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  ObjectRecordData,
  ObjectRecordData$inboundSchema,
} from "./object-record-data.js";

export type GetPublicMeterApiV2PublicMetersMeterIdGet200Envelope = {
  success: true;
  data: ObjectRecordData;
  meta: EnvelopeMeta;
};

/** @internal */
export const GetPublicMeterApiV2PublicMetersMeterIdGet200Envelope$inboundSchema:
  z.ZodMiniType<GetPublicMeterApiV2PublicMetersMeterIdGet200Envelope, unknown> =
    z.object({
      success: types.literal(true),
      data: ObjectRecordData$inboundSchema,
      meta: EnvelopeMeta$inboundSchema,
    });

export function getPublicMeterApiV2PublicMetersMeterIdGet200EnvelopeFromJSON(
  jsonString: string,
): SafeParseResult<
  GetPublicMeterApiV2PublicMetersMeterIdGet200Envelope,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetPublicMeterApiV2PublicMetersMeterIdGet200Envelope$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetPublicMeterApiV2PublicMetersMeterIdGet200Envelope' from JSON`,
  );
}
