/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { EnvelopeMeta, EnvelopeMeta$inboundSchema } from "./envelope-meta.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  GoalProgressData,
  GoalProgressData$inboundSchema,
} from "./goal-progress-data.js";

export type GetPublicGoalProgress200Envelope = {
  success: true;
  data: GoalProgressData;
  meta: EnvelopeMeta;
};

/** @internal */
export const GetPublicGoalProgress200Envelope$inboundSchema: z.ZodMiniType<
  GetPublicGoalProgress200Envelope,
  unknown
> = z.object({
  success: types.literal(true),
  data: GoalProgressData$inboundSchema,
  meta: EnvelopeMeta$inboundSchema,
});

export function getPublicGoalProgress200EnvelopeFromJSON(
  jsonString: string,
): SafeParseResult<GetPublicGoalProgress200Envelope, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPublicGoalProgress200Envelope$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPublicGoalProgress200Envelope' from JSON`,
  );
}
