/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { EnvelopeMeta, EnvelopeMeta$inboundSchema } from "./envelope-meta.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PresentationData,
  PresentationData$inboundSchema,
} from "./presentation-data.js";

export type GetPublicProgramPresentation200Envelope = {
  success: true;
  data: PresentationData;
  meta: EnvelopeMeta;
};

/** @internal */
export const GetPublicProgramPresentation200Envelope$inboundSchema:
  z.ZodMiniType<GetPublicProgramPresentation200Envelope, unknown> = z.object({
    success: types.literal(true),
    data: PresentationData$inboundSchema,
    meta: EnvelopeMeta$inboundSchema,
  });

export function getPublicProgramPresentation200EnvelopeFromJSON(
  jsonString: string,
): SafeParseResult<
  GetPublicProgramPresentation200Envelope,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetPublicProgramPresentation200Envelope$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetPublicProgramPresentation200Envelope' from JSON`,
  );
}
