/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const Key = {
  Month: "month",
  Quarter: "quarter",
  Half: "half",
  Year: "year",
} as const;
export type Key = OpenEnum<typeof Key>;

export type GoalPeriodProgress = {
  key: Key;
  start: Date;
  end: Date;
  actual: string;
  target: string | null;
  expected: string | null;
};

/** @internal */
export const Key$inboundSchema: z.ZodMiniType<Key, unknown> = openEnums
  .inboundSchema(Key);

/** @internal */
export const GoalPeriodProgress$inboundSchema: z.ZodMiniType<
  GoalPeriodProgress,
  unknown
> = z.object({
  key: Key$inboundSchema,
  start: types.date(),
  end: types.date(),
  actual: types.string(),
  target: types.nullable(types.string()),
  expected: types.nullable(types.string()),
});

export function goalPeriodProgressFromJSON(
  jsonString: string,
): SafeParseResult<GoalPeriodProgress, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GoalPeriodProgress$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GoalPeriodProgress' from JSON`,
  );
}
