/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { smartUnion } from "../types/smart-union.js";

export type Target = number | string;

export type GoalTargetCell = {
  ownerId?: number | null | undefined;
  month: Date;
  target?: number | string | null | undefined;
};

/** @internal */
export type Target$Outbound = number | string;

/** @internal */
export const Target$outboundSchema: z.ZodMiniType<Target$Outbound, Target> =
  smartUnion([z.number(), z.string()]);

export function targetToJSON(target: Target): string {
  return JSON.stringify(Target$outboundSchema.parse(target));
}

/** @internal */
export type GoalTargetCell$Outbound = {
  owner_id?: number | null | undefined;
  month: string;
  target?: number | string | null | undefined;
};

/** @internal */
export const GoalTargetCell$outboundSchema: z.ZodMiniType<
  GoalTargetCell$Outbound,
  GoalTargetCell
> = z.pipe(
  z.object({
    ownerId: z.optional(z.nullable(z.int())),
    month: z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    ),
    target: z.optional(z.nullable(smartUnion([z.number(), z.string()]))),
  }),
  z.transform((v) => {
    return remap$(v, {
      ownerId: "owner_id",
    });
  }),
);

export function goalTargetCellToJSON(goalTargetCell: GoalTargetCell): string {
  return JSON.stringify(GoalTargetCell$outboundSchema.parse(goalTargetCell));
}
