/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { GoalData, GoalData$inboundSchema } from "./goal-data.js";
import {
  GoalPeriodProgress,
  GoalPeriodProgress$inboundSchema,
} from "./goal-period-progress.js";

export type GoalListItem = {
  goal: GoalData;
  thisMonth: GoalPeriodProgress;
};

/** @internal */
export const GoalListItem$inboundSchema: z.ZodMiniType<GoalListItem, unknown> =
  z.pipe(
    z.object({
      goal: GoalData$inboundSchema,
      this_month: GoalPeriodProgress$inboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        "this_month": "thisMonth",
      });
    }),
  );

export function goalListItemFromJSON(
  jsonString: string,
): SafeParseResult<GoalListItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GoalListItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GoalListItem' from JSON`,
  );
}
