/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  GoalSourceOption,
  GoalSourceOption$inboundSchema,
} from "./goal-source-option.js";
import { GoalTemplate, GoalTemplate$inboundSchema } from "./goal-template.js";

export type GoalMetricCatalog = {
  templates: Array<GoalTemplate>;
  sources: Array<GoalSourceOption>;
};

/** @internal */
export const GoalMetricCatalog$inboundSchema: z.ZodMiniType<
  GoalMetricCatalog,
  unknown
> = z.object({
  templates: z.array(GoalTemplate$inboundSchema),
  sources: z.array(GoalSourceOption$inboundSchema),
});

export function goalMetricCatalogFromJSON(
  jsonString: string,
): SafeParseResult<GoalMetricCatalog, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GoalMetricCatalog$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GoalMetricCatalog' from JSON`,
  );
}
