/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { GoalData, GoalData$inboundSchema } from "./goal-data.js";
import {
  GoalMonthPoint,
  GoalMonthPoint$inboundSchema,
} from "./goal-month-point.js";
import { GoalOwner, GoalOwner$inboundSchema } from "./goal-owner.js";
import {
  GoalPeriodProgress,
  GoalPeriodProgress$inboundSchema,
} from "./goal-period-progress.js";
import {
  GoalPersonProgress,
  GoalPersonProgress$inboundSchema,
} from "./goal-person-progress.js";

export const PeoplePeriod = {
  Month: "month",
  Quarter: "quarter",
  Half: "half",
  Year: "year",
} as const;
export type PeoplePeriod = OpenEnum<typeof PeoplePeriod>;

export type GoalProgressData = {
  goal: GoalData;
  subject: string;
  owner: GoalOwner | null;
  asOf: Date;
  fiscalYear: number;
  months: Array<GoalMonthPoint>;
  periods: Array<GoalPeriodProgress>;
  peoplePeriod?: PeoplePeriod | null | undefined;
  people?: Array<GoalPersonProgress> | undefined;
  excludedRecords: number;
};

/** @internal */
export const PeoplePeriod$inboundSchema: z.ZodMiniType<PeoplePeriod, unknown> =
  openEnums.inboundSchema(PeoplePeriod);

/** @internal */
export const GoalProgressData$inboundSchema: z.ZodMiniType<
  GoalProgressData,
  unknown
> = z.pipe(
  z.object({
    goal: GoalData$inboundSchema,
    subject: types.string(),
    owner: types.nullable(GoalOwner$inboundSchema),
    as_of: types.date(),
    fiscal_year: types.number(),
    months: z.array(GoalMonthPoint$inboundSchema),
    periods: z.array(GoalPeriodProgress$inboundSchema),
    people_period: z.optional(z.nullable(PeoplePeriod$inboundSchema)),
    people: types.optional(z.array(GoalPersonProgress$inboundSchema)),
    excluded_records: z._default(types.number(), 0),
  }),
  z.transform((v) => {
    return remap$(v, {
      "as_of": "asOf",
      "fiscal_year": "fiscalYear",
      "people_period": "peoplePeriod",
      "excluded_records": "excludedRecords",
    });
  }),
);

export function goalProgressDataFromJSON(
  jsonString: string,
): SafeParseResult<GoalProgressData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GoalProgressData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GoalProgressData' from JSON`,
  );
}
