/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const Level = {
  One: 1,
  Two: 2,
  Three: 3,
} as const;
export type Level = OpenEnum<typeof Level>;

export type HeadingBlock = {
  type: "heading";
  id?: string | null | undefined;
  level: Level;
  text: string;
  kicker?: string | null | undefined;
};

/** @internal */
export const Level$inboundSchema: z.ZodMiniType<Level, unknown> = openEnums
  .inboundSchemaInt(Level);

/** @internal */
export const HeadingBlock$inboundSchema: z.ZodMiniType<HeadingBlock, unknown> =
  z.object({
    type: types.literal("heading"),
    id: z.optional(z.nullable(types.string())),
    level: z._default(Level$inboundSchema, 1),
    text: types.string(),
    kicker: z.optional(z.nullable(types.string())),
  });

export function headingBlockFromJSON(
  jsonString: string,
): SafeParseResult<HeadingBlock, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => HeadingBlock$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'HeadingBlock' from JSON`,
  );
}
