/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  TransferColumnMapping,
  TransferColumnMapping$Outbound,
  TransferColumnMapping$outboundSchema,
} from "./transfer-column-mapping.js";

export type ImportJobCreateRequest = {
  objectType: string;
  sourceKind?: string | undefined;
  fileFormat?: string | undefined;
  fileId?: string | null | undefined;
  customObjectId?: string | null | undefined;
  provider?: string | null | undefined;
  channelId?: string | null | undefined;
  recordIds?: Array<string> | null | undefined;
  /**
   * Provider-specific source metadata. For Stripe invoice/subscription backfills, use scope=all with optional days_ago, created_gte, and limit; bounded synchronous backfills support up to 200 records.
   */
  sourceRecord?: { [k: string]: any } | null | undefined;
  operation?: string | undefined;
  mappingMode?: string | undefined;
  keyField?: string | null | undefined;
  relationKeyMap?: { [k: string]: string } | undefined;
  columnMappings?: Array<TransferColumnMapping> | undefined;
  dryRun?: boolean | undefined;
};

/** @internal */
export type ImportJobCreateRequest$Outbound = {
  object_type: string;
  source_kind: string;
  file_format: string;
  file_id?: string | null | undefined;
  custom_object_id?: string | null | undefined;
  provider?: string | null | undefined;
  channel_id?: string | null | undefined;
  record_ids?: Array<string> | null | undefined;
  source_record?: { [k: string]: any } | null | undefined;
  operation: string;
  mapping_mode: string;
  key_field?: string | null | undefined;
  relation_key_map?: { [k: string]: string } | undefined;
  column_mappings?: Array<TransferColumnMapping$Outbound> | undefined;
  dry_run: boolean;
};

/** @internal */
export const ImportJobCreateRequest$outboundSchema: z.ZodMiniType<
  ImportJobCreateRequest$Outbound,
  ImportJobCreateRequest
> = z.pipe(
  z.object({
    objectType: z.string(),
    sourceKind: z._default(z.string(), "file"),
    fileFormat: z._default(z.string(), "csv"),
    fileId: z.optional(z.nullable(z.string())),
    customObjectId: z.optional(z.nullable(z.string())),
    provider: z.optional(z.nullable(z.string())),
    channelId: z.optional(z.nullable(z.string())),
    recordIds: z.optional(z.nullable(z.array(z.string()))),
    sourceRecord: z.optional(z.nullable(z.record(z.string(), z.any()))),
    operation: z._default(z.string(), "upsert"),
    mappingMode: z._default(z.string(), "auto"),
    keyField: z.optional(z.nullable(z.string())),
    relationKeyMap: z.optional(z.record(z.string(), z.string())),
    columnMappings: z.optional(z.array(TransferColumnMapping$outboundSchema)),
    dryRun: z._default(z.boolean(), false),
  }),
  z.transform((v) => {
    return remap$(v, {
      objectType: "object_type",
      sourceKind: "source_kind",
      fileFormat: "file_format",
      fileId: "file_id",
      customObjectId: "custom_object_id",
      channelId: "channel_id",
      recordIds: "record_ids",
      sourceRecord: "source_record",
      mappingMode: "mapping_mode",
      keyField: "key_field",
      relationKeyMap: "relation_key_map",
      columnMappings: "column_mappings",
      dryRun: "dry_run",
    });
  }),
);

export function importJobCreateRequestToJSON(
  importJobCreateRequest: ImportJobCreateRequest,
): string {
  return JSON.stringify(
    ImportJobCreateRequest$outboundSchema.parse(importJobCreateRequest),
  );
}
