/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { EnvelopeMeta, EnvelopeMeta$inboundSchema } from "./envelope-meta.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PresentationImageData,
  PresentationImageData$inboundSchema,
} from "./presentation-image-data.js";

export type ImportPublicPresentationImage201Envelope = {
  success: true;
  /**
   * An image stored with the presentation; use `assetId` in image blocks and accents.
   */
  data: PresentationImageData;
  meta: EnvelopeMeta;
};

/** @internal */
export const ImportPublicPresentationImage201Envelope$inboundSchema:
  z.ZodMiniType<ImportPublicPresentationImage201Envelope, unknown> = z.object({
    success: types.literal(true),
    data: PresentationImageData$inboundSchema,
    meta: EnvelopeMeta$inboundSchema,
  });

export function importPublicPresentationImage201EnvelopeFromJSON(
  jsonString: string,
): SafeParseResult<
  ImportPublicPresentationImage201Envelope,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ImportPublicPresentationImage201Envelope$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ImportPublicPresentationImage201Envelope' from JSON`,
  );
}
