/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smart-union.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TransactionId = string | number;

export type InventoryTransactionSchema = {
  id?: string | null | undefined;
  transactionId?: string | number | null | undefined;
  inventoryId?: any | null | undefined;
  inventoryUuid?: string | null | undefined;
  inventoryType?: string | null | undefined;
  transactionType?: string | null | undefined;
  status?: string | null | undefined;
  amount?: number | null | undefined;
  transactionAmount?: number | null | undefined;
  useUnitValue?: boolean | null | undefined;
  price?: number | null | undefined;
  totalPrice?: number | null | undefined;
  averagePrice?: number | null | undefined;
  transactionDate?: Date | null | undefined;
  createdAt: Date;
  updatedAt: Date;
  usageStatus?: string | null | undefined;
};

/** @internal */
export const TransactionId$inboundSchema: z.ZodMiniType<
  TransactionId,
  unknown
> = smartUnion([types.string(), types.number()]);

export function transactionIdFromJSON(
  jsonString: string,
): SafeParseResult<TransactionId, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TransactionId$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TransactionId' from JSON`,
  );
}

/** @internal */
export const InventoryTransactionSchema$inboundSchema: z.ZodMiniType<
  InventoryTransactionSchema,
  unknown
> = z.pipe(
  z.object({
    id: z.optional(z.nullable(types.string())),
    transaction_id: z.optional(
      z.nullable(smartUnion([types.string(), types.number()])),
    ),
    inventory_id: z.optional(z.nullable(z.any())),
    inventory_uuid: z.optional(z.nullable(types.string())),
    inventory_type: z.optional(z.nullable(types.string())),
    transaction_type: z.optional(z.nullable(types.string())),
    status: z.optional(z.nullable(types.string())),
    amount: z.optional(z.nullable(types.number())),
    transaction_amount: z.optional(z.nullable(types.number())),
    use_unit_value: z.optional(z.nullable(types.boolean())),
    price: z.optional(z.nullable(types.number())),
    total_price: z.optional(z.nullable(types.number())),
    average_price: z.optional(z.nullable(types.number())),
    transaction_date: z.optional(z.nullable(types.date())),
    created_at: types.date(),
    updated_at: types.date(),
    usage_status: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "transaction_id": "transactionId",
      "inventory_id": "inventoryId",
      "inventory_uuid": "inventoryUuid",
      "inventory_type": "inventoryType",
      "transaction_type": "transactionType",
      "transaction_amount": "transactionAmount",
      "use_unit_value": "useUnitValue",
      "total_price": "totalPrice",
      "average_price": "averagePrice",
      "transaction_date": "transactionDate",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
      "usage_status": "usageStatus",
    });
  }),
);

export function inventoryTransactionSchemaFromJSON(
  jsonString: string,
): SafeParseResult<InventoryTransactionSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InventoryTransactionSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InventoryTransactionSchema' from JSON`,
  );
}
