/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { EnvelopeMeta, EnvelopeMeta$inboundSchema } from "./envelope-meta.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  ObjectRecordListData,
  ObjectRecordListData$inboundSchema,
} from "./object-record-list-data.js";

export type ListPublicJournalsApiV2PublicJournalsGet200Envelope = {
  success: true;
  data: ObjectRecordListData;
  meta: EnvelopeMeta;
};

/** @internal */
export const ListPublicJournalsApiV2PublicJournalsGet200Envelope$inboundSchema:
  z.ZodMiniType<ListPublicJournalsApiV2PublicJournalsGet200Envelope, unknown> =
    z.object({
      success: types.literal(true),
      data: ObjectRecordListData$inboundSchema,
      meta: EnvelopeMeta$inboundSchema,
    });

export function listPublicJournalsApiV2PublicJournalsGet200EnvelopeFromJSON(
  jsonString: string,
): SafeParseResult<
  ListPublicJournalsApiV2PublicJournalsGet200Envelope,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListPublicJournalsApiV2PublicJournalsGet200Envelope$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListPublicJournalsApiV2PublicJournalsGet200Envelope' from JSON`,
  );
}
