/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { EnvelopeMeta, EnvelopeMeta$inboundSchema } from "./envelope-meta.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  ObjectRecordListData,
  ObjectRecordListData$inboundSchema,
} from "./object-record-list-data.js";

export type ListPublicPaymentsApiV2PublicPaymentsGet200Envelope = {
  success: true;
  data: ObjectRecordListData;
  meta: EnvelopeMeta;
};

/** @internal */
export const ListPublicPaymentsApiV2PublicPaymentsGet200Envelope$inboundSchema:
  z.ZodMiniType<ListPublicPaymentsApiV2PublicPaymentsGet200Envelope, unknown> =
    z.object({
      success: types.literal(true),
      data: ObjectRecordListData$inboundSchema,
      meta: EnvelopeMeta$inboundSchema,
    });

export function listPublicPaymentsApiV2PublicPaymentsGet200EnvelopeFromJSON(
  jsonString: string,
): SafeParseResult<
  ListPublicPaymentsApiV2PublicPaymentsGet200Envelope,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListPublicPaymentsApiV2PublicPaymentsGet200Envelope$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListPublicPaymentsApiV2PublicPaymentsGet200Envelope' from JSON`,
  );
}
