/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { EnvelopeMeta, EnvelopeMeta$inboundSchema } from "./envelope-meta.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ListPublicWorkflowsApiV2PublicWorkflowsGet200Envelope = {
  success: true;
  data: { [k: string]: any };
  meta: EnvelopeMeta;
};

/** @internal */
export const ListPublicWorkflowsApiV2PublicWorkflowsGet200Envelope$inboundSchema:
  z.ZodMiniType<
    ListPublicWorkflowsApiV2PublicWorkflowsGet200Envelope,
    unknown
  > = z.object({
    success: types.literal(true),
    data: z.record(z.string(), z.any()),
    meta: EnvelopeMeta$inboundSchema,
  });

export function listPublicWorkflowsApiV2PublicWorkflowsGet200EnvelopeFromJSON(
  jsonString: string,
): SafeParseResult<
  ListPublicWorkflowsApiV2PublicWorkflowsGet200Envelope,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListPublicWorkflowsApiV2PublicWorkflowsGet200Envelope$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListPublicWorkflowsApiV2PublicWorkflowsGet200Envelope' from JSON`,
  );
}
