/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { EnvelopeMeta, EnvelopeMeta$inboundSchema } from "./envelope-meta.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  ObjectRecordListData,
  ObjectRecordListData$inboundSchema,
} from "./object-record-list-data.js";

export type ListPublicOrdersApiV2PublicOrdersGet200Envelope = {
  success: true;
  data: ObjectRecordListData;
  meta: EnvelopeMeta;
};

/** @internal */
export const ListPublicOrdersApiV2PublicOrdersGet200Envelope$inboundSchema:
  z.ZodMiniType<ListPublicOrdersApiV2PublicOrdersGet200Envelope, unknown> = z
    .object({
      success: types.literal(true),
      data: ObjectRecordListData$inboundSchema,
      meta: EnvelopeMeta$inboundSchema,
    });

export function listPublicOrdersApiV2PublicOrdersGet200EnvelopeFromJSON(
  jsonString: string,
): SafeParseResult<
  ListPublicOrdersApiV2PublicOrdersGet200Envelope,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListPublicOrdersApiV2PublicOrdersGet200Envelope$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListPublicOrdersApiV2PublicOrdersGet200Envelope' from JSON`,
  );
}
