/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type LookoutSignalRequest = {
  provider?: string | undefined;
  signalType: string;
  dedupeKey: string;
  occurredAt?: Date | undefined;
  account?: { [k: string]: any } | undefined;
  contact?: { [k: string]: any } | undefined;
  attributes?: { [k: string]: any } | undefined;
  sourceUrl?: string | null | undefined;
  confidence?: number | null | undefined;
  rawPayload?: { [k: string]: any } | undefined;
  [additionalProperties: string]: unknown;
};

/** @internal */
export type LookoutSignalRequest$Outbound = {
  provider: string;
  signal_type: string;
  dedupe_key: string;
  occurred_at?: string | undefined;
  account?: { [k: string]: any } | undefined;
  contact?: { [k: string]: any } | undefined;
  attributes?: { [k: string]: any } | undefined;
  source_url?: string | null | undefined;
  confidence?: number | null | undefined;
  raw_payload?: { [k: string]: any } | undefined;
  [additionalProperties: string]: unknown;
};

/** @internal */
export const LookoutSignalRequest$outboundSchema: z.ZodMiniType<
  LookoutSignalRequest$Outbound,
  LookoutSignalRequest
> = z.pipe(
  z.catchall(
    z.object({
      provider: z._default(z.string(), "lookout"),
      signalType: z.string(),
      dedupeKey: z.string(),
      occurredAt: z.optional(
        z.pipe(z.date(), z.transform(v => v.toISOString())),
      ),
      account: z.optional(z.record(z.string(), z.any())),
      contact: z.optional(z.record(z.string(), z.any())),
      attributes: z.optional(z.record(z.string(), z.any())),
      sourceUrl: z.optional(z.nullable(z.string())),
      confidence: z.optional(z.nullable(z.number())),
      rawPayload: z.optional(z.record(z.string(), z.any())),
    }),
    z.any(),
  ),
  z.transform((v) => {
    return {
      ...remap$(v, {
        signalType: "signal_type",
        dedupeKey: "dedupe_key",
        occurredAt: "occurred_at",
        sourceUrl: "source_url",
        rawPayload: "raw_payload",
      }),
    };
  }),
);

export function lookoutSignalRequestToJSON(
  lookoutSignalRequest: LookoutSignalRequest,
): string {
  return JSON.stringify(
    LookoutSignalRequest$outboundSchema.parse(lookoutSignalRequest),
  );
}
