/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type MoveSlidesOp = {
  op: "move_slides";
  slideIds: Array<string>;
  /**
   * Slide to move after; null moves first; omit to move last.
   */
  after?: string | null | undefined;
};

/** @internal */
export type MoveSlidesOp$Outbound = {
  op: "move_slides";
  slideIds: Array<string>;
  after?: string | null | undefined;
};

/** @internal */
export const MoveSlidesOp$outboundSchema: z.ZodMiniType<
  MoveSlidesOp$Outbound,
  MoveSlidesOp
> = z.object({
  op: z.literal("move_slides"),
  slideIds: z.array(z.string()),
  after: z.optional(z.nullable(z.string())),
});

export function moveSlidesOpToJSON(moveSlidesOp: MoveSlidesOp): string {
  return JSON.stringify(MoveSlidesOp$outboundSchema.parse(moveSlidesOp));
}
