/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { EnvelopeMeta, EnvelopeMeta$inboundSchema } from "./envelope-meta.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type MutatePublicObjectSchemaApiV2PublicObjectSchemasPost200Envelope = {
  success: true;
  data: { [k: string]: any };
  meta: EnvelopeMeta;
};

/** @internal */
export const MutatePublicObjectSchemaApiV2PublicObjectSchemasPost200Envelope$inboundSchema:
  z.ZodMiniType<
    MutatePublicObjectSchemaApiV2PublicObjectSchemasPost200Envelope,
    unknown
  > = z.object({
    success: types.literal(true),
    data: z.record(z.string(), z.any()),
    meta: EnvelopeMeta$inboundSchema,
  });

export function mutatePublicObjectSchemaApiV2PublicObjectSchemasPost200EnvelopeFromJSON(
  jsonString: string,
): SafeParseResult<
  MutatePublicObjectSchemaApiV2PublicObjectSchemasPost200Envelope,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      MutatePublicObjectSchemaApiV2PublicObjectSchemasPost200Envelope$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'MutatePublicObjectSchemaApiV2PublicObjectSchemasPost200Envelope' from JSON`,
  );
}
