/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type OrderLineItemMutationRequest = {
  lineItemId?: string | null | undefined;
  itemId?: string | null | undefined;
  itemExternalId?: string | null | undefined;
  customItemName?: string | null | undefined;
  quantity?: number | null | undefined;
  unitPrice?: number | null | undefined;
  taxRate?: number | null | undefined;
  taxType?: string | null | undefined;
  totalPrice?: number | null | undefined;
  currency?: string | null | undefined;
  customFields?: { [k: string]: any } | undefined;
};

/** @internal */
export type OrderLineItemMutationRequest$Outbound = {
  line_item_id?: string | null | undefined;
  item_id?: string | null | undefined;
  item_external_id?: string | null | undefined;
  custom_item_name?: string | null | undefined;
  quantity?: number | null | undefined;
  unit_price?: number | null | undefined;
  tax_rate?: number | null | undefined;
  tax_type?: string | null | undefined;
  total_price?: number | null | undefined;
  currency?: string | null | undefined;
  custom_fields?: { [k: string]: any } | undefined;
};

/** @internal */
export const OrderLineItemMutationRequest$outboundSchema: z.ZodMiniType<
  OrderLineItemMutationRequest$Outbound,
  OrderLineItemMutationRequest
> = z.pipe(
  z.object({
    lineItemId: z.optional(z.nullable(z.string())),
    itemId: z.optional(z.nullable(z.string())),
    itemExternalId: z.optional(z.nullable(z.string())),
    customItemName: z.optional(z.nullable(z.string())),
    quantity: z.optional(z.nullable(z.number())),
    unitPrice: z.optional(z.nullable(z.number())),
    taxRate: z.optional(z.nullable(z.number())),
    taxType: z.optional(z.nullable(z.string())),
    totalPrice: z.optional(z.nullable(z.number())),
    currency: z.optional(z.nullable(z.string())),
    customFields: z.optional(z.record(z.string(), z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      lineItemId: "line_item_id",
      itemId: "item_id",
      itemExternalId: "item_external_id",
      customItemName: "custom_item_name",
      unitPrice: "unit_price",
      taxRate: "tax_rate",
      taxType: "tax_type",
      totalPrice: "total_price",
      customFields: "custom_fields",
    });
  }),
);

export function orderLineItemMutationRequestToJSON(
  orderLineItemMutationRequest: OrderLineItemMutationRequest,
): string {
  return JSON.stringify(
    OrderLineItemMutationRequest$outboundSchema.parse(
      orderLineItemMutationRequest,
    ),
  );
}
