/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type PayrollJournalEntryRequest = {
  debitAccount?: string | null | undefined;
  creditAccount?: string | null | undefined;
  deductionsAccount?: string | null | undefined;
  notes?: string | null | undefined;
};

/** @internal */
export type PayrollJournalEntryRequest$Outbound = {
  debit_account?: string | null | undefined;
  credit_account?: string | null | undefined;
  deductions_account?: string | null | undefined;
  notes?: string | null | undefined;
};

/** @internal */
export const PayrollJournalEntryRequest$outboundSchema: z.ZodMiniType<
  PayrollJournalEntryRequest$Outbound,
  PayrollJournalEntryRequest
> = z.pipe(
  z.object({
    debitAccount: z.optional(z.nullable(z.string())),
    creditAccount: z.optional(z.nullable(z.string())),
    deductionsAccount: z.optional(z.nullable(z.string())),
    notes: z.optional(z.nullable(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      debitAccount: "debit_account",
      creditAccount: "credit_account",
      deductionsAccount: "deductions_account",
    });
  }),
);

export function payrollJournalEntryRequestToJSON(
  payrollJournalEntryRequest: PayrollJournalEntryRequest,
): string {
  return JSON.stringify(
    PayrollJournalEntryRequest$outboundSchema.parse(payrollJournalEntryRequest),
  );
}
