/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PresentationPreviewSlide,
  PresentationPreviewSlide$inboundSchema,
} from "./presentation-preview-slide.js";

export type PresentationPreviewData = {
  revision: number;
  slides: Array<PresentationPreviewSlide>;
  warnings?: Array<{ [k: string]: any }> | undefined;
};

/** @internal */
export const PresentationPreviewData$inboundSchema: z.ZodMiniType<
  PresentationPreviewData,
  unknown
> = z.object({
  revision: types.number(),
  slides: z.array(PresentationPreviewSlide$inboundSchema),
  warnings: types.optional(z.array(z.record(z.string(), z.any()))),
});

export function presentationPreviewDataFromJSON(
  jsonString: string,
): SafeParseResult<PresentationPreviewData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PresentationPreviewData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PresentationPreviewData' from JSON`,
  );
}
