/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { Deck, Deck$inboundSchema } from "./deck.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PresentationWarning,
  PresentationWarning$inboundSchema,
} from "./presentation-warning.js";

export const PresentationDataProduct = {
  Sanka: "sanka",
  Flow: "flow",
} as const;
export type PresentationDataProduct = OpenEnum<typeof PresentationDataProduct>;

export const PresentationDataUpdatedvia = {
  App: "app",
  Api: "api",
  Mcp: "mcp",
  System: "system",
} as const;
export type PresentationDataUpdatedvia = OpenEnum<
  typeof PresentationDataUpdatedvia
>;

export type PresentationData = {
  id: string;
  programId?: string | null | undefined;
  workspaceId: string;
  product: PresentationDataProduct;
  kind: "presentation";
  title: string;
  revision: number;
  deck: Deck;
  slideCount: number;
  /**
   * Read-only Markdown outline derived from the deck.
   */
  outline: string;
  updatedVia: PresentationDataUpdatedvia;
  sourceRef?: string | null | undefined;
  pinned: boolean;
  archivedAt?: Date | null | undefined;
  createdById?: number | null | undefined;
  updatedById?: number | null | undefined;
  createdAt?: Date | null | undefined;
  updatedAt?: Date | null | undefined;
  /**
   * App-relative URL of the Docs page with this presentation open.
   */
  appPath: string;
  warnings?: Array<PresentationWarning> | undefined;
};

/** @internal */
export const PresentationDataProduct$inboundSchema: z.ZodMiniType<
  PresentationDataProduct,
  unknown
> = openEnums.inboundSchema(PresentationDataProduct);

/** @internal */
export const PresentationDataUpdatedvia$inboundSchema: z.ZodMiniType<
  PresentationDataUpdatedvia,
  unknown
> = openEnums.inboundSchema(PresentationDataUpdatedvia);

/** @internal */
export const PresentationData$inboundSchema: z.ZodMiniType<
  PresentationData,
  unknown
> = z.object({
  id: types.string(),
  programId: z.optional(z.nullable(types.string())),
  workspaceId: types.string(),
  product: PresentationDataProduct$inboundSchema,
  kind: z._default(types.literal("presentation"), "presentation"),
  title: types.string(),
  revision: types.number(),
  deck: Deck$inboundSchema,
  slideCount: types.number(),
  outline: types.string(),
  updatedVia: PresentationDataUpdatedvia$inboundSchema,
  sourceRef: z.optional(z.nullable(types.string())),
  pinned: z._default(types.boolean(), false),
  archivedAt: z.optional(z.nullable(types.date())),
  createdById: z.optional(z.nullable(types.number())),
  updatedById: z.optional(z.nullable(types.number())),
  createdAt: z.optional(z.nullable(types.date())),
  updatedAt: z.optional(z.nullable(types.date())),
  appPath: types.string(),
  warnings: types.optional(z.array(PresentationWarning$inboundSchema)),
});

export function presentationDataFromJSON(
  jsonString: string,
): SafeParseResult<PresentationData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PresentationData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PresentationData' from JSON`,
  );
}
