/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type PresentationWarning = {
  code: string;
  path: string;
  message: string;
};

/** @internal */
export const PresentationWarning$inboundSchema: z.ZodMiniType<
  PresentationWarning,
  unknown
> = z.object({
  code: types.string(),
  path: types.string(),
  message: types.string(),
});

export function presentationWarningFromJSON(
  jsonString: string,
): SafeParseResult<PresentationWarning, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PresentationWarning$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PresentationWarning' from JSON`,
  );
}
