/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";
import {
  PresentationThemeChoice,
  PresentationThemeChoice$Outbound,
  PresentationThemeChoice$outboundSchema,
} from "./presentation-theme-choice.js";

export const PresentationCreateRequestPageSize = {
  OneHundredAndSixtyNine: "16:9",
  A4Landscape: "a4-landscape",
} as const;
export type PresentationCreateRequestPageSize = ClosedEnum<
  typeof PresentationCreateRequestPageSize
>;

export type PresentationCreateRequest = {
  title: string;
  /**
   * A `sanka.deck/v1` deck. The presentations catalog (`GET …/presentations/catalog`) publishes its JSON Schema, limits and guidance. Give at most one of `deck`, `markdown` and `sourceDocumentId`; with none of them the presentation starts with one title slide.
   */
  deck?: { [k: string]: any } | null | undefined;
  /**
   * Markdown to lay out as slides: `---` and the most frequent of the top two heading levels start slides; lists, tables, quotes, images and Mermaid fences become blocks.
   */
  markdown?: string | null | undefined;
  /**
   * A Markdown Doc in the same Docs to convert; the Doc itself is unchanged.
   */
  sourceDocumentId?: string | null | undefined;
  /**
   * Slide size; overrides `deck.page.size`. Defaults to 16:9.
   */
  pageSize?: PresentationCreateRequestPageSize | null | undefined;
  /**
   * Theme; overrides `deck.theme`.
   */
  theme?: PresentationThemeChoice | null | undefined;
  /**
   * Docs folder to create the presentation in.
   */
  folderId?: string | null | undefined;
  sourceRef?: string | null | undefined;
};

/** @internal */
export const PresentationCreateRequestPageSize$outboundSchema: z.ZodMiniEnum<
  typeof PresentationCreateRequestPageSize
> = z.enum(PresentationCreateRequestPageSize);

/** @internal */
export type PresentationCreateRequest$Outbound = {
  title: string;
  deck?: { [k: string]: any } | null | undefined;
  markdown?: string | null | undefined;
  sourceDocumentId?: string | null | undefined;
  pageSize?: string | null | undefined;
  theme?: PresentationThemeChoice$Outbound | null | undefined;
  folderId?: string | null | undefined;
  sourceRef?: string | null | undefined;
};

/** @internal */
export const PresentationCreateRequest$outboundSchema: z.ZodMiniType<
  PresentationCreateRequest$Outbound,
  PresentationCreateRequest
> = z.object({
  title: z.string(),
  deck: z.optional(z.nullable(z.record(z.string(), z.any()))),
  markdown: z.optional(z.nullable(z.string())),
  sourceDocumentId: z.optional(z.nullable(z.string())),
  pageSize: z.optional(
    z.nullable(PresentationCreateRequestPageSize$outboundSchema),
  ),
  theme: z.optional(z.nullable(PresentationThemeChoice$outboundSchema)),
  folderId: z.optional(z.nullable(z.string())),
  sourceRef: z.optional(z.nullable(z.string())),
});

export function presentationCreateRequestToJSON(
  presentationCreateRequest: PresentationCreateRequest,
): string {
  return JSON.stringify(
    PresentationCreateRequest$outboundSchema.parse(presentationCreateRequest),
  );
}
