/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type ProspectCompaniesRequest = {
  query?: string | null | undefined;
  location?: string | null | undefined;
  industry?: string | null | undefined;
  minEmployeeCount?: number | null | undefined;
  maxEmployeeCount?: number | null | undefined;
  limit?: number | undefined;
  sources?: Array<string> | undefined;
};

/** @internal */
export type ProspectCompaniesRequest$Outbound = {
  query?: string | null | undefined;
  location?: string | null | undefined;
  industry?: string | null | undefined;
  min_employee_count?: number | null | undefined;
  max_employee_count?: number | null | undefined;
  limit: number;
  sources?: Array<string> | undefined;
};

/** @internal */
export const ProspectCompaniesRequest$outboundSchema: z.ZodMiniType<
  ProspectCompaniesRequest$Outbound,
  ProspectCompaniesRequest
> = z.pipe(
  z.object({
    query: z.optional(z.nullable(z.string())),
    location: z.optional(z.nullable(z.string())),
    industry: z.optional(z.nullable(z.string())),
    minEmployeeCount: z.optional(z.nullable(z.int())),
    maxEmployeeCount: z.optional(z.nullable(z.int())),
    limit: z._default(z.int(), 10),
    sources: z.optional(z.array(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      minEmployeeCount: "min_employee_count",
      maxEmployeeCount: "max_employee_count",
    });
  }),
);

export function prospectCompaniesRequestToJSON(
  prospectCompaniesRequest: ProspectCompaniesRequest,
): string {
  return JSON.stringify(
    ProspectCompaniesRequest$outboundSchema.parse(prospectCompaniesRequest),
  );
}
