/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ProspectCompanyData = {
  name?: string | null | undefined;
  url?: string | null | undefined;
  domain?: string | null | undefined;
  industry?: string | null | undefined;
  employeeCount?: number | null | undefined;
  employeeCountDisplay?: string | null | undefined;
  address?: string | null | undefined;
  email?: string | null | undefined;
  phoneNumber?: string | null | undefined;
  linkedinUrl?: string | null | undefined;
  description?: string | null | undefined;
  sourceUrls?: Array<string> | undefined;
  sources?: Array<string> | undefined;
  relevanceScore: number;
  matchReasons?: Array<string> | undefined;
  providerMeta?: { [k: string]: any } | undefined;
};

/** @internal */
export const ProspectCompanyData$inboundSchema: z.ZodMiniType<
  ProspectCompanyData,
  unknown
> = z.pipe(
  z.object({
    name: z.optional(z.nullable(types.string())),
    url: z.optional(z.nullable(types.string())),
    domain: z.optional(z.nullable(types.string())),
    industry: z.optional(z.nullable(types.string())),
    employee_count: z.optional(z.nullable(types.number())),
    employee_count_display: z.optional(z.nullable(types.string())),
    address: z.optional(z.nullable(types.string())),
    email: z.optional(z.nullable(types.string())),
    phone_number: z.optional(z.nullable(types.string())),
    linkedin_url: z.optional(z.nullable(types.string())),
    description: z.optional(z.nullable(types.string())),
    source_urls: types.optional(z.array(types.string())),
    sources: types.optional(z.array(types.string())),
    relevance_score: z._default(types.number(), 0),
    match_reasons: types.optional(z.array(types.string())),
    provider_meta: types.optional(z.record(z.string(), z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "employee_count": "employeeCount",
      "employee_count_display": "employeeCountDisplay",
      "phone_number": "phoneNumber",
      "linkedin_url": "linkedinUrl",
      "source_urls": "sourceUrls",
      "relevance_score": "relevanceScore",
      "match_reasons": "matchReasons",
      "provider_meta": "providerMeta",
    });
  }),
);

export function prospectCompanyDataFromJSON(
  jsonString: string,
): SafeParseResult<ProspectCompanyData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProspectCompanyData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProspectCompanyData' from JSON`,
  );
}
