/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type PublicSlipRequest = {
  externalId?: string | null | undefined;
  contactId?: string | null | undefined;
  contactExternalId?: string | null | undefined;
  companyId?: string | null | undefined;
  companyExternalId?: string | null | undefined;
  startDate?: string | null | undefined;
  status?: string | null | undefined;
  slipType?: string | null | undefined;
  currency?: string | null | undefined;
  notes?: string | null | undefined;
  taxRate?: number | null | undefined;
  taxInclusive?: boolean | null | undefined;
  taxOption?: string | null | undefined;
  totalPrice?: number | null | undefined;
  totalPriceWithoutTax?: number | null | undefined;
};

/** @internal */
export type PublicSlipRequest$Outbound = {
  external_id?: string | null | undefined;
  contact_id?: string | null | undefined;
  contact_external_id?: string | null | undefined;
  company_id?: string | null | undefined;
  company_external_id?: string | null | undefined;
  start_date?: string | null | undefined;
  status?: string | null | undefined;
  slip_type?: string | null | undefined;
  currency?: string | null | undefined;
  notes?: string | null | undefined;
  tax_rate?: number | null | undefined;
  tax_inclusive?: boolean | null | undefined;
  tax_option?: string | null | undefined;
  total_price?: number | null | undefined;
  total_price_without_tax?: number | null | undefined;
};

/** @internal */
export const PublicSlipRequest$outboundSchema: z.ZodMiniType<
  PublicSlipRequest$Outbound,
  PublicSlipRequest
> = z.pipe(
  z.object({
    externalId: z.optional(z.nullable(z.string())),
    contactId: z.optional(z.nullable(z.string())),
    contactExternalId: z.optional(z.nullable(z.string())),
    companyId: z.optional(z.nullable(z.string())),
    companyExternalId: z.optional(z.nullable(z.string())),
    startDate: z.optional(z.nullable(z.string())),
    status: z.optional(z.nullable(z.string())),
    slipType: z.optional(z.nullable(z.string())),
    currency: z.optional(z.nullable(z.string())),
    notes: z.optional(z.nullable(z.string())),
    taxRate: z.optional(z.nullable(z.number())),
    taxInclusive: z.optional(z.nullable(z.boolean())),
    taxOption: z.optional(z.nullable(z.string())),
    totalPrice: z.optional(z.nullable(z.number())),
    totalPriceWithoutTax: z.optional(z.nullable(z.number())),
  }),
  z.transform((v) => {
    return remap$(v, {
      externalId: "external_id",
      contactId: "contact_id",
      contactExternalId: "contact_external_id",
      companyId: "company_id",
      companyExternalId: "company_external_id",
      startDate: "start_date",
      slipType: "slip_type",
      taxRate: "tax_rate",
      taxInclusive: "tax_inclusive",
      taxOption: "tax_option",
      totalPrice: "total_price",
      totalPriceWithoutTax: "total_price_without_tax",
    });
  }),
);

export function publicSlipRequestToJSON(
  publicSlipRequest: PublicSlipRequest,
): string {
  return JSON.stringify(
    PublicSlipRequest$outboundSchema.parse(publicSlipRequest),
  );
}
