/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type PublicFlowConstructRequest = {
  planDigest: string;
  attemptId: string;
};

/** @internal */
export type PublicFlowConstructRequest$Outbound = {
  plan_digest: string;
  attempt_id: string;
};

/** @internal */
export const PublicFlowConstructRequest$outboundSchema: z.ZodMiniType<
  PublicFlowConstructRequest$Outbound,
  PublicFlowConstructRequest
> = z.pipe(
  z.object({
    planDigest: z.string(),
    attemptId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      planDigest: "plan_digest",
      attemptId: "attempt_id",
    });
  }),
);

export function publicFlowConstructRequestToJSON(
  publicFlowConstructRequest: PublicFlowConstructRequest,
): string {
  return JSON.stringify(
    PublicFlowConstructRequest$outboundSchema.parse(publicFlowConstructRequest),
  );
}
