/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type PublicExpenseResponse = {
  ok: boolean;
  status: string;
  externalId?: string | null | undefined;
  expenseId?: string | null | undefined;
  ctxId?: string | null | undefined;
};

/** @internal */
export const PublicExpenseResponse$inboundSchema: z.ZodMiniType<
  PublicExpenseResponse,
  unknown
> = z.pipe(
  z.object({
    ok: types.boolean(),
    status: types.string(),
    external_id: z.optional(z.nullable(types.string())),
    expense_id: z.optional(z.nullable(types.string())),
    ctx_id: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "external_id": "externalId",
      "expense_id": "expenseId",
      "ctx_id": "ctxId",
    });
  }),
);

export function publicExpenseResponseFromJSON(
  jsonString: string,
): SafeParseResult<PublicExpenseResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PublicExpenseResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PublicExpenseResponse' from JSON`,
  );
}
