/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type PublicPropertyMutationResponse = {
  ok: boolean;
  status: string;
  object: string;
  propertyId: string;
  ctxId: string;
};

/** @internal */
export const PublicPropertyMutationResponse$inboundSchema: z.ZodMiniType<
  PublicPropertyMutationResponse,
  unknown
> = z.pipe(
  z.object({
    ok: types.boolean(),
    status: types.string(),
    object: types.string(),
    property_id: types.string(),
    ctx_id: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "property_id": "propertyId",
      "ctx_id": "ctxId",
    });
  }),
);

export function publicPropertyMutationResponseFromJSON(
  jsonString: string,
): SafeParseResult<PublicPropertyMutationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PublicPropertyMutationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PublicPropertyMutationResponse' from JSON`,
  );
}
