/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PublicWorkflowListItemResponse,
  PublicWorkflowListItemResponse$inboundSchema,
} from "./public-workflow-list-item-response.js";

export type PublicWorkflowListResponse = {
  data: Array<PublicWorkflowListItemResponse>;
  count: number;
  page: number;
  limit: number;
  ctxId?: string | null | undefined;
};

/** @internal */
export const PublicWorkflowListResponse$inboundSchema: z.ZodMiniType<
  PublicWorkflowListResponse,
  unknown
> = z.pipe(
  z.object({
    data: z.array(PublicWorkflowListItemResponse$inboundSchema),
    count: types.number(),
    page: types.number(),
    limit: types.number(),
    ctx_id: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "ctx_id": "ctxId",
    });
  }),
);

export function publicWorkflowListResponseFromJSON(
  jsonString: string,
): SafeParseResult<PublicWorkflowListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PublicWorkflowListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PublicWorkflowListResponse' from JSON`,
  );
}
