/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  BulkOrderIn,
  BulkOrderIn$Outbound,
  BulkOrderIn$outboundSchema,
} from "./bulk-order-in.js";

export type PublicOrderRequest = {
  order: BulkOrderIn;
  createMissingItems?: boolean | undefined;
  triggerWorkflows?: boolean | undefined;
};

/** @internal */
export type PublicOrderRequest$Outbound = {
  order: BulkOrderIn$Outbound;
  createMissingItems: boolean;
  triggerWorkflows: boolean;
};

/** @internal */
export const PublicOrderRequest$outboundSchema: z.ZodMiniType<
  PublicOrderRequest$Outbound,
  PublicOrderRequest
> = z.object({
  order: BulkOrderIn$outboundSchema,
  createMissingItems: z._default(z.boolean(), false),
  triggerWorkflows: z._default(z.boolean(), true),
});

export function publicOrderRequestToJSON(
  publicOrderRequest: PublicOrderRequest,
): string {
  return JSON.stringify(
    PublicOrderRequest$outboundSchema.parse(publicOrderRequest),
  );
}
