/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type PublicReportMetricRequest = {
  role?: string | null | undefined;
  name?: string | null | undefined;
  metric: string;
  metricType?: string | null | undefined;
  order?: number | null | undefined;
  filter?: { [k: string]: any } | null | undefined;
  dataSource?: string | null | undefined;
  sort?: string | null | undefined;
  metaData?: { [k: string]: any } | null | undefined;
  rawSql?: string | null | undefined;
  displayResult?: string | null | undefined;
};

/** @internal */
export type PublicReportMetricRequest$Outbound = {
  role?: string | null | undefined;
  name?: string | null | undefined;
  metric: string;
  metricType?: string | null | undefined;
  order?: number | null | undefined;
  filter?: { [k: string]: any } | null | undefined;
  dataSource?: string | null | undefined;
  sort?: string | null | undefined;
  metaData?: { [k: string]: any } | null | undefined;
  rawSql?: string | null | undefined;
  displayResult?: string | null | undefined;
};

/** @internal */
export const PublicReportMetricRequest$outboundSchema: z.ZodMiniType<
  PublicReportMetricRequest$Outbound,
  PublicReportMetricRequest
> = z.object({
  role: z.optional(z.nullable(z.string())),
  name: z.optional(z.nullable(z.string())),
  metric: z.string(),
  metricType: z.optional(z.nullable(z.string())),
  order: z.optional(z.nullable(z.int())),
  filter: z.optional(z.nullable(z.record(z.string(), z.any()))),
  dataSource: z.optional(z.nullable(z.string())),
  sort: z.optional(z.nullable(z.string())),
  metaData: z.optional(z.nullable(z.record(z.string(), z.any()))),
  rawSql: z.optional(z.nullable(z.string())),
  displayResult: z.optional(z.nullable(z.string())),
});

export function publicReportMetricRequestToJSON(
  publicReportMetricRequest: PublicReportMetricRequest,
): string {
  return JSON.stringify(
    PublicReportMetricRequest$outboundSchema.parse(publicReportMetricRequest),
  );
}
