/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smart-union.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Value = string | number | number | boolean | Array<string>;

export type PublicFlowFieldState = {
  present: boolean;
  value?: string | number | number | boolean | Array<string> | null | undefined;
};

/** @internal */
export const Value$inboundSchema: z.ZodMiniType<Value, unknown> = smartUnion([
  types.string(),
  types.number(),
  types.number(),
  types.boolean(),
  z.array(types.string()),
]);

export function valueFromJSON(
  jsonString: string,
): SafeParseResult<Value, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Value$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Value' from JSON`,
  );
}

/** @internal */
export const PublicFlowFieldState$inboundSchema: z.ZodMiniType<
  PublicFlowFieldState,
  unknown
> = z.object({
  present: types.boolean(),
  value: z.optional(
    z.nullable(
      smartUnion([
        types.string(),
        types.number(),
        types.number(),
        types.boolean(),
        z.array(types.string()),
      ]),
    ),
  ),
});

export function publicFlowFieldStateFromJSON(
  jsonString: string,
): SafeParseResult<PublicFlowFieldState, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PublicFlowFieldState$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PublicFlowFieldState' from JSON`,
  );
}
