/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  CalendarDayScheduleSchema,
  CalendarDayScheduleSchema$inboundSchema,
} from "./calendar-day-schedule-schema.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type PublicCalendarEventSchema = {
  id: string;
  title: string;
  description?: string | null | undefined;
  status?: string | null | undefined;
  slug?: string | null | undefined;
  url?: string | null | undefined;
  location?: string | null | undefined;
  duration?: string | null | undefined;
  timeIncrement?: string | null | undefined;
  timezone?: string | null | undefined;
  timezoneLabel?: string | null | undefined;
  timezoneLocked: boolean;
  schedule?: Array<CalendarDayScheduleSchema> | undefined;
};

/** @internal */
export const PublicCalendarEventSchema$inboundSchema: z.ZodMiniType<
  PublicCalendarEventSchema,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    title: types.string(),
    description: z.optional(z.nullable(types.string())),
    status: z.optional(z.nullable(types.string())),
    slug: z.optional(z.nullable(types.string())),
    url: z.optional(z.nullable(types.string())),
    location: z.optional(z.nullable(types.string())),
    duration: z.optional(z.nullable(types.string())),
    time_increment: z.optional(z.nullable(types.string())),
    timezone: z.optional(z.nullable(types.string())),
    timezone_label: z.optional(z.nullable(types.string())),
    timezone_locked: z._default(types.boolean(), false),
    schedule: types.optional(z.array(CalendarDayScheduleSchema$inboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      "time_increment": "timeIncrement",
      "timezone_label": "timezoneLabel",
      "timezone_locked": "timezoneLocked",
    });
  }),
);

export function publicCalendarEventSchemaFromJSON(
  jsonString: string,
): SafeParseResult<PublicCalendarEventSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PublicCalendarEventSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PublicCalendarEventSchema' from JSON`,
  );
}
