/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type PublicOrderDetailSchema = {
  id: string;
  orderId?: number | null | undefined;
  status?: string | null | undefined;
  deliveryStatus?: string | null | undefined;
  totalPrice?: number | null | undefined;
  totalPriceWithoutTax?: number | null | undefined;
  numberItem?: number | null | undefined;
  currency?: string | null | undefined;
  orderAt: Date;
  createdAt: Date;
  updatedAt: Date;
  companyId?: string | null | undefined;
  contactId?: string | null | undefined;
};

/** @internal */
export const PublicOrderDetailSchema$inboundSchema: z.ZodMiniType<
  PublicOrderDetailSchema,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    order_id: z.optional(z.nullable(types.number())),
    status: z.optional(z.nullable(types.string())),
    delivery_status: z.optional(z.nullable(types.string())),
    total_price: z.optional(z.nullable(types.number())),
    total_price_without_tax: z.optional(z.nullable(types.number())),
    number_item: z.optional(z.nullable(types.number())),
    currency: z.optional(z.nullable(types.string())),
    order_at: types.date(),
    created_at: types.date(),
    updated_at: types.date(),
    company_id: z.optional(z.nullable(types.string())),
    contact_id: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "order_id": "orderId",
      "delivery_status": "deliveryStatus",
      "total_price": "totalPrice",
      "total_price_without_tax": "totalPriceWithoutTax",
      "number_item": "numberItem",
      "order_at": "orderAt",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
      "company_id": "companyId",
      "contact_id": "contactId",
    });
  }),
);

export function publicOrderDetailSchemaFromJSON(
  jsonString: string,
): SafeParseResult<PublicOrderDetailSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PublicOrderDetailSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PublicOrderDetailSchema' from JSON`,
  );
}
