/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type PublicExpenseAttachmentFileRef = {
  id?: string | null | undefined;
  fileId?: string | null | undefined;
  name?: string | null | undefined;
};

/** @internal */
export type PublicExpenseAttachmentFileRef$Outbound = {
  id?: string | null | undefined;
  file_id?: string | null | undefined;
  name?: string | null | undefined;
};

/** @internal */
export const PublicExpenseAttachmentFileRef$outboundSchema: z.ZodMiniType<
  PublicExpenseAttachmentFileRef$Outbound,
  PublicExpenseAttachmentFileRef
> = z.pipe(
  z.object({
    id: z.optional(z.nullable(z.string())),
    fileId: z.optional(z.nullable(z.string())),
    name: z.optional(z.nullable(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      fileId: "file_id",
    });
  }),
);

export function publicExpenseAttachmentFileRefToJSON(
  publicExpenseAttachmentFileRef: PublicExpenseAttachmentFileRef,
): string {
  return JSON.stringify(
    PublicExpenseAttachmentFileRef$outboundSchema.parse(
      publicExpenseAttachmentFileRef,
    ),
  );
}
