/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type PublicWorkflowResponse = {
  ok: boolean;
  status: string;
  externalId: string;
  workflowId: string;
  validToRun: boolean;
  nodeCount: number;
  ctxId?: string | null | undefined;
};

/** @internal */
export const PublicWorkflowResponse$inboundSchema: z.ZodMiniType<
  PublicWorkflowResponse,
  unknown
> = z.pipe(
  z.object({
    ok: types.boolean(),
    status: types.string(),
    external_id: types.string(),
    workflow_id: types.string(),
    valid_to_run: types.boolean(),
    node_count: types.number(),
    ctx_id: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "external_id": "externalId",
      "workflow_id": "workflowId",
      "valid_to_run": "validToRun",
      "node_count": "nodeCount",
      "ctx_id": "ctxId",
    });
  }),
);

export function publicWorkflowResponseFromJSON(
  jsonString: string,
): SafeParseResult<PublicWorkflowResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PublicWorkflowResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PublicWorkflowResponse' from JSON`,
  );
}
