/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type PublicOrderDeleteResponse = {
  ok: boolean;
  status: string;
  externalId?: string | null | undefined;
  orderId?: string | null | undefined;
  ctxId?: string | null | undefined;
};

/** @internal */
export const PublicOrderDeleteResponse$inboundSchema: z.ZodMiniType<
  PublicOrderDeleteResponse,
  unknown
> = z.pipe(
  z.object({
    ok: types.boolean(),
    status: types.string(),
    external_id: z.optional(z.nullable(types.string())),
    order_id: z.optional(z.nullable(types.string())),
    ctx_id: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "external_id": "externalId",
      "order_id": "orderId",
      "ctx_id": "ctxId",
    });
  }),
);

export function publicOrderDeleteResponseFromJSON(
  jsonString: string,
): SafeParseResult<PublicOrderDeleteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PublicOrderDeleteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PublicOrderDeleteResponse' from JSON`,
  );
}
