/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  FieldReference,
  FieldReference$inboundSchema,
  FieldReference$Outbound,
  FieldReference$outboundSchema,
} from "./field-reference.js";

export const Operator = {
  Equals: "equals",
  NotEquals: "not_equals",
  Contains: "contains",
  DoesNotContain: "does_not_contain",
  StartsWith: "starts_with",
  EndsWith: "ends_with",
  In: "in",
  NotIn: "not_in",
  IsEmpty: "is_empty",
  IsNotEmpty: "is_not_empty",
  GreaterThan: "greater_than",
  GreaterThanOrEqual: "greater_than_or_equal",
  LessThan: "less_than",
  LessThanOrEqual: "less_than_or_equal",
  Between: "between",
  EqualOrAfterToday: "equal_or_after_today",
  EqualOrBeforeToday: "equal_or_before_today",
  LastXDays: "last_x_days",
  MoreThanXDays: "more_than_x_days",
} as const;
export type Operator = OpenEnum<typeof Operator>;

export type SearchFilterExpression = {
  field: FieldReference;
  operator: Operator;
  value?: any | undefined;
  selectedLabel?: string | null | undefined;
};

/** @internal */
export const Operator$inboundSchema: z.ZodMiniType<Operator, unknown> =
  openEnums.inboundSchema(Operator);
/** @internal */
export const Operator$outboundSchema: z.ZodMiniType<string, Operator> =
  openEnums.outboundSchema(Operator);

/** @internal */
export const SearchFilterExpression$inboundSchema: z.ZodMiniType<
  SearchFilterExpression,
  unknown
> = z.pipe(
  z.object({
    field: FieldReference$inboundSchema,
    operator: Operator$inboundSchema,
    value: types.optional(z.any()),
    selected_label: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "selected_label": "selectedLabel",
    });
  }),
);
/** @internal */
export type SearchFilterExpression$Outbound = {
  field: FieldReference$Outbound;
  operator: string;
  value?: any | undefined;
  selected_label?: string | null | undefined;
};

/** @internal */
export const SearchFilterExpression$outboundSchema: z.ZodMiniType<
  SearchFilterExpression$Outbound,
  SearchFilterExpression
> = z.pipe(
  z.object({
    field: FieldReference$outboundSchema,
    operator: Operator$outboundSchema,
    value: z.optional(z.any()),
    selectedLabel: z.optional(z.nullable(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      selectedLabel: "selected_label",
    });
  }),
);

export function searchFilterExpressionToJSON(
  searchFilterExpression: SearchFilterExpression,
): string {
  return JSON.stringify(
    SearchFilterExpression$outboundSchema.parse(searchFilterExpression),
  );
}
export function searchFilterExpressionFromJSON(
  jsonString: string,
): SafeParseResult<SearchFilterExpression, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchFilterExpression$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchFilterExpression' from JSON`,
  );
}
