/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { EnvelopeMeta, EnvelopeMeta$inboundSchema } from "./envelope-meta.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  GoalDetailData,
  GoalDetailData$inboundSchema,
} from "./goal-detail-data.js";

export type SetPublicGoalTargets200Envelope = {
  success: true;
  data: GoalDetailData;
  meta: EnvelopeMeta;
};

/** @internal */
export const SetPublicGoalTargets200Envelope$inboundSchema: z.ZodMiniType<
  SetPublicGoalTargets200Envelope,
  unknown
> = z.object({
  success: types.literal(true),
  data: GoalDetailData$inboundSchema,
  meta: EnvelopeMeta$inboundSchema,
});

export function setPublicGoalTargets200EnvelopeFromJSON(
  jsonString: string,
): SafeParseResult<SetPublicGoalTargets200Envelope, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SetPublicGoalTargets200Envelope$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SetPublicGoalTargets200Envelope' from JSON`,
  );
}
