/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { EnvelopeMeta, EnvelopeMeta$inboundSchema } from "./envelope-meta.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type StartPublicHubspotRevenueControlReportApiV2PublicReportsRevenueControlHubspotPost200Envelope =
  {
    success: true;
    data: { [k: string]: any };
    meta: EnvelopeMeta;
  };

/** @internal */
export const StartPublicHubspotRevenueControlReportApiV2PublicReportsRevenueControlHubspotPost200Envelope$inboundSchema:
  z.ZodMiniType<
    StartPublicHubspotRevenueControlReportApiV2PublicReportsRevenueControlHubspotPost200Envelope,
    unknown
  > = z.object({
    success: types.literal(true),
    data: z.record(z.string(), z.any()),
    meta: EnvelopeMeta$inboundSchema,
  });

export function startPublicHubspotRevenueControlReportApiV2PublicReportsRevenueControlHubspotPost200EnvelopeFromJSON(
  jsonString: string,
): SafeParseResult<
  StartPublicHubspotRevenueControlReportApiV2PublicReportsRevenueControlHubspotPost200Envelope,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      StartPublicHubspotRevenueControlReportApiV2PublicReportsRevenueControlHubspotPost200Envelope$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'StartPublicHubspotRevenueControlReportApiV2PublicReportsRevenueControlHubspotPost200Envelope' from JSON`,
  );
}
