/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { StatItem, StatItem$inboundSchema } from "./stat-item.js";

export type StatsBlock = {
  type: "stats";
  id?: string | null | undefined;
  items: Array<StatItem>;
};

/** @internal */
export const StatsBlock$inboundSchema: z.ZodMiniType<StatsBlock, unknown> = z
  .object({
    type: types.literal("stats"),
    id: z.optional(z.nullable(types.string())),
    items: z.array(StatItem$inboundSchema),
  });

export function statsBlockFromJSON(
  jsonString: string,
): SafeParseResult<StatsBlock, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StatsBlock$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StatsBlock' from JSON`,
  );
}
