/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type StepItem = {
  id?: string | null | undefined;
  title: string;
  body?: string | null | undefined;
};

/** @internal */
export const StepItem$inboundSchema: z.ZodMiniType<StepItem, unknown> = z
  .object({
    id: z.optional(z.nullable(types.string())),
    title: types.string(),
    body: z.optional(z.nullable(types.string())),
  });

export function stepItemFromJSON(
  jsonString: string,
): SafeParseResult<StepItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StepItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StepItem' from JSON`,
  );
}
