/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type SubscriptionItemInput = {
  id: string;
  amount: number;
  price?: number | null | undefined;
  name?: string | null | undefined;
};

/** @internal */
export type SubscriptionItemInput$Outbound = {
  id: string;
  amount: number;
  price?: number | null | undefined;
  name?: string | null | undefined;
};

/** @internal */
export const SubscriptionItemInput$outboundSchema: z.ZodMiniType<
  SubscriptionItemInput$Outbound,
  SubscriptionItemInput
> = z.object({
  id: z.string(),
  amount: z.int(),
  price: z.optional(z.nullable(z.number())),
  name: z.optional(z.nullable(z.string())),
});

export function subscriptionItemInputToJSON(
  subscriptionItemInput: SubscriptionItemInput,
): string {
  return JSON.stringify(
    SubscriptionItemInput$outboundSchema.parse(subscriptionItemInput),
  );
}
