/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { EnvelopeMeta, EnvelopeMeta$inboundSchema } from "./envelope-meta.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  FerryProgramMeetingData,
  FerryProgramMeetingData$inboundSchema,
} from "./ferry-program-meeting-data.js";

export type UpdatePublicFerryProgramMeetingApiV2PublicFerryProgramsProgramIdMeetingsMeetingIdPatch200Envelope =
  {
    success: true;
    data: FerryProgramMeetingData;
    meta: EnvelopeMeta;
  };

/** @internal */
export const UpdatePublicFerryProgramMeetingApiV2PublicFerryProgramsProgramIdMeetingsMeetingIdPatch200Envelope$inboundSchema:
  z.ZodMiniType<
    UpdatePublicFerryProgramMeetingApiV2PublicFerryProgramsProgramIdMeetingsMeetingIdPatch200Envelope,
    unknown
  > = z.object({
    success: types.literal(true),
    data: FerryProgramMeetingData$inboundSchema,
    meta: EnvelopeMeta$inboundSchema,
  });

export function updatePublicFerryProgramMeetingApiV2PublicFerryProgramsProgramIdMeetingsMeetingIdPatch200EnvelopeFromJSON(
  jsonString: string,
): SafeParseResult<
  UpdatePublicFerryProgramMeetingApiV2PublicFerryProgramsProgramIdMeetingsMeetingIdPatch200Envelope,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      UpdatePublicFerryProgramMeetingApiV2PublicFerryProgramsProgramIdMeetingsMeetingIdPatch200Envelope$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'UpdatePublicFerryProgramMeetingApiV2PublicFerryProgramsProgramIdMeetingsMeetingIdPatch200Envelope' from JSON`,
  );
}
