/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type UpdateBlockOp = {
  op: "update_block";
  slideId: string;
  blockId: string;
  /**
   * Type-specific block fields to change.
   */
  set: { [k: string]: any };
};

/** @internal */
export type UpdateBlockOp$Outbound = {
  op: "update_block";
  slideId: string;
  blockId: string;
  set: { [k: string]: any };
};

/** @internal */
export const UpdateBlockOp$outboundSchema: z.ZodMiniType<
  UpdateBlockOp$Outbound,
  UpdateBlockOp
> = z.object({
  op: z.literal("update_block"),
  slideId: z.string(),
  blockId: z.string(),
  set: z.record(z.string(), z.any()),
});

export function updateBlockOpToJSON(updateBlockOp: UpdateBlockOp): string {
  return JSON.stringify(UpdateBlockOp$outboundSchema.parse(updateBlockOp));
}
