/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";

export const ViewCreateRequestVisibility = {
  Workspace: "workspace",
  Private: "private",
} as const;
export type ViewCreateRequestVisibility = ClosedEnum<
  typeof ViewCreateRequestVisibility
>;

export const ViewCreateRequestMode = {
  Table: "table",
  Component: "component",
  ComponentTable: "component_table",
  ItemList: "item_list",
  Kanban: "kanban",
  Calendar: "calendar",
  Project: "project",
  Forecast: "forecast",
  Group: "group",
  ReceivableBalance: "receivable_balance",
  PayableBalance: "payable_balance",
  Pnl: "pnl",
  BalanceSheet: "balance_sheet",
} as const;
export type ViewCreateRequestMode = ClosedEnum<typeof ViewCreateRequestMode>;

export type ViewCreateRequest = {
  title: string;
  objectType?: string | null | undefined;
  customObjectId?: string | null | undefined;
  formViewId?: string | null | undefined;
  visibility?: ViewCreateRequestVisibility | undefined;
  mode?: ViewCreateRequestMode | undefined;
  columnFieldIds?: Array<string> | undefined;
};

/** @internal */
export const ViewCreateRequestVisibility$outboundSchema: z.ZodMiniEnum<
  typeof ViewCreateRequestVisibility
> = z.enum(ViewCreateRequestVisibility);

/** @internal */
export const ViewCreateRequestMode$outboundSchema: z.ZodMiniEnum<
  typeof ViewCreateRequestMode
> = z.enum(ViewCreateRequestMode);

/** @internal */
export type ViewCreateRequest$Outbound = {
  title: string;
  object_type?: string | null | undefined;
  custom_object_id?: string | null | undefined;
  form_view_id?: string | null | undefined;
  visibility: string;
  mode: string;
  column_field_ids?: Array<string> | undefined;
};

/** @internal */
export const ViewCreateRequest$outboundSchema: z.ZodMiniType<
  ViewCreateRequest$Outbound,
  ViewCreateRequest
> = z.pipe(
  z.object({
    title: z.string(),
    objectType: z.optional(z.nullable(z.string())),
    customObjectId: z.optional(z.nullable(z.string())),
    formViewId: z.optional(z.nullable(z.string())),
    visibility: z._default(
      ViewCreateRequestVisibility$outboundSchema,
      "workspace",
    ),
    mode: z._default(ViewCreateRequestMode$outboundSchema, "table"),
    columnFieldIds: z.optional(z.array(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      objectType: "object_type",
      customObjectId: "custom_object_id",
      formViewId: "form_view_id",
      columnFieldIds: "column_field_ids",
    });
  }),
);

export function viewCreateRequestToJSON(
  viewCreateRequest: ViewCreateRequest,
): string {
  return JSON.stringify(
    ViewCreateRequest$outboundSchema.parse(viewCreateRequest),
  );
}
