/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type WorkforceOrganizationSummary = {
  positions: number;
  planned: number;
  readyToHire: number;
  recruiting: number;
  interviewing: number;
  offer: number;
  filled: number;
  unassignedJobs: number;
};

/** @internal */
export const WorkforceOrganizationSummary$inboundSchema: z.ZodMiniType<
  WorkforceOrganizationSummary,
  unknown
> = z.pipe(
  z.object({
    positions: z._default(types.number(), 0),
    planned: z._default(types.number(), 0),
    ready_to_hire: z._default(types.number(), 0),
    recruiting: z._default(types.number(), 0),
    interviewing: z._default(types.number(), 0),
    offer: z._default(types.number(), 0),
    filled: z._default(types.number(), 0),
    unassigned_jobs: z._default(types.number(), 0),
  }),
  z.transform((v) => {
    return remap$(v, {
      "ready_to_hire": "readyToHire",
      "unassigned_jobs": "unassignedJobs",
    });
  }),
);

export function workforceOrganizationSummaryFromJSON(
  jsonString: string,
): SafeParseResult<WorkforceOrganizationSummary, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WorkforceOrganizationSummary$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WorkforceOrganizationSummary' from JSON`,
  );
}
